/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

import 'dart:convert';
import 'dart:typed_data';

import 'crc.dart';
import 'fit.dart';

/// A growable byte sink. Multi-byte writes default to little-endian, which is
/// what every FIT producer uses, but take the endianness the caller's message
/// definition announced.
///
/// [replaceRange] exists for one reason: a FIT file header states the size of
/// the data that follows it, which is only known once encoding is done, so the
/// encoder reserves the header up front and patches it in `FitEncoder.close`.
class ByteWriter {
  ByteWriter([int initialCapacity = 4096])
      : _buffer = Uint8List(initialCapacity > 0 ? initialCapacity : 16) {
    _data = ByteData.sublistView(_buffer);
  }

  Uint8List _buffer;
  late ByteData _data;
  int _size = 0;

  int get size => _size;

  bool get isEmpty => _size == 0;

  void _ensureCapacity(int additional) {
    final required = _size + additional;
    if (required <= _buffer.length) return;
    var newSize = _buffer.length;
    while (newSize < required) {
      newSize *= 2;
    }
    final grown = Uint8List(newSize);
    grown.setRange(0, _size, _buffer);
    _buffer = grown;
    _data = ByteData.sublistView(_buffer);
  }

  void writeByte(int value) {
    _ensureCapacity(1);
    _buffer[_size++] = value & 0xFF;
  }

  void writeBytes(List<int> bytes) {
    _ensureCapacity(bytes.length);
    _buffer.setRange(_size, _size + bytes.length, bytes);
    _size += bytes.length;
  }

  Endian _endian(Endianness endianness) =>
      endianness == Endianness.little ? Endian.little : Endian.big;

  void writeUint16(int value, [Endianness endianness = Endianness.little]) {
    _ensureCapacity(2);
    _data.setUint16(_size, value & 0xFFFF, _endian(endianness));
    _size += 2;
  }

  void writeInt16(int value, [Endianness endianness = Endianness.little]) {
    _ensureCapacity(2);
    _data.setInt16(_size, value.toSigned(16), _endian(endianness));
    _size += 2;
  }

  void writeUint32(int value, [Endianness endianness = Endianness.little]) {
    _ensureCapacity(4);
    _data.setUint32(_size, value & 0xFFFFFFFF, _endian(endianness));
    _size += 4;
  }

  void writeInt32(int value, [Endianness endianness = Endianness.little]) {
    _ensureCapacity(4);
    _data.setInt32(_size, value.toSigned(32), _endian(endianness));
    _size += 4;
  }

  /// Writes eight bytes of [value]'s bit pattern.
  ///
  /// Signed and unsigned are the same write: `setInt64` stores two's complement,
  /// which is exactly what a `uint64` above 2^63 is being held as.
  void writeUint64(int value, [Endianness endianness = Endianness.little]) =>
      writeInt64(value, endianness);

  void writeInt64(int value, [Endianness endianness = Endianness.little]) {
    _ensureCapacity(8);
    _data.setInt64(_size, value, _endian(endianness));
    _size += 8;
  }

  void writeFloat32(double value, [Endianness endianness = Endianness.little]) {
    _ensureCapacity(4);
    _data.setFloat32(_size, value, _endian(endianness));
    _size += 4;
  }

  void writeFloat64(double value, [Endianness endianness = Endianness.little]) {
    _ensureCapacity(8);
    _data.setFloat64(_size, value, _endian(endianness));
    _size += 8;
  }

  /// Writes the UTF-8 bytes of [value] followed by a NUL terminator.
  void writeString(String value) {
    writeBytes(utf8.encode(value));
    writeByte(0);
  }

  /// Overwrites [bytes.length] bytes starting at [startIndex], which must
  /// already be written.
  void replaceRange(int startIndex, List<int> bytes) {
    if (startIndex < 0 || startIndex + bytes.length > _size) {
      throw ArgumentError(
        'replaceRange($startIndex, ${bytes.length}) is outside the $_size bytes written',
      );
    }
    _buffer.setRange(startIndex, startIndex + bytes.length, bytes);
  }

  /// CRC of the bytes written so far, computed in place.
  ///
  /// Exists so `FitEncoder.close` can checksum the file without first copying it
  /// out — on a large activity the copy costs more than the CRC.
  int crc() => Crc.calculate(_buffer, 0, _size);

  Uint8List toBytes() =>
      Uint8List.fromList(Uint8List.sublistView(_buffer, 0, _size));
}
