/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

import 'base_type.dart';
import 'byte_reader.dart';
import 'byte_writer.dart';
import 'field_base.dart';

/// One entry of a message definition record: which field, how wide, what type.
class FieldDefinition {
  const FieldDefinition(this.num, this.size, this.typeId);

  FieldDefinition.ofBaseType(int num, int size, BaseType baseType)
      : this(num, size, baseType.id);

  FieldDefinition.ofField(FieldBase field)
      : this(field.fieldNum, field.size,
            field.declaredTypeId ?? field.baseType.id);

  final int num;
  final int size;
  final int typeId;

  /// The base type this definition names.
  ///
  /// Null when a producer wrote a type byte outside the 17 the protocol defines,
  /// which happens in the wild; the decoder then skips the field.
  BaseType? get baseType => BaseType.fromId(typeId);

  /// Number of values packed into this field.
  int get count {
    final type = baseType;
    if (type == null || type.size == 0) return 0;
    return size ~/ type.size;
  }

  void write(ByteWriter writer) {
    writer.writeByte(num);
    writer.writeByte(size);
    writer.writeByte(typeId);
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldDefinition &&
          other.num == num &&
          other.size == size &&
          other.typeId == typeId;

  @override
  int get hashCode => (num * 31 + size) * 31 + typeId;

  @override
  String toString() =>
      'FieldDefinition(num: $num, size: $size, type: ${baseType ?? typeId})';

  static FieldDefinition read(ByteReader reader) =>
      FieldDefinition(reader.readByte(), reader.readByte(), reader.readByte());
}

/// A field declared at runtime by a `developer_data_id` / `field_description`
/// pair rather than by the profile.
///
/// The definition record only carries the indices; resolving them to the
/// declaring messages is the decoder's job.
class DeveloperFieldDefinition {
  const DeveloperFieldDefinition(this.num, this.size, this.developerDataIndex);

  final int num;
  final int size;
  final int developerDataIndex;

  void write(ByteWriter writer) {
    writer.writeByte(num);
    writer.writeByte(size);
    writer.writeByte(developerDataIndex);
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeveloperFieldDefinition &&
          other.num == num &&
          other.size == size &&
          other.developerDataIndex == developerDataIndex;

  @override
  int get hashCode => (num * 31 + size) * 31 + developerDataIndex;

  @override
  String toString() =>
      'DeveloperFieldDefinition(num: $num, size: $size, dev: $developerDataIndex)';

  static DeveloperFieldDefinition read(ByteReader reader) =>
      DeveloperFieldDefinition(
        reader.readByte(),
        reader.readByte(),
        reader.readByte(),
      );
}
