/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// Protocol-level constants shared by the decoder and the encoder.
abstract final class Fit {
  static const int profileVersionScale = 1000;
  static const int profileMajorVersion = 21;
  static const int profileMinorVersion = 215;

  /// Profile version as encoded in the FIT file header.
  static const int profileVersion =
      profileMajorVersion * profileVersionScale + profileMinorVersion;

  /// Seconds between the UNIX epoch and the FIT epoch (1989-12-31T00:00:00Z).
  static const int epochOffsetSeconds = 631065600;

  static const double fieldDefaultScale = 1.0;
  static const double fieldDefaultOffset = 0.0;

  /// A field is length-prefixed by a single byte, so it can never exceed 255 bytes.
  static const int maxFieldSize = 255;

  /// One byte of the maximum is reserved for the NUL terminator appended to every string.
  static const int stringMaxByteCount = maxFieldSize - 1;

  static const int compressedHeaderMask = 0x80;
  static const int mesgDefinitionMask = 0x40;
  static const int mesgHeaderMask = 0x00;
  static const int crcSize = 2;
  static const int numLocalMesgDefs = 16;
  static const int hdrTypeMask = 0x0F;
  static const int hdrTypeDefBit = 0x40;
  static const int devDataMask = 0x20;
  static const int localMesgNumMask = 0x0F;
  static const int headerWithCrcSize = 14;
  static const int headerWithoutCrcSize = 12;
}

/// Selects which of a field's meanings to read or write.
///
/// A FIT field can carry a different meaning depending on a sibling field's
/// value (`event_data` means `gear_change_data` when `event` is
/// `rear_gear_change`). Those alternatives are the field's *subfields*.
///
/// Sealed, so a `switch` over one is exhaustive without a default arm.
sealed class SubFieldSelector {
  const SubFieldSelector();
}

/// Ignore subfields and use the field's own type, scale and offset.
final class MainFieldSelector extends SubFieldSelector {
  const MainFieldSelector();

  @override
  bool operator ==(Object other) => other is MainFieldSelector;

  @override
  int get hashCode => 0x4d41494e;

  @override
  String toString() => 'SubFieldSelector.mainField';
}

/// Use whichever subfield the surrounding message currently satisfies, if any.
final class ActiveSelector extends SubFieldSelector {
  const ActiveSelector();

  @override
  bool operator ==(Object other) => other is ActiveSelector;

  @override
  int get hashCode => 0x41435456;

  @override
  String toString() => 'SubFieldSelector.active';
}

/// Use the subfield at this position in the field's subfield list.
final class IndexSelector extends SubFieldSelector {
  const IndexSelector(this.index);

  final int index;

  @override
  bool operator ==(Object other) =>
      other is IndexSelector && other.index == index;

  @override
  int get hashCode => index.hashCode;

  @override
  String toString() => 'SubFieldSelector.atIndex($index)';
}

/// Use the subfield with this profile name.
final class NamedSelector extends SubFieldSelector {
  const NamedSelector(this.name);

  final String name;

  @override
  bool operator ==(Object other) =>
      other is NamedSelector && other.name == name;

  @override
  int get hashCode => name.hashCode;

  @override
  String toString() => "SubFieldSelector.named('$name')";
}

/// The default selectors, as constants rather than fresh objects per call.
const SubFieldSelector mainFieldSelector = MainFieldSelector();

/// See [ActiveSelector].
const SubFieldSelector activeSelector = ActiveSelector();

/// Byte order of a message's field values, declared per message definition.
enum Endianness {
  little(0),
  big(1);

  const Endianness(this.value);

  final int value;

  /// The architecture byte's meaning, or null when it is neither 0 nor 1.
  static Endianness? fromValue(int value) => switch (value) {
        0 => Endianness.little,
        1 => Endianness.big,
        _ => null,
      };
}

/// FIT protocol version from the file header.
enum ProtocolVersion {
  invalid(0x00),
  v1_0(0x10),
  v2_0(0x20);

  const ProtocolVersion(this.value);

  final int value;

  static ProtocolVersion fromValue(int value) => switch (value) {
        0x10 => ProtocolVersion.v1_0,
        0x20 => ProtocolVersion.v2_0,
        _ => ProtocolVersion.invalid,
      };
}
