/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

import 'fit.dart';

/// Conversion between FIT timestamps and [DateTime].
///
/// FIT counts seconds from 1989-12-31T00:00:00Z, not from the UNIX epoch.
///
/// Values below [systemTimeThreshold] are not wall-clock times at all: a device
/// that has not acquired a date yet writes seconds since power-on there. Those
/// cannot be turned into a [DateTime] and come back as null.
///
/// Every [DateTime] produced here is in UTC. A FIT timestamp carries no zone, so
/// rendering one in local time is the caller's decision, not the SDK's.
abstract final class FitDateTime {
  /// Seconds between 1970-01-01T00:00:00Z and the FIT epoch.
  static const int epochOffsetSeconds = Fit.epochOffsetSeconds;

  /// Below this, a timestamp is seconds since device power-on rather than a date.
  static const int systemTimeThreshold = 0x10000000;

  static DateTime? toDateTime(int timestamp) {
    if (timestamp < systemTimeThreshold) return null;
    return DateTime.fromMillisecondsSinceEpoch(
      (timestamp + epochOffsetSeconds) * 1000,
      isUtc: true,
    );
  }

  static int toTimestamp(DateTime dateTime) =>
      dateTime.toUtc().millisecondsSinceEpoch ~/ 1000 - epochOffsetSeconds;

  /// True when [timestamp] is a device uptime rather than a date.
  static bool isSystemTime(int timestamp) => timestamp < systemTimeThreshold;
}
