/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'byte_writer.dart';
import 'developer_field_description.dart';
import 'file_header.dart';
import 'fit.dart';
import 'mesg.dart';
import 'mesg_definition.dart';
import 'messages.dart';
import 'types.dart';

/// Writes FIT files.
///
/// ```dart
/// final bytes = encodeFit((encoder) {
///   encoder.write(FileIdMesg()
///     ..type = File.activity
///     ..timeCreated = DateTime.timestamp());
///   encoder.write(RecordMesg()..heartRate = 140);
/// });
/// ```
///
/// A FIT file must open with a `file_id` message; nothing here enforces that,
/// but readers will reject a file without one.
///
/// [close] is not optional. The file header states the size of the data that
/// follows it, which is only known once the last message is written, and the
/// file ends with a CRC over everything before it. Both are produced there.
class FitEncoder {
  FitEncoder({
    this.protocolVersionByte = 0x20,
    this.profileVersion = Fit.profileVersion,
    this.endianness = Endianness.little,
  }) {
    // Reserve the header; its data size is only known at close().
    _writer.writeBytes(Uint8List(Fit.headerWithCrcSize));
  }

  /// Protocol version byte to stamp into the header.
  ///
  /// Raw rather than a [ProtocolVersion] so that re-encoding a file written by a
  /// producer whose version the enum does not name reproduces its header.
  /// Defaults to [ProtocolVersion.v2_0]'s 0x20.
  final int protocolVersionByte;

  final int profileVersion;

  /// Architecture announced by the message definitions this encoder emits, and
  /// used for every multi-byte field value written under them. The file header
  /// itself is always little-endian, as the protocol requires.
  final Endianness endianness;

  final ByteWriter _writer = ByteWriter();

  /// Which layout each of the 16 local message numbers currently holds.
  final List<MesgDefinition?> _localDefinitions =
      List<MesgDefinition?>.filled(Fit.numLocalMesgDefs, null);
  int _nextLocalMesgNum = 0;
  bool _closed = false;

  /// (index, application) pairs whose `developer_data_id` is already in the file.
  final Set<String> _announcedDeveloperIds = <String>{};

  /// Number of messages written so far.
  int mesgCount = 0;

  FitEncoder writeAll(Iterable<Mesg> mesgs) {
    for (final mesg in mesgs) {
      write(mesg);
    }
    return this;
  }

  /// Writes [mesg], emitting a message definition first if the layout it needs
  /// is not already the one bound to a local message number.
  FitEncoder write(Mesg mesg) {
    _checkOpen();

    final definition = MesgDefinition.of(mesg, 0, endianness);
    final local = _localMesgNumFor(definition);

    final bound = MesgDefinition(
      local,
      definition.globalMesgNum,
      definition.endianness,
      definition.fieldDefinitions,
      definition.developerFieldDefinitions,
    );

    if (_localDefinitions[local]?.hasSameLayout(bound) != true) {
      bound.write(_writer);
      _localDefinitions[local] = bound;
    }

    mesg.write(_writer, bound);
    mesgCount++;
    return this;
  }

  /// Declares a developer field, writing the `developer_data_id` message that
  /// claims its index (once per application/index pair) followed by its
  /// `field_description` message.
  ///
  /// A data record can only carry a `DeveloperField` whose declaration precedes
  /// it in the file, so call this before writing the first message holding a
  /// field made from [description] — typically one obtained from
  /// [FitMessages.developerFieldDescriptions] after decoding, which closes the
  /// decode → re-encode loop, or built by hand alongside
  /// [DeveloperFieldDescription.createField].
  ///
  /// `field_description` stores scale and offset as single bytes; a
  /// [description] whose values do not fit those types (never the case for one
  /// produced by the decoder) is declared with them truncated.
  FitEncoder registerDeveloperField(DeveloperFieldDescription description) {
    _checkOpen();

    final application = description.applicationId;
    final announceKey =
        '${description.developerDataIndex}:${application?.join(',') ?? ''}';
    if (_announcedDeveloperIds.add(announceKey)) {
      final idMesg = DeveloperDataIdMesg()
        ..developerDataIndex = description.developerDataIndex;
      if (application != null) idMesg.applicationId = application;
      if (description.applicationVersion != null) {
        idMesg.applicationVersion = description.applicationVersion;
      }
      write(idMesg);
    }

    final fieldMesg = FieldDescriptionMesg()
      ..developerDataIndex = description.developerDataIndex
      ..fieldDefinitionNumber = description.fieldDefinitionNumber
      ..fitBaseTypeId = FitBaseType.fromValue(description.baseType.id)
      ..fieldName = <String?>[description.fieldName];
    if (description.units.isNotEmpty) {
      fieldMesg.units = <String?>[description.units];
    }
    if (description.scale != Fit.fieldDefaultScale) {
      fieldMesg.scale = description.scale.toInt();
    }
    if (description.offset != Fit.fieldDefaultOffset) {
      fieldMesg.offset = description.offset.toInt();
    }
    if (description.nativeFieldNum != null) {
      fieldMesg.nativeFieldNum = description.nativeFieldNum;
    }
    write(fieldMesg);
    return this;
  }

  /// Writes a definition explicitly, claiming its local message number.
  FitEncoder writeDefinition(MesgDefinition mesgDefinition) {
    _checkOpen();
    mesgDefinition.write(_writer);
    _localDefinitions[mesgDefinition.localMesgNum] = mesgDefinition;
    return this;
  }

  /// Finishes the file: patches the header's data size and header CRC, then
  /// appends the file CRC. Returns the complete file.
  Uint8List close() {
    _checkOpen();
    _closed = true;

    final dataSize = _writer.size - Fit.headerWithCrcSize;
    final header = FileHeader(
      protocolVersionByte: protocolVersionByte,
      profileVersion: profileVersion,
      dataSize: dataSize,
    );
    header.updateCrc();
    _writer.replaceRange(0, header.toBytes());

    _writer.writeUint16(_writer.crc());
    return _writer.toBytes();
  }

  void _checkOpen() {
    if (_closed) throw StateError('this encoder is closed');
  }

  /// Finds the local message number to write [definition] under.
  ///
  /// Reuses the slot already holding this exact layout, so a run of records
  /// costs one definition record rather than one per message. Otherwise takes
  /// the next slot round-robin: there are only 16, and evicting the
  /// least-recently-claimed is what the other SDKs do.
  int _localMesgNumFor(MesgDefinition definition) {
    for (var i = 0; i < _localDefinitions.length; i++) {
      // hasSameLayout ignores the local number, so the incoming definition can
      // be compared directly against each slot, whatever it is bound to.
      if (_localDefinitions[i]?.hasSameLayout(definition) == true) return i;
    }

    for (var i = 0; i < _localDefinitions.length; i++) {
      if (_localDefinitions[i] == null) return i;
    }

    final local = _nextLocalMesgNum;
    _nextLocalMesgNum = (_nextLocalMesgNum + 1) % Fit.numLocalMesgDefs;
    _localDefinitions[local] = null;
    return local;
  }
}

/// Encodes a FIT file from [block], closing the encoder for you.
///
/// ```dart
/// final bytes = encodeFit((encoder) => encoder.write(FileIdMesg()));
/// ```
///
/// [endianness] is the architecture the emitted definitions announce;
/// little-endian is what every Garmin producer writes, and reading is unaffected
/// either way.
Uint8List encodeFit(
  void Function(FitEncoder encoder) block, {
  Endianness endianness = Endianness.little,
}) {
  final encoder = FitEncoder(endianness: endianness);
  block(encoder);
  return encoder.close();
}
