/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

import 'dart:async';
import 'dart:typed_data';

import 'byte_reader.dart';
import 'crc.dart';
import 'decode_options.dart';
import 'file_header.dart';
import 'fit.dart';
import 'fit_exception.dart';
import 'fit_messages.dart';
import 'hr_mesg_util.dart';
import 'mesg.dart';
import 'mesg_cursor.dart';

/// Reads FIT files.
///
/// ```dart
/// final result = FitDecoder(bytes).decode();
/// for (final error in result.errors) print(error);
/// for (final record in result.messages.recordMesgs) print(record.heartRate);
/// ```
///
/// [decode] never throws on malformed input: it returns everything that decoded
/// before the problem alongside a description of it, because a truncated file
/// usually still holds most of an activity. Neither does [read] or
/// [decodeAsync], which report through their return values. Only [asIterable]
/// and [stream] throw, having no place to carry an error.
///
/// "Never throws" means no [Exception] escapes. An [Error] — an
/// `OutOfMemoryError`, a `StackOverflowError` — does propagate: those say the
/// runtime is out of resources, not that the file is malformed, and swallowing
/// one into [DecodeResult.errors] would report a broken process as a corrupt
/// activity while leaving the caller to run on in an unusable isolate.
///
/// ## Decoding off the UI thread
///
/// [decode] is synchronous and CPU-bound, so a large activity will drop frames
/// if it runs on Flutter's UI isolate. Two ways out, neither of which this
/// package has to import `dart:isolate` for — it stays usable on the web:
///
/// ```dart
/// // Another isolate. Not available on the web.
/// final result = await Isolate.run(() => FitDecoder(bytes).decode());
///
/// // Same isolate, yielding to the event loop every [chunkSize] messages.
/// // Slower overall, but the UI keeps painting, and it works everywhere.
/// final result = await FitDecoder(bytes).decodeAsync();
/// ```
class FitDecoder {
  FitDecoder(this._bytes);

  final Uint8List _bytes;

  /// True when the input opens with a plausible FIT header.
  bool isFit() => looksLikeFit(_bytes);

  /// True when every chained file's header CRC and file CRC check out.
  ///
  /// The header CRC lives in the 14-byte header form only, and even there a
  /// producer may leave it at 0x0000 to mean "not computed", which the protocol
  /// allows and this accepts. Anything else has to match the CRC over the first
  /// 12 bytes. The 12-byte header form carries no header CRC at all.
  bool checkIntegrity() {
    if (!isFit()) return false;
    try {
      if (!_headerCrcsAreValid()) return false;
      final cursor = MesgCursor(
        ByteReader(_bytes),
        const DecodeOptions(mode: DecodeMode.normal),
      );
      while (cursor.moveNext()) {}
      return true;
    } on Exception {
      // Same safety net as decode(): an integrity check is a question, not an
      // operation that may fail. An Error still propagates.
      return false;
    }
  }

  /// Checks the header CRC of every file in the stream.
  ///
  /// Walks the chain by itself rather than going through [MesgCursor], which
  /// reports only what it reads past the header. A length that does not add up
  /// ends the walk without a verdict: the record loop in [checkIntegrity] is
  /// what reports a truncated or overlong file, and reporting it twice would
  /// hide the more precise message.
  bool _headerCrcsAreValid() {
    var offset = 0;
    while (offset < _bytes.length) {
      if (_bytes.length - offset < Fit.headerWithoutCrcSize) return false;

      final header = FileHeader.read(ByteReader(_bytes, offset));
      if (!header.isValid) return false;

      // 0x0000 is how a producer says "header CRC not filled in".
      if (header.hasCrc && header.headerCrc != _unsetHeaderCrc) {
        final computed = Crc.calculate(
          _bytes,
          offset,
          offset + Fit.headerWithoutCrcSize,
        );
        if (computed != header.headerCrc) return false;
      }

      final next = offset + header.headerSize + header.dataSize + Fit.crcSize;
      if (next <= offset || next > _bytes.length) return true;
      offset = next;
    }
    return true;
  }

  /// Decodes the whole input.
  ///
  /// Never throws an [Exception]: problems come back in [DecodeResult.errors].
  /// An [Error] propagates — see the class documentation.
  DecodeResult decode([DecodeOptions options = const DecodeOptions()]) {
    final messages = FitMessages();
    final ordered = <Mesg>[];
    final errors = <FitError>[];

    final cursor = MesgCursor(ByteReader(_bytes), options);
    try {
      while (cursor.moveNext()) {
        final mesg = cursor.current;
        ordered.add(mesg);
        messages.add(mesg);
      }
    } on FitFormatException catch (e) {
      errors.add(FitError.fromFormatException(e));
    } on FitException catch (e) {
      errors.add(FitError(e.message, -1, e));
    } on Exception catch (e) {
      // Last-resort net. Malformed input is supposed to surface as a
      // FitFormatException, but decode() promises never to throw, so an
      // unforeseen failure becomes an error entry rather than escaping.
      // Deliberately Exception and not Object: an Error means the runtime is in
      // trouble, which is not something a FitError can describe.
      errors.add(FitError(_unexpectedMessage(e), -1, e));
    }

    messages
        .addDeveloperFieldDescriptions(cursor.developerData.fieldDescriptions);

    if (options.mergeHeartRates && options.expandComponents) {
      HrMesgUtil.mergeHeartRates(messages.hrMesgs, messages.recordMesgs);
    }

    return DecodeResult(
      messages: messages,
      mesgs: ordered,
      profileVersion: cursor.profileVersion,
      errors: errors,
    );
  }

  /// [decode], yielding to the event loop every [chunkSize] messages.
  ///
  /// Same result, same guarantees, and no isolate: on Flutter this is what keeps
  /// a large activity from dropping frames on platforms where `Isolate.run` is
  /// unavailable, the web among them. Lower [chunkSize] means smoother frames
  /// and a slower decode.
  Future<DecodeResult> decodeAsync({
    DecodeOptions options = const DecodeOptions(),
    int chunkSize = 512,
  }) async {
    final messages = FitMessages();
    final ordered = <Mesg>[];
    final errors = <FitError>[];

    final cursor = MesgCursor(ByteReader(_bytes), options);
    var sinceYield = 0;
    var running = true;
    while (running) {
      try {
        running = cursor.moveNext();
      } on FitFormatException catch (e) {
        errors.add(FitError.fromFormatException(e));
        break;
      } on FitException catch (e) {
        errors.add(FitError(e.message, -1, e));
        break;
      } on Exception catch (e) {
        errors.add(FitError(_unexpectedMessage(e), -1, e));
        break;
      }
      if (!running) break;

      final mesg = cursor.current;
      ordered.add(mesg);
      messages.add(mesg);

      if (++sinceYield >= chunkSize) {
        sinceYield = 0;
        // Duration.zero rather than a microtask: only a macrotask lets the
        // embedder paint a frame in between.
        await Future<void>.delayed(Duration.zero);
      }
    }

    messages
        .addDeveloperFieldDescriptions(cursor.developerData.fieldDescriptions);

    if (options.mergeHeartRates && options.expandComponents) {
      HrMesgUtil.mergeHeartRates(messages.hrMesgs, messages.recordMesgs);
    }

    return DecodeResult(
      messages: messages,
      mesgs: ordered,
      profileVersion: cursor.profileVersion,
      errors: errors,
    );
  }

  /// Decodes lazily, handing each message to [onMesg] as it is read.
  ///
  /// Nothing is retained, so this is the entry point for files too large to hold
  /// decoded in memory. Returns the errors that stopped the decode, if any: like
  /// [decode], it never throws an [Exception] on malformed input. An exception
  /// raised by [onMesg] itself does propagate, and so does an [Error] from
  /// either side.
  List<FitError> read(
    void Function(Mesg mesg) onMesg, [
    DecodeOptions options = const DecodeOptions(),
  ]) {
    final errors = <FitError>[];
    final cursor = MesgCursor(ByteReader(_bytes), options);
    while (true) {
      // Only the decode is guarded: an exception out of [onMesg] is the caller's
      // own and must not be swallowed as a file error.
      final bool hasNext;
      try {
        hasNext = cursor.moveNext();
      } on FitFormatException catch (e) {
        errors.add(FitError.fromFormatException(e));
        break;
      } on FitException catch (e) {
        errors.add(FitError(e.message, -1, e));
        break;
      } on Exception catch (e) {
        // See decode(): anything unforeseen is reported, not thrown.
        errors.add(FitError(_unexpectedMessage(e), -1, e));
        break;
      }
      if (!hasNext) break;
      onMesg(cursor.current);
    }
    return errors;
  }

  /// The file's messages as a lazily decoded [Iterable].
  ///
  /// Throws [FitFormatException] mid-iteration on malformed input. Note that
  /// [DecodeOptions.mergeHeartRates] cannot apply here: merging needs the whole
  /// file, which is exactly what streaming avoids holding.
  ///
  /// ```dart
  /// for (final record in decoder.asIterable().whereType<RecordMesg>()) {
  ///   print(record.heartRate);
  /// }
  /// ```
  Iterable<Mesg> asIterable([
    DecodeOptions options = const DecodeOptions(),
  ]) =>
      MesgIterable(() => MesgCursor(ByteReader(_bytes), options));

  /// The file's messages as a [Stream], yielding to the event loop every
  /// [chunkSize] messages.
  ///
  /// The asynchronous half of [asIterable], and the shape Flutter code reaches
  /// for: a `StreamBuilder` can render an activity as it decodes, and the
  /// pauses keep the UI responsive while it does. Throws mid-stream on malformed
  /// input, exactly as [asIterable] does. [DecodeOptions.mergeHeartRates] does
  /// not apply, for the same reason.
  ///
  /// ```dart
  /// await for (final record
  ///     in decoder.stream().where((m) => m is RecordMesg).cast<RecordMesg>()) {
  ///   print(record.heartRate);
  /// }
  /// ```
  Stream<Mesg> stream({
    DecodeOptions options = const DecodeOptions(),
    int chunkSize = 512,
  }) async* {
    final cursor = MesgCursor(ByteReader(_bytes), options);
    var sinceYield = 0;
    while (cursor.moveNext()) {
      yield cursor.current;
      if (++sinceYield >= chunkSize) {
        sinceYield = 0;
        await Future<void>.delayed(Duration.zero);
      }
    }
  }

  /// True when [bytes] opens with a plausible FIT header.
  static bool looksLikeFit(Uint8List bytes) {
    if (bytes.length < Fit.headerWithoutCrcSize) return false;
    try {
      final header = FileHeader.read(ByteReader(bytes));
      return header.isValid &&
          bytes.length >= header.headerSize + header.dataSize;
    } on Exception {
      return false;
    }
  }

  /// A 14-byte header whose CRC field is zero is one that never computed it.
  static const int _unsetHeaderCrc = 0;

  /// Describes an exception the decoder was not expecting to see at all.
  static String _unexpectedMessage(Object e) {
    final kind = e.runtimeType.toString();
    final detail = e.toString();
    return detail.isEmpty
        ? 'unexpected $kind while decoding'
        : 'unexpected $kind while decoding: $detail';
  }
}

/// Reads every byte of [input], then decodes it.
///
/// The decoder needs the whole file in memory — FIT records are variable-length
/// and chained files have to be seeked across — so this collects the stream
/// rather than decoding it incrementally. It exists because a file, an HTTP
/// response and a platform channel all hand Dart a `Stream<List<int>>`.
Future<DecodeResult> decodeFitStream(
  Stream<List<int>> input, {
  DecodeOptions options = const DecodeOptions(),
}) async {
  final builder = BytesBuilder(copy: false);
  await for (final chunk in input) {
    builder.add(chunk);
  }
  return FitDecoder(builder.takeBytes()).decode(options);
}
