/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'base_type.dart';

/// Coercion helpers between the boxed `Object?` values a `FieldBase` stores and
/// the two numeric types Dart works in.
///
/// FIT is self-describing, so a field's runtime type is only known from the
/// profile or from the message definition in the file. Values are therefore kept
/// boxed and narrowed at the API boundary by the generated typed accessors.
///
/// Dart has no unsigned types and exactly one integer type, so every one of the
/// 15 integral base types is held as an `int` and the two float ones as a
/// `double`. Signedness lives in the [BaseType], which is what the reader and
/// the writer work from; a `uint64` above 2^63 is held as the negative `int`
/// sharing its bit pattern, exactly as the Java SDK holds one in a `long`.
abstract final class FitValues {
  /// Scratch buffer for the float bit-pattern conversions below. Single-threaded
  /// by construction: Dart isolates share no memory, so one per isolate is one
  /// per thread of execution.
  static final ByteData _scratch = ByteData(8);

  /// Widens any FIT numeric value to [double].
  ///
  /// Returns [double.nan] for a value that is not numeric, which every caller
  /// treats as invalid.
  static double toDouble(Object? value) {
    if (value is double) return value;
    if (value is int) return value.toDouble();
    if (value is bool) return value ? 1.0 : 0.0;
    return double.nan;
  }

  /// Narrows any FIT numeric value to [int] without going through [double].
  ///
  /// Bit-exact for 64-bit values, which [toDouble] is not: a double has 53 bits
  /// of mantissa, so routing a uint64 through it silently rounds.
  static int toInt(Object? value) {
    if (value is int) return value;
    if (value is bool) return value ? 1 : 0;
    if (value is double) {
      if (value.isNaN || value.isInfinite) return 0;
      return value.toInt();
    }
    return 0;
  }

  /// Renders a value the way the FIT profile names it, for diagnostics.
  static String toStringValue(Object? value) {
    if (value == null) return '';
    if (value is String) return value;
    return value.toString();
  }

  /// The raw bit pattern of [value], sized to [baseType].
  ///
  /// The base type has to be passed in: Dart holds a `float32` and a `float64`
  /// in the same `double`, so unlike Kotlin there is nothing in the value itself
  /// to say which of the two bit layouts is wanted.
  static int rawBits(Object? value, BaseType baseType) {
    if (value == null) return 0;
    switch (baseType) {
      case BaseType.float32:
        _scratch.setFloat32(0, toDouble(value), Endian.little);
        return _scratch.getUint32(0, Endian.little);
      case BaseType.float64:
        _scratch.setFloat64(0, toDouble(value), Endian.little);
        // Read back as signed: a double's bit pattern does not fit an unsigned
        // Dart int, and every caller masks byte by byte anyway.
        return _scratch.getInt64(0, Endian.little);
      default:
        return toInt(value);
    }
  }

  /// Reinterprets the low 32 bits of [bits] as a `float32`.
  static double float32FromBits(int bits) {
    _scratch.setUint32(0, bits & 0xFFFFFFFF, Endian.little);
    return _scratch.getFloat32(0, Endian.little);
  }

  /// Reinterprets all 64 bits of [bits] as a `float64`.
  static double float64FromBits(int bits) {
    _scratch.setInt64(0, bits, Endian.little);
    return _scratch.getFloat64(0, Endian.little);
  }
}
