/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

import 'accumulator.dart';
import 'base_type.dart';
import 'bit_stream.dart';
import 'byte_reader.dart';
import 'byte_writer.dart';
import 'developer_field.dart';
import 'factory.dart';
import 'field.dart';
import 'field_component.dart';
import 'field_definition.dart';
import 'fit.dart';
import 'fit_exception.dart';
import 'fit_values.dart';
import 'mesg_definition.dart';

/// A FIT message: a bag of numbered fields.
///
/// This untyped form is the real data model. The generated `*Mesg` subclasses
/// add named accessors over the same field numbers and hold no state of their
/// own, so anything reachable through them is reachable here.
class Mesg {
  Mesg(this.mesgName, this.globalMesgNum);

  /// Copy constructor. Drops fields that ended up with no values.
  ///
  /// The fields are deep-copied: a copy and its original share no mutable state,
  /// so mutating either one leaves the other untouched.
  Mesg.from(Mesg mesg)
      : mesgName = mesg.mesgName,
        globalMesgNum = mesg.globalMesgNum {
    localMesgNum = mesg.localMesgNum;
    decoderMesgIndex = mesg.decoderMesgIndex;
    mesg.fieldMap.forEach((fieldNum, field) {
      if (field.hasValues) fieldMap[fieldNum] = Field.from(field);
    });
    mesg.developerFieldMap.forEach((key, field) {
      if (field.hasValues) developerFieldMap[key] = DeveloperField.from(field);
    });
  }

  /// Adoption constructor: takes over [mesg]'s fields without copying them.
  ///
  /// Only for a caller that owns [mesg] outright and discards it afterwards —
  /// the decoder, which builds a fresh [Mesg] per record and hands it to
  /// [Factory.typed]. Sharing the fields there is safe precisely because nothing
  /// else ever saw them; anywhere else, use [Mesg.from].
  Mesg.adopt(Mesg mesg)
      : mesgName = mesg.mesgName,
        globalMesgNum = mesg.globalMesgNum {
    localMesgNum = mesg.localMesgNum;
    decoderMesgIndex = mesg.decoderMesgIndex;
    fieldMap.addAll(mesg.fieldMap);
    developerFieldMap.addAll(mesg.developerFieldMap);
  }

  /// [getActiveSubFieldIndex] returns this when no subfield applies.
  static const int mainField = -1;

  final String mesgName;
  final int globalMesgNum;

  // Dart's Map literal is insertion-ordered, so re-encoding preserves the
  // producer's field order without any extra bookkeeping.
  final Map<int, Field> fieldMap = <int, Field>{};
  final Map<DeveloperDataKey, DeveloperField> developerFieldMap =
      <DeveloperDataKey, DeveloperField>{};

  /// Local message number this was read with, or will be written with.
  int localMesgNum = 0;

  /// Position of this message in the file, counting from 0.
  int decoderMesgIndex = 0;

  /// Removes fields left with no values, in place. What [Mesg.from] does by
  /// omission, for the adoption path: a field whose every value was the invalid
  /// sentinel stops being "present".
  void dropEmptyFields() {
    fieldMap.removeWhere((_, field) => !field.hasValues);
    developerFieldMap.removeWhere((_, field) => !field.hasValues);
  }

  List<Field> get fieldList => fieldMap.values.toList(growable: false);

  List<DeveloperField> get developerFieldList =>
      developerFieldMap.values.toList(growable: false);

  // No fieldCount getter here: FIT has a field called `field_count` on
  // exd_screen_configuration, and the generated accessor for it would clash.
  // Use fieldList.length.

  // ------------------------------------------------------------------ fields

  Field? getField(int fieldNum) => fieldMap[fieldNum];

  Field? getFieldNamed(String fieldName) {
    for (final field in fieldMap.values) {
      if (field.fieldName == fieldName) return field;
    }
    return null;
  }

  bool hasField(int fieldNum) => fieldMap.containsKey(fieldNum);

  void setField(Field field) {
    fieldMap[field.fieldNum] = field;
  }

  void removeField(int fieldNum) {
    fieldMap.remove(fieldNum);
  }

  /// Drops the fields that were synthesised by component expansion.
  void removeExpandedFields() {
    fieldMap.removeWhere((_, field) => field.isExpandedField);
  }

  // ------------------------------------------------------------------ values

  /// The value of field [fieldNum], scale and offset applied, or null when the
  /// field is absent or holds FIT's invalid sentinel.
  Object? getFieldValue(
    int fieldNum, [
    int index = 0,
    SubFieldSelector selector = activeSelector,
  ]) {
    final field = getField(fieldNum);
    if (field == null) return null;
    final subField = field.resolveSubField(selector, this);
    if (selector is IndexSelector || selector is NamedSelector) {
      // An explicitly named subfield that this message does not satisfy would
      // give a value under the wrong interpretation.
      if (subField != null && !subField.canMesgSupport(this)) return null;
    }
    return field.getValueWith(index, subField);
  }

  /// [getFieldValue] narrowed to [int], or null when the field is absent, holds
  /// the invalid sentinel, or turned out not to be integral after all.
  ///
  /// The generated accessors read through these three rather than casting: FIT
  /// is self-describing, so a producer can write a field under a type the
  /// profile does not declare, and a failed cast mid-decode would cost the
  /// caller the rest of the file to save one null.
  int? intFieldValue(
    int fieldNum, [
    int index = 0,
    SubFieldSelector selector = activeSelector,
  ]) {
    final value = getFieldValue(fieldNum, index, selector);
    return value is int ? value : null;
  }

  /// [getFieldValue] narrowed to [double]. An `int` widens rather than failing:
  /// a scaled field whose scale divides exactly still reads as a number.
  double? doubleFieldValue(
    int fieldNum, [
    int index = 0,
    SubFieldSelector selector = activeSelector,
  ]) {
    final value = getFieldValue(fieldNum, index, selector);
    return value is num ? value.toDouble() : null;
  }

  /// [getFieldValue] narrowed to [String].
  String? stringFieldValue(
    int fieldNum, [
    int index = 0,
    SubFieldSelector selector = activeSelector,
  ]) {
    final value = getFieldValue(fieldNum, index, selector);
    return value is String ? value : null;
  }

  void setFieldValue(
    int fieldNum,
    Object? value, [
    int index = 0,
    SubFieldSelector selector = mainFieldSelector,
  ]) {
    var field = getField(fieldNum);
    if (field == null) {
      field = _createFieldFor(fieldNum, value);
      setField(field);
    }
    final subField = field.resolveSubField(selector, this);
    if (subField != null && !subField.canMesgSupport(this)) {
      throw FitFieldException(
        'subfield ${subField.name} is not active on $mesgName; set its reference field first',
      );
    }
    field.setValueWith(value, index, subField);
  }

  /// The index of the subfield [fieldNum] currently resolves to, or [mainField]
  /// when the field's own meaning applies.
  int getActiveSubFieldIndex(int fieldNum) {
    final field = getField(fieldNum);
    if (field == null) return mainField;
    for (var i = 0; i < field.subFields.length; i++) {
      if (field.subFields[i].canMesgSupport(this)) return i;
    }
    return mainField;
  }

  Field _createFieldFor(int fieldNum, Object? value) {
    final known = Factory.createField(globalMesgNum, fieldNum);
    if (known != null) return known;
    final baseType = BaseType.of(value);
    if (baseType == null) {
      throw FitFieldException(
        'cannot infer a FIT base type for a value of type ${value.runtimeType}',
      );
    }
    return Factory.createDefaultField(fieldNum, baseType);
  }

  // -------------------------------------------------------- developer fields

  DeveloperField? getDeveloperField(DeveloperDataKey key) =>
      developerFieldMap[key];

  void setDeveloperField(DeveloperField field) {
    developerFieldMap[field.key] = field;
  }

  // -------------------------------------------------------------------- read

  /// Reads one data record laid out by [definition].
  void read(
    ByteReader reader,
    MesgDefinition definition,
    Accumulator accumulator, {
    bool expandComponents = true,
    DeveloperField? Function(DeveloperFieldDefinition)? developerFields,
  }) {
    for (final fieldDefinition in definition.fieldDefinitions) {
      final baseType = fieldDefinition.baseType;
      if (baseType == null) {
        // Unknown type byte: the width is still trustworthy, so skip exactly
        // that much and keep the record aligned.
        reader.skip(fieldDefinition.size);
        continue;
      }

      // Fields are created in the order the definition record lists them, not in
      // profile declaration order, so a decoded message preserves the producer's
      // layout and re-encoding does not reshuffle it.
      var field = getField(fieldDefinition.num);
      if (field == null) {
        field = Factory.createField(globalMesgNum, fieldDefinition.num) ??
            Factory.createDefaultField(fieldDefinition.num, baseType);
        setField(field);
      }

      field.declaredTypeId = fieldDefinition.typeId;
      field.read(reader, fieldDefinition.size, definition.endianness);

      if (field.isAccumulated) _seedAccumulator(field, accumulator);
    }

    // Expansion has to run after every field is read: a component's destination
    // field may be one that appears later in the record.
    if (expandComponents) {
      final expanded = <int>{};
      for (final field in fieldMap.values.toList(growable: false)) {
        _expandComponents(field, accumulator, expanded);
      }
    }

    for (final devDefinition in definition.developerFieldDefinitions) {
      final devField = developerFields?.call(devDefinition);
      if (devField == null) {
        // The declaring field_description has not been seen. The bytes are
        // unreadable but their width is known.
        reader.skip(devDefinition.size);
        continue;
      }
      devField.read(reader, devDefinition.size, definition.endianness);
      setDeveloperField(devField);
    }
  }

  void _seedAccumulator(Field field, Accumulator accumulator) {
    for (var index = 0; index < field.numValues; index++) {
      var value = FitValues.toDouble(field.getRawValue(index));

      // If some other field packs this one as a component, the seed must be
      // expressed in the component's units, not the field's.
      outer:
      for (final containing in fieldMap.values) {
        for (final component in containing.components) {
          if (component.fieldNum == field.fieldNum && component.accumulate) {
            value = ((value / field.scale) - field.offset + component.offset) *
                component.scale;
            break outer;
          }
        }
      }

      accumulator.create(globalMesgNum, field.fieldNum, FitValues.toInt(value));
    }
  }

  /// Unpacks [containingField]'s bit-packed components into their destination
  /// fields, recursively.
  ///
  /// [expandedSoFar] records which destination fields this message has already
  /// written, so the first component to reach a field replaces whatever the
  /// record stored there directly and later ones append. A record may carry both
  /// `avg_speed` and `enhanced_avg_speed`, and the expanded value is the
  /// authoritative one.
  void _expandComponents(
    Field containingField,
    Accumulator accumulator,
    Set<int> expandedSoFar,
  ) {
    if (!containingField.hasValues) return;

    // A field that is entirely the invalid sentinel packs nothing.
    if (!containingField.values.any(containingField.baseType.isValid)) return;

    // The active subfield decides which set of components applies, so it must be
    // resolved before any bits are read.
    final activeIndex = getActiveSubFieldIndex(containingField.fieldNum);
    final activeSubField = activeIndex == mainField
        ? null
        : containingField.getSubFieldAt(activeIndex);

    final List<FieldComponent> components;
    if (activeSubField != null && activeSubField.hasComponents) {
      components = activeSubField.components;
    } else if (activeIndex == mainField && containingField.hasComponents) {
      components = containingField.components;
    } else {
      return;
    }
    if (components.isEmpty) return;

    final bitStream = BitStream(
      List<Object?>.of(containingField.values),
      containingField.baseType,
    );

    for (final component in components) {
      if (bitStream.bitsAvailable < component.bits) break;

      final destination = fieldMap[component.fieldNum] ??
          Factory.createField(globalMesgNum, component.fieldNum) ??
          Factory.createDefaultField(
              component.fieldNum, containingField.baseType);

      final signed = destination.baseType.isSignedInteger;
      var raw = bitStream.readBits(component.bits, signed);

      if (component.accumulate) {
        // An all-ones component is the wire's invalid sentinel: it carries no
        // sample, so it must not feed the running total — fed in, the next real
        // sample's delta would be computed against the sentinel rather than the
        // last real sample. fit-python-sdk folds it in before testing
        // invalidity; that corruption is deliberately not reproduced here.
        final mask = component.bits >= 64 ? -1 : (1 << component.bits) - 1;
        if ((raw & mask) == mask) {
          final key = component.fieldNum;
          if (expandedSoFar.add(key)) destination.clearValues();
          destination.isExpandedField = true;
          destination.addRawValue(null);
          fieldMap[key] = destination;
          continue;
        }
        raw = accumulator.accumulate(
            globalMesgNum, component.fieldNum, raw, component.bits);
      }

      // Undo the component's own scale and offset, then apply the destination
      // field's, so the stored value round-trips.
      final destScale = activeSubField?.scale ?? destination.scale;
      final destOffset = activeSubField?.offset ?? destination.offset;
      final scaled =
          ((raw.toDouble() / component.scale) - component.offset + destOffset) *
              destScale;

      final key = component.fieldNum;
      if (expandedSoFar.add(key)) destination.clearValues();

      destination.isExpandedField = true;
      // An all-ones component means the same thing here as on the wire.
      destination.addRawValue(
          scaled == destination.baseType.invalidAsNumber() ? null : scaled);
      fieldMap[key] = destination;

      if (destination.hasComponents) {
        _expandComponents(destination, accumulator, expandedSoFar);
      }
    }
  }

  // ------------------------------------------------------------------- write

  /// Writes one data record laid out by [definition].
  ///
  /// Every field the definition lists must be present here. A definition record
  /// is a promise about the exact byte layout of the records that follow it, so
  /// skipping a field the definition declared would not lose that field — it
  /// would shift every byte after it, turning the rest of the record, and every
  /// record read under the same local message number, into garbage no decoder
  /// can detect. Refusing to write is the only safe answer.
  void write(ByteWriter writer, MesgDefinition definition) {
    writer.writeByte(definition.localMesgNum & Fit.hdrTypeMask);
    for (final fieldDefinition in definition.fieldDefinitions) {
      final field = getField(fieldDefinition.num);
      if (field == null) {
        throw FitFieldException(
          '$mesgName has no field ${fieldDefinition.num}, which the message '
          'definition for local message ${definition.localMesgNum} declares as '
          '${fieldDefinition.size} byte(s)',
        );
      }
      field.write(writer, definition.endianness);
    }
    for (final devDefinition in definition.developerFieldDefinitions) {
      DeveloperField? devField;
      for (final candidate in developerFieldMap.values) {
        if (candidate.fieldNum == devDefinition.num &&
            candidate.developerDataIndex == devDefinition.developerDataIndex) {
          devField = candidate;
          break;
        }
      }
      if (devField == null) {
        throw FitFieldException(
          '$mesgName has no developer field '
          '${devDefinition.developerDataIndex}/${devDefinition.num}, which the '
          'message definition for local message ${definition.localMesgNum} '
          'declares as ${devDefinition.size} byte(s)',
        );
      }
      devField.write(writer, definition.endianness);
    }
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! Mesg) return false;
    return globalMesgNum == other.globalMesgNum &&
        mesgName == other.mesgName &&
        _sameFields(fieldMap, other.fieldMap) &&
        _sameFields(developerFieldMap, other.developerFieldMap);
  }

  @override
  int get hashCode => Object.hash(
        globalMesgNum,
        mesgName,
        Object.hashAll(fieldMap.keys),
        Object.hashAll(fieldMap.values),
      );

  @override
  String toString() => '$mesgName(#$globalMesgNum) ${fieldMap.values.toList()}';

  static bool _sameFields<K, V>(Map<K, V> a, Map<K, V> b) {
    if (a.length != b.length) return false;
    for (final entry in a.entries) {
      if (!b.containsKey(entry.key) || b[entry.key] != entry.value) {
        return false;
      }
    }
    return true;
  }
}
