/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

// Every generated message class.

export 'messages/file_id_mesg.dart';
export 'messages/file_creator_mesg.dart';
export 'messages/timestamp_correlation_mesg.dart';
export 'messages/software_mesg.dart';
export 'messages/slave_device_mesg.dart';
export 'messages/capabilities_mesg.dart';
export 'messages/file_capabilities_mesg.dart';
export 'messages/mesg_capabilities_mesg.dart';
export 'messages/field_capabilities_mesg.dart';
export 'messages/device_settings_mesg.dart';
export 'messages/user_profile_mesg.dart';
export 'messages/hrm_profile_mesg.dart';
export 'messages/sdm_profile_mesg.dart';
export 'messages/bike_profile_mesg.dart';
export 'messages/connectivity_mesg.dart';
export 'messages/watchface_settings_mesg.dart';
export 'messages/ohr_settings_mesg.dart';
export 'messages/time_in_zone_mesg.dart';
export 'messages/zones_target_mesg.dart';
export 'messages/sport_mesg.dart';
export 'messages/hr_zone_mesg.dart';
export 'messages/speed_zone_mesg.dart';
export 'messages/cadence_zone_mesg.dart';
export 'messages/power_zone_mesg.dart';
export 'messages/met_zone_mesg.dart';
export 'messages/training_settings_mesg.dart';
export 'messages/dive_settings_mesg.dart';
export 'messages/dive_alarm_mesg.dart';
export 'messages/dive_apnea_alarm_mesg.dart';
export 'messages/dive_gas_mesg.dart';
export 'messages/goal_mesg.dart';
export 'messages/activity_mesg.dart';
export 'messages/session_mesg.dart';
export 'messages/lap_mesg.dart';
export 'messages/length_mesg.dart';
export 'messages/record_mesg.dart';
export 'messages/event_mesg.dart';
export 'messages/device_info_mesg.dart';
export 'messages/device_aux_battery_info_mesg.dart';
export 'messages/training_file_mesg.dart';
export 'messages/battery_mesg.dart';
export 'messages/weather_conditions_mesg.dart';
export 'messages/weather_alert_mesg.dart';
export 'messages/gps_metadata_mesg.dart';
export 'messages/camera_event_mesg.dart';
export 'messages/gyroscope_data_mesg.dart';
export 'messages/accelerometer_data_mesg.dart';
export 'messages/magnetometer_data_mesg.dart';
export 'messages/barometer_data_mesg.dart';
export 'messages/three_d_sensor_calibration_mesg.dart';
export 'messages/one_d_sensor_calibration_mesg.dart';
export 'messages/video_frame_mesg.dart';
export 'messages/obdii_data_mesg.dart';
export 'messages/nmea_sentence_mesg.dart';
export 'messages/aviation_attitude_mesg.dart';
export 'messages/video_mesg.dart';
export 'messages/video_title_mesg.dart';
export 'messages/video_description_mesg.dart';
export 'messages/video_clip_mesg.dart';
export 'messages/set_mesg.dart';
export 'messages/jump_mesg.dart';
export 'messages/split_mesg.dart';
export 'messages/split_summary_mesg.dart';
export 'messages/climb_pro_mesg.dart';
export 'messages/field_description_mesg.dart';
export 'messages/developer_data_id_mesg.dart';
export 'messages/course_mesg.dart';
export 'messages/course_point_mesg.dart';
export 'messages/segment_id_mesg.dart';
export 'messages/segment_leaderboard_entry_mesg.dart';
export 'messages/segment_point_mesg.dart';
export 'messages/segment_lap_mesg.dart';
export 'messages/segment_file_mesg.dart';
export 'messages/workout_mesg.dart';
export 'messages/workout_session_mesg.dart';
export 'messages/workout_step_mesg.dart';
export 'messages/exercise_title_mesg.dart';
export 'messages/schedule_mesg.dart';
export 'messages/totals_mesg.dart';
export 'messages/weight_scale_mesg.dart';
export 'messages/blood_pressure_mesg.dart';
export 'messages/monitoring_info_mesg.dart';
export 'messages/monitoring_mesg.dart';
export 'messages/monitoring_hr_data_mesg.dart';
export 'messages/spo2_data_mesg.dart';
export 'messages/hr_mesg.dart';
export 'messages/stress_level_mesg.dart';
export 'messages/max_met_data_mesg.dart';
export 'messages/hsa_body_battery_data_mesg.dart';
export 'messages/hsa_event_mesg.dart';
export 'messages/hsa_accelerometer_data_mesg.dart';
export 'messages/hsa_gyroscope_data_mesg.dart';
export 'messages/hsa_step_data_mesg.dart';
export 'messages/hsa_spo2_data_mesg.dart';
export 'messages/hsa_stress_data_mesg.dart';
export 'messages/hsa_respiration_data_mesg.dart';
export 'messages/hsa_heart_rate_data_mesg.dart';
export 'messages/hsa_configuration_data_mesg.dart';
export 'messages/hsa_wrist_temperature_data_mesg.dart';
export 'messages/memo_glob_mesg.dart';
export 'messages/sleep_level_mesg.dart';
export 'messages/ant_channel_id_mesg.dart';
export 'messages/ant_rx_mesg.dart';
export 'messages/ant_tx_mesg.dart';
export 'messages/exd_screen_configuration_mesg.dart';
export 'messages/exd_data_field_configuration_mesg.dart';
export 'messages/exd_data_concept_configuration_mesg.dart';
export 'messages/dive_summary_mesg.dart';
export 'messages/aad_accel_features_mesg.dart';
export 'messages/hrv_mesg.dart';
export 'messages/beat_intervals_mesg.dart';
export 'messages/hrv_status_summary_mesg.dart';
export 'messages/hrv_value_mesg.dart';
export 'messages/raw_bbi_mesg.dart';
export 'messages/respiration_rate_mesg.dart';
export 'messages/chrono_shot_session_mesg.dart';
export 'messages/chrono_shot_data_mesg.dart';
export 'messages/tank_update_mesg.dart';
export 'messages/tank_summary_mesg.dart';
export 'messages/sleep_assessment_mesg.dart';
export 'messages/sleep_disruption_severity_period_mesg.dart';
export 'messages/sleep_disruption_overnight_severity_mesg.dart';
export 'messages/nap_event_mesg.dart';
export 'messages/skin_temp_overnight_mesg.dart';
export 'messages/pad_mesg.dart';
