/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

import 'fit.dart';

/// The generated FIT profile: the version this SDK was generated from.
abstract final class Profile {
  static const int versionMajor = 21;
  static const int versionMinor = 217;
  static const int versionBuild = 0;

  /// Profile version as encoded in the FIT file header.
  ///
  /// The minor version is scaled by [Fit.profileVersionScale], not by 100: the
  /// profile's minor number runs past 100 (21.205 here), so a factor of 100
  /// would fold it into the major version and make 21.205 indistinguishable from
  /// 23.5. Always equal to [Fit.profileVersion].
  static const int version =
      versionMajor * Fit.profileVersionScale + versionMinor;
}

/// Global message numbers, as used by `Mesg.globalMesgNum`.
abstract final class MesgNum {
  static const int fileId = 0; // Must be first message in file.
  static const int fileCreator = 49;
  static const int timestampCorrelation = 162;
  static const int software = 35;
  static const int slaveDevice = 106;
  static const int capabilities = 1;
  static const int fileCapabilities = 37;
  static const int mesgCapabilities = 38;
  static const int fieldCapabilities = 39;
  static const int deviceSettings = 2;
  static const int userProfile = 3;
  static const int hrmProfile = 4;
  static const int sdmProfile = 5;
  static const int bikeProfile = 6;
  static const int connectivity = 127;
  static const int watchfaceSettings = 159;
  static const int ohrSettings = 188;
  static const int timeInZone = 216;
  static const int zonesTarget = 7;
  static const int sport = 12;
  static const int hrZone = 8;
  static const int speedZone = 53;
  static const int cadenceZone = 131;
  static const int powerZone = 9;
  static const int metZone = 10;
  static const int trainingSettings = 13;
  static const int diveSettings = 258;
  static const int diveAlarm = 262;
  static const int diveApneaAlarm = 393;
  static const int diveGas = 259;
  static const int goal = 15;
  static const int activity = 34;
  static const int session = 18;
  static const int lap = 19;
  static const int length = 101;
  static const int record = 20;
  static const int event = 21;
  static const int deviceInfo = 23;
  static const int deviceAuxBatteryInfo = 375;
  static const int trainingFile =
      72; // Corresponds to file_id of workout or course.
  static const int battery = 104;
  static const int weatherConditions = 128;
  static const int weatherAlert = 129;
  static const int gpsMetadata = 160;
  static const int cameraEvent = 161;
  static const int gyroscopeData = 164;
  static const int accelerometerData = 165;
  static const int magnetometerData = 208;
  static const int barometerData = 209;
  static const int threeDSensorCalibration = 167;
  static const int oneDSensorCalibration = 210;
  static const int videoFrame = 169;
  static const int obdiiData = 174;
  static const int nmeaSentence = 177;
  static const int aviationAttitude = 178;
  static const int video = 184;
  static const int videoTitle = 185;
  static const int videoDescription = 186;
  static const int videoClip = 187;
  static const int set = 225;
  static const int jump = 285;
  static const int split = 312;
  static const int splitSummary = 313;
  static const int climbPro = 317;
  static const int fieldDescription =
      206; // Must be logged before developer field is used
  static const int developerDataId =
      207; // Must be logged before field description
  static const int course = 31;
  static const int coursePoint = 32;
  static const int segmentId =
      148; // Unique Identification data for a segment file
  static const int segmentLeaderboardEntry =
      149; // Unique Identification data for an individual segment leader within a segment file
  static const int segmentPoint =
      150; // Navigation and race evaluation point for a segment decribing a point along the segment path and time it took each segment leader to reach that point
  static const int segmentLap = 142;
  static const int segmentFile =
      151; // Summary of the unique segment and leaderboard information associated with a segment file. This message is used to compile a segment list file describing all segment files on a device. The segment list file is used when refreshing the contents of a segment file with the latest available leaderboard information.
  static const int workout = 26;
  static const int workoutSession = 158;
  static const int workoutStep = 27;
  static const int exerciseTitle = 264;
  static const int schedule = 28;
  static const int totals = 33;
  static const int weightScale = 30;
  static const int bloodPressure = 51;
  static const int monitoringInfo = 103;
  static const int monitoring = 55;
  static const int monitoringHrData = 211;
  static const int spo2Data = 269;
  static const int hr = 132;
  static const int stressLevel =
      227; // Value from 1 to 100 calculated by FirstBeat
  static const int maxMetData = 229;
  static const int hsaBodyBatteryData =
      314; // Body battery data used for HSA custom data logging
  static const int hsaEvent = 315; // HSA events
  static const int hsaAccelerometerData =
      302; // Raw accelerometer data used for HSA custom data logging
  static const int hsaGyroscopeData = 376;
  static const int hsaStepData =
      304; // User's current daily step data used for HSA custom data logging
  static const int hsaSpo2Data =
      305; // User's current SpO2 data used for HSA custom data logging
  static const int hsaStressData =
      306; // User's current stress data used for HSA custom data logging
  static const int hsaRespirationData =
      307; // User's current respiration data used for HSA custom data logging
  static const int hsaHeartRateData =
      308; // User's current heart rate data used for HSA custom data logging
  static const int hsaConfigurationData =
      389; // Configuration data for HSA custom data logging
  static const int hsaWristTemperatureData =
      409; // Wrist temperature data used for HSA custom data logging
  static const int memoGlob = 145;
  static const int sleepLevel = 275;
  static const int antChannelId = 82;
  static const int antRx = 80;
  static const int antTx = 81;
  static const int exdScreenConfiguration = 200;
  static const int exdDataFieldConfiguration = 201;
  static const int exdDataConceptConfiguration = 202;
  static const int diveSummary = 268;
  static const int aadAccelFeatures =
      289; // Number of acclerometer zero crossings summed over the specified time interval
  static const int hrv = 78; // Heart rate variability
  static const int beatIntervals = 290; // Array of heart beat intervals
  static const int hrvStatusSummary = 370;
  static const int hrvValue = 371;
  static const int rawBbi = 372; // Raw Beat-to-Beat Interval values
  static const int respirationRate = 297;
  static const int chronoShotSession =
      387; // Specifically used for XERO products.
  static const int chronoShotData = 388; // Specifically used for XERO products.
  static const int tankUpdate = 319;
  static const int tankSummary = 323;
  static const int sleepAssessment = 346;
  static const int sleepDisruptionSeverityPeriod = 470;
  static const int sleepDisruptionOvernightSeverity = 471;
  static const int napEvent = 412;
  static const int skinTempOvernight = 398;
  static const int pad = 105;

  /// Sentinel for a message number absent from the profile.
  static const int invalid = 0xFFFF;
}
