/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// An unofficial Dart/Flutter SDK for Garmin's FIT protocol.
///
/// Decoding:
///
/// ```dart
/// final result = FitDecoder(bytes).decode();
/// for (final record in result.messages.recordMesgs) {
///   print('${record.timestamp}: ${record.heartRate} bpm');
/// }
/// ```
///
/// Encoding:
///
/// ```dart
/// final bytes = encodeFit((encoder) {
///   encoder.write(FileIdMesg()
///     ..type = File.activity
///     ..manufacturer = Manufacturer.development
///     ..timeCreated = DateTime.timestamp());
/// });
/// ```
library;

export 'src/accumulator.dart';
export 'src/base_type.dart';
export 'src/bit_stream.dart';
export 'src/byte_reader.dart';
export 'src/byte_writer.dart';
export 'src/crc.dart';
export 'src/decode_options.dart';
export 'src/developer_data_lookup.dart';
export 'src/developer_field.dart';
export 'src/developer_field_description.dart';
export 'src/factory.dart';
export 'src/field.dart';
export 'src/field_base.dart';
export 'src/field_component.dart';
export 'src/field_definition.dart';
export 'src/file_header.dart';
export 'src/fit.dart';
export 'src/fit_date_time.dart';
export 'src/fit_decoder.dart';
export 'src/fit_encoder.dart';
export 'src/fit_exception.dart';
export 'src/fit_messages.dart';
export 'src/hr_mesg_util.dart';
export 'src/mesg.dart';
export 'src/mesg_cursor.dart';
export 'src/mesg_definition.dart';
export 'src/messages.dart';
export 'src/profile.dart';
export 'src/sub_field.dart';
export 'src/types.dart';
