/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `bike_profile` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class BikeProfileMesg extends Mesg {
  BikeProfileMesg() : super('bike_profile', MesgNum.bikeProfile);

  /// A deep copy of [mesg] reinterpreted as a `bike_profile`.
  BikeProfileMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  BikeProfileMesg.adopt(super.mesg) : super.adopt();

  static const int messageIndexFieldNum = 254;

  /// message_index.
  int? get messageIndex => intFieldValue(messageIndexFieldNum);

  set messageIndex(int? value) => setFieldValue(messageIndexFieldNum, value);

  static const int name_FieldNum = 0;

  /// name.
  String? get name_ => stringFieldValue(name_FieldNum);

  set name_(String? value) => setFieldValue(name_FieldNum, value);

  static const int sportFieldNum = 1;

  /// sport.
  Sport? get sport {
    final value = intFieldValue(sportFieldNum);
    return value == null ? null : Sport.fromValue(value);
  }

  set sport(Sport? value) => setFieldValue(sportFieldNum, value?.value);

  static const int subSportFieldNum = 2;

  /// sub_sport.
  SubSport? get subSport {
    final value = intFieldValue(subSportFieldNum);
    return value == null ? null : SubSport.fromValue(value);
  }

  set subSport(SubSport? value) =>
      setFieldValue(subSportFieldNum, value?.value);

  static const int odometerFieldNum = 3;

  /// odometer, in m.
  double? get odometer => doubleFieldValue(odometerFieldNum);

  set odometer(double? value) => setFieldValue(odometerFieldNum, value);

  static const int bikeSpdAntIdFieldNum = 4;

  /// bike_spd_ant_id.
  int? get bikeSpdAntId => intFieldValue(bikeSpdAntIdFieldNum);

  set bikeSpdAntId(int? value) => setFieldValue(bikeSpdAntIdFieldNum, value);

  static const int bikeCadAntIdFieldNum = 5;

  /// bike_cad_ant_id.
  int? get bikeCadAntId => intFieldValue(bikeCadAntIdFieldNum);

  set bikeCadAntId(int? value) => setFieldValue(bikeCadAntIdFieldNum, value);

  static const int bikeSpdcadAntIdFieldNum = 6;

  /// bike_spdcad_ant_id.
  int? get bikeSpdcadAntId => intFieldValue(bikeSpdcadAntIdFieldNum);

  set bikeSpdcadAntId(int? value) =>
      setFieldValue(bikeSpdcadAntIdFieldNum, value);

  static const int bikePowerAntIdFieldNum = 7;

  /// bike_power_ant_id.
  int? get bikePowerAntId => intFieldValue(bikePowerAntIdFieldNum);

  set bikePowerAntId(int? value) =>
      setFieldValue(bikePowerAntIdFieldNum, value);

  static const int customWheelsizeFieldNum = 8;

  /// custom_wheelsize, in m.
  double? get customWheelsize => doubleFieldValue(customWheelsizeFieldNum);

  set customWheelsize(double? value) =>
      setFieldValue(customWheelsizeFieldNum, value);

  static const int autoWheelsizeFieldNum = 9;

  /// auto_wheelsize, in m.
  double? get autoWheelsize => doubleFieldValue(autoWheelsizeFieldNum);

  set autoWheelsize(double? value) =>
      setFieldValue(autoWheelsizeFieldNum, value);

  static const int bikeWeightFieldNum = 10;

  /// bike_weight, in kg.
  double? get bikeWeight => doubleFieldValue(bikeWeightFieldNum);

  set bikeWeight(double? value) => setFieldValue(bikeWeightFieldNum, value);

  static const int powerCalFactorFieldNum = 11;

  /// power_cal_factor, in %.
  double? get powerCalFactor => doubleFieldValue(powerCalFactorFieldNum);

  set powerCalFactor(double? value) =>
      setFieldValue(powerCalFactorFieldNum, value);

  static const int autoWheelCalFieldNum = 12;

  /// auto_wheel_cal.
  bool? get autoWheelCal {
    final value = intFieldValue(autoWheelCalFieldNum);
    return value == null ? null : value != 0;
  }

  set autoWheelCal(bool? value) => setFieldValue(
      autoWheelCalFieldNum, value == null ? null : (value ? 1 : 0));

  static const int autoPowerZeroFieldNum = 13;

  /// auto_power_zero.
  bool? get autoPowerZero {
    final value = intFieldValue(autoPowerZeroFieldNum);
    return value == null ? null : value != 0;
  }

  set autoPowerZero(bool? value) => setFieldValue(
      autoPowerZeroFieldNum, value == null ? null : (value ? 1 : 0));

  static const int idFieldNum = 14;

  /// id.
  int? get id => intFieldValue(idFieldNum);

  set id(int? value) => setFieldValue(idFieldNum, value);

  static const int spdEnabledFieldNum = 15;

  /// spd_enabled.
  bool? get spdEnabled {
    final value = intFieldValue(spdEnabledFieldNum);
    return value == null ? null : value != 0;
  }

  set spdEnabled(bool? value) =>
      setFieldValue(spdEnabledFieldNum, value == null ? null : (value ? 1 : 0));

  static const int cadEnabledFieldNum = 16;

  /// cad_enabled.
  bool? get cadEnabled {
    final value = intFieldValue(cadEnabledFieldNum);
    return value == null ? null : value != 0;
  }

  set cadEnabled(bool? value) =>
      setFieldValue(cadEnabledFieldNum, value == null ? null : (value ? 1 : 0));

  static const int spdcadEnabledFieldNum = 17;

  /// spdcad_enabled.
  bool? get spdcadEnabled {
    final value = intFieldValue(spdcadEnabledFieldNum);
    return value == null ? null : value != 0;
  }

  set spdcadEnabled(bool? value) => setFieldValue(
      spdcadEnabledFieldNum, value == null ? null : (value ? 1 : 0));

  static const int powerEnabledFieldNum = 18;

  /// power_enabled.
  bool? get powerEnabled {
    final value = intFieldValue(powerEnabledFieldNum);
    return value == null ? null : value != 0;
  }

  set powerEnabled(bool? value) => setFieldValue(
      powerEnabledFieldNum, value == null ? null : (value ? 1 : 0));

  static const int crankLengthFieldNum = 19;

  /// crank_length, in mm.
  double? get crankLength => doubleFieldValue(crankLengthFieldNum);

  set crankLength(double? value) => setFieldValue(crankLengthFieldNum, value);

  static const int enabledFieldNum = 20;

  /// enabled.
  bool? get enabled {
    final value = intFieldValue(enabledFieldNum);
    return value == null ? null : value != 0;
  }

  set enabled(bool? value) =>
      setFieldValue(enabledFieldNum, value == null ? null : (value ? 1 : 0));

  static const int bikeSpdAntIdTransTypeFieldNum = 21;

  /// bike_spd_ant_id_trans_type.
  int? get bikeSpdAntIdTransType =>
      intFieldValue(bikeSpdAntIdTransTypeFieldNum);

  set bikeSpdAntIdTransType(int? value) =>
      setFieldValue(bikeSpdAntIdTransTypeFieldNum, value);

  static const int bikeCadAntIdTransTypeFieldNum = 22;

  /// bike_cad_ant_id_trans_type.
  int? get bikeCadAntIdTransType =>
      intFieldValue(bikeCadAntIdTransTypeFieldNum);

  set bikeCadAntIdTransType(int? value) =>
      setFieldValue(bikeCadAntIdTransTypeFieldNum, value);

  static const int bikeSpdcadAntIdTransTypeFieldNum = 23;

  /// bike_spdcad_ant_id_trans_type.
  int? get bikeSpdcadAntIdTransType =>
      intFieldValue(bikeSpdcadAntIdTransTypeFieldNum);

  set bikeSpdcadAntIdTransType(int? value) =>
      setFieldValue(bikeSpdcadAntIdTransTypeFieldNum, value);

  static const int bikePowerAntIdTransTypeFieldNum = 24;

  /// bike_power_ant_id_trans_type.
  int? get bikePowerAntIdTransType =>
      intFieldValue(bikePowerAntIdTransTypeFieldNum);

  set bikePowerAntIdTransType(int? value) =>
      setFieldValue(bikePowerAntIdTransTypeFieldNum, value);

  static const int odometerRolloverFieldNum = 37;

  /// odometer_rollover. Rollover counter that can be used to extend the odometer
  int? get odometerRollover => intFieldValue(odometerRolloverFieldNum);

  set odometerRollover(int? value) =>
      setFieldValue(odometerRolloverFieldNum, value);

  static const int frontGearNumFieldNum = 38;

  /// front_gear_num. Number of front gears
  int? get frontGearNum => intFieldValue(frontGearNumFieldNum);

  set frontGearNum(int? value) => setFieldValue(frontGearNumFieldNum, value);

  static const int frontGearFieldNum = 39;

  /// Number of values stored in front_gear.
  int get numFrontGear => getField(frontGearFieldNum)?.numValues ?? 0;

  /// front_gear. Number of teeth on each gear 0 is innermost
  List<int?>? get frontGear {
    final field = getField(frontGearFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getFrontGear);
  }

  set frontGear(List<int?>? value) {
    removeField(frontGearFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setFrontGear(index, value[index]);
    }
  }

  int? getFrontGear(int index) => intFieldValue(frontGearFieldNum, index);

  void setFrontGear(int index, int? value) =>
      setFieldValue(frontGearFieldNum, value, index);

  static const int rearGearNumFieldNum = 40;

  /// rear_gear_num. Number of rear gears
  int? get rearGearNum => intFieldValue(rearGearNumFieldNum);

  set rearGearNum(int? value) => setFieldValue(rearGearNumFieldNum, value);

  static const int rearGearFieldNum = 41;

  /// Number of values stored in rear_gear.
  int get numRearGear => getField(rearGearFieldNum)?.numValues ?? 0;

  /// rear_gear. Number of teeth on each gear 0 is innermost
  List<int?>? get rearGear {
    final field = getField(rearGearFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getRearGear);
  }

  set rearGear(List<int?>? value) {
    removeField(rearGearFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setRearGear(index, value[index]);
    }
  }

  int? getRearGear(int index) => intFieldValue(rearGearFieldNum, index);

  void setRearGear(int index, int? value) =>
      setFieldValue(rearGearFieldNum, value, index);

  static const int shimanoDi2EnabledFieldNum = 44;

  /// shimano_di2_enabled.
  bool? get shimanoDi2Enabled {
    final value = intFieldValue(shimanoDi2EnabledFieldNum);
    return value == null ? null : value != 0;
  }

  set shimanoDi2Enabled(bool? value) => setFieldValue(
      shimanoDi2EnabledFieldNum, value == null ? null : (value ? 1 : 0));

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[254] =
        Field('message_index', 254, BaseType.uint16, 1.0, 0.0, '', false);
    fields[0] = Field('name', 0, BaseType.string, 1.0, 0.0, '', false);
    fields[1] = Field('sport', 1, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[2] = Field('sub_sport', 2, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[3] = Field('odometer', 3, BaseType.uint32, 100.0, 0.0, 'm', false);
    fields[4] =
        Field('bike_spd_ant_id', 4, BaseType.uint16z, 1.0, 0.0, '', false);
    fields[5] =
        Field('bike_cad_ant_id', 5, BaseType.uint16z, 1.0, 0.0, '', false);
    fields[6] =
        Field('bike_spdcad_ant_id', 6, BaseType.uint16z, 1.0, 0.0, '', false);
    fields[7] =
        Field('bike_power_ant_id', 7, BaseType.uint16z, 1.0, 0.0, '', false);
    fields[8] =
        Field('custom_wheelsize', 8, BaseType.uint16, 1000.0, 0.0, 'm', false);
    fields[9] =
        Field('auto_wheelsize', 9, BaseType.uint16, 1000.0, 0.0, 'm', false);
    fields[10] =
        Field('bike_weight', 10, BaseType.uint16, 10.0, 0.0, 'kg', false);
    fields[11] =
        Field('power_cal_factor', 11, BaseType.uint16, 10.0, 0.0, '%', false);
    fields[12] =
        Field('auto_wheel_cal', 12, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[13] =
        Field('auto_power_zero', 13, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[14] = Field('id', 14, BaseType.uint8, 1.0, 0.0, '', false);
    fields[15] =
        Field('spd_enabled', 15, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[16] =
        Field('cad_enabled', 16, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[17] =
        Field('spdcad_enabled', 17, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[18] =
        Field('power_enabled', 18, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[19] =
        Field('crank_length', 19, BaseType.uint8, 2.0, -110.0, 'mm', false);
    fields[20] = Field('enabled', 20, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[21] = Field(
        'bike_spd_ant_id_trans_type', 21, BaseType.uint8z, 1.0, 0.0, '', false);
    fields[22] = Field(
        'bike_cad_ant_id_trans_type', 22, BaseType.uint8z, 1.0, 0.0, '', false);
    fields[23] = Field('bike_spdcad_ant_id_trans_type', 23, BaseType.uint8z,
        1.0, 0.0, '', false);
    fields[24] = Field('bike_power_ant_id_trans_type', 24, BaseType.uint8z, 1.0,
        0.0, '', false);
    fields[37] =
        Field('odometer_rollover', 37, BaseType.uint8, 1.0, 0.0, '', false);
    fields[38] =
        Field('front_gear_num', 38, BaseType.uint8z, 1.0, 0.0, '', false);
    fields[39] = Field('front_gear', 39, BaseType.uint8z, 1.0, 0.0, '', false);
    fields[40] =
        Field('rear_gear_num', 40, BaseType.uint8z, 1.0, 0.0, '', false);
    fields[41] = Field('rear_gear', 41, BaseType.uint8z, 1.0, 0.0, '', false);
    fields[44] =
        Field('shimano_di2_enabled', 44, BaseType.fitEnum, 1.0, 0.0, '', false);
    return fields;
  }
}
