/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `capabilities` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class CapabilitiesMesg extends Mesg {
  CapabilitiesMesg() : super('capabilities', MesgNum.capabilities);

  /// A deep copy of [mesg] reinterpreted as a `capabilities`.
  CapabilitiesMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  CapabilitiesMesg.adopt(super.mesg) : super.adopt();

  static const int languagesFieldNum = 0;

  /// Number of values stored in languages.
  int get numLanguages => getField(languagesFieldNum)?.numValues ?? 0;

  /// languages. Use language_bits_x types where x is index of array.
  List<int?>? get languages {
    final field = getField(languagesFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getLanguages);
  }

  set languages(List<int?>? value) {
    removeField(languagesFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setLanguages(index, value[index]);
    }
  }

  int? getLanguages(int index) => intFieldValue(languagesFieldNum, index);

  void setLanguages(int index, int? value) =>
      setFieldValue(languagesFieldNum, value, index);

  static const int sportsFieldNum = 1;

  /// Number of values stored in sports.
  int get numSports => getField(sportsFieldNum)?.numValues ?? 0;

  /// sports. Use sport_bits_x types where x is index of array.
  List<SportBits0?>? get sports {
    final field = getField(sportsFieldNum);
    if (field == null) return null;
    return List<SportBits0?>.generate(field.numValues, getSports);
  }

  set sports(List<SportBits0?>? value) {
    removeField(sportsFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setSports(index, value[index]);
    }
  }

  SportBits0? getSports(int index) {
    final value = intFieldValue(sportsFieldNum, index);
    return value == null ? null : SportBits0.fromValue(value);
  }

  void setSports(int index, SportBits0? value) =>
      setFieldValue(sportsFieldNum, value?.value, index);

  static const int workoutsSupportedFieldNum = 21;

  /// workouts_supported.
  WorkoutCapabilities? get workoutsSupported {
    final value = intFieldValue(workoutsSupportedFieldNum);
    return value == null ? null : WorkoutCapabilities.fromValue(value);
  }

  set workoutsSupported(WorkoutCapabilities? value) =>
      setFieldValue(workoutsSupportedFieldNum, value?.value);

  static const int connectivitySupportedFieldNum = 23;

  /// connectivity_supported.
  ConnectivityCapabilities? get connectivitySupported {
    final value = intFieldValue(connectivitySupportedFieldNum);
    return value == null ? null : ConnectivityCapabilities.fromValue(value);
  }

  set connectivitySupported(ConnectivityCapabilities? value) =>
      setFieldValue(connectivitySupportedFieldNum, value?.value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[0] = Field('languages', 0, BaseType.uint8z, 1.0, 0.0, '', false);
    fields[1] = Field('sports', 1, BaseType.uint8z, 1.0, 0.0, '', false);
    fields[21] =
        Field('workouts_supported', 21, BaseType.uint32z, 1.0, 0.0, '', false);
    fields[23] = Field(
        'connectivity_supported', 23, BaseType.uint32z, 1.0, 0.0, '', false);
    return fields;
  }
}
