/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `chrono_shot_session` message.
///
/// Specifically used for XERO products.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class ChronoShotSessionMesg extends Mesg {
  ChronoShotSessionMesg()
      : super('chrono_shot_session', MesgNum.chronoShotSession);

  /// A deep copy of [mesg] reinterpreted as a `chrono_shot_session`.
  ChronoShotSessionMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  ChronoShotSessionMesg.adopt(super.mesg) : super.adopt();

  static const int timestampFieldNum = 253;

  /// timestamp.
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int minSpeedFieldNum = 0;

  /// min_speed, in m/s.
  double? get minSpeed => doubleFieldValue(minSpeedFieldNum);

  set minSpeed(double? value) => setFieldValue(minSpeedFieldNum, value);

  static const int maxSpeedFieldNum = 1;

  /// max_speed, in m/s.
  double? get maxSpeed => doubleFieldValue(maxSpeedFieldNum);

  set maxSpeed(double? value) => setFieldValue(maxSpeedFieldNum, value);

  static const int avgSpeedFieldNum = 2;

  /// avg_speed, in m/s.
  double? get avgSpeed => doubleFieldValue(avgSpeedFieldNum);

  set avgSpeed(double? value) => setFieldValue(avgSpeedFieldNum, value);

  static const int shotCountFieldNum = 3;

  /// shot_count.
  int? get shotCount => intFieldValue(shotCountFieldNum);

  set shotCount(int? value) => setFieldValue(shotCountFieldNum, value);

  static const int projectileTypeFieldNum = 4;

  /// projectile_type.
  ProjectileType? get projectileType {
    final value = intFieldValue(projectileTypeFieldNum);
    return value == null ? null : ProjectileType.fromValue(value);
  }

  set projectileType(ProjectileType? value) =>
      setFieldValue(projectileTypeFieldNum, value?.value);

  static const int grainWeightFieldNum = 5;

  /// grain_weight, in gr.
  double? get grainWeight => doubleFieldValue(grainWeightFieldNum);

  set grainWeight(double? value) => setFieldValue(grainWeightFieldNum, value);

  static const int standardDeviationFieldNum = 6;

  /// standard_deviation, in m/s.
  double? get standardDeviation => doubleFieldValue(standardDeviationFieldNum);

  set standardDeviation(double? value) =>
      setFieldValue(standardDeviationFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[253] = Field('timestamp', 253, BaseType.uint32, 1.0, 0.0, '', false);
    fields[0] =
        Field('min_speed', 0, BaseType.uint32, 1000.0, 0.0, 'm/s', false);
    fields[1] =
        Field('max_speed', 1, BaseType.uint32, 1000.0, 0.0, 'm/s', false);
    fields[2] =
        Field('avg_speed', 2, BaseType.uint32, 1000.0, 0.0, 'm/s', false);
    fields[3] = Field('shot_count', 3, BaseType.uint16, 1.0, 0.0, '', false);
    fields[4] =
        Field('projectile_type', 4, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[5] =
        Field('grain_weight', 5, BaseType.uint32, 10.0, 0.0, 'gr', false);
    fields[6] = Field(
        'standard_deviation', 6, BaseType.uint32, 1000.0, 0.0, 'm/s', false);
    return fields;
  }
}
