/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `course_point` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class CoursePointMesg extends Mesg {
  CoursePointMesg() : super('course_point', MesgNum.coursePoint);

  /// A deep copy of [mesg] reinterpreted as a `course_point`.
  CoursePointMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  CoursePointMesg.adopt(super.mesg) : super.adopt();

  static const int messageIndexFieldNum = 254;

  /// message_index.
  int? get messageIndex => intFieldValue(messageIndexFieldNum);

  set messageIndex(int? value) => setFieldValue(messageIndexFieldNum, value);

  static const int timestampFieldNum = 1;

  /// timestamp.
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int positionLatFieldNum = 2;

  /// position_lat, in semicircles.
  int? get positionLat => intFieldValue(positionLatFieldNum);

  set positionLat(int? value) => setFieldValue(positionLatFieldNum, value);

  static const int positionLongFieldNum = 3;

  /// position_long, in semicircles.
  int? get positionLong => intFieldValue(positionLongFieldNum);

  set positionLong(int? value) => setFieldValue(positionLongFieldNum, value);

  static const int distanceFieldNum = 4;

  /// distance, in m.
  double? get distance => doubleFieldValue(distanceFieldNum);

  set distance(double? value) => setFieldValue(distanceFieldNum, value);

  static const int typeFieldNum = 5;

  /// type.
  CoursePoint? get type {
    final value = intFieldValue(typeFieldNum);
    return value == null ? null : CoursePoint.fromValue(value);
  }

  set type(CoursePoint? value) => setFieldValue(typeFieldNum, value?.value);

  static const int name_FieldNum = 6;

  /// name.
  String? get name_ => stringFieldValue(name_FieldNum);

  set name_(String? value) => setFieldValue(name_FieldNum, value);

  static const int favoriteFieldNum = 8;

  /// favorite.
  bool? get favorite {
    final value = intFieldValue(favoriteFieldNum);
    return value == null ? null : value != 0;
  }

  set favorite(bool? value) =>
      setFieldValue(favoriteFieldNum, value == null ? null : (value ? 1 : 0));

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[254] =
        Field('message_index', 254, BaseType.uint16, 1.0, 0.0, '', false);
    fields[1] = Field('timestamp', 1, BaseType.uint32, 1.0, 0.0, '', false);
    fields[2] = Field(
        'position_lat', 2, BaseType.sint32, 1.0, 0.0, 'semicircles', false);
    fields[3] = Field(
        'position_long', 3, BaseType.sint32, 1.0, 0.0, 'semicircles', false);
    fields[4] = Field('distance', 4, BaseType.uint32, 100.0, 0.0, 'm', false);
    fields[5] = Field('type', 5, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[6] = Field('name', 6, BaseType.string, 1.0, 0.0, '', false);
    fields[8] = Field('favorite', 8, BaseType.fitEnum, 1.0, 0.0, '', false);
    return fields;
  }
}
