/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `dive_summary` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class DiveSummaryMesg extends Mesg {
  DiveSummaryMesg() : super('dive_summary', MesgNum.diveSummary);

  /// A deep copy of [mesg] reinterpreted as a `dive_summary`.
  DiveSummaryMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  DiveSummaryMesg.adopt(super.mesg) : super.adopt();

  static const int timestampFieldNum = 253;

  /// timestamp, in s.
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int referenceMesgFieldNum = 0;

  /// reference_mesg.
  FitMesgNum? get referenceMesg {
    final value = intFieldValue(referenceMesgFieldNum);
    return value == null ? null : FitMesgNum.fromValue(value);
  }

  set referenceMesg(FitMesgNum? value) =>
      setFieldValue(referenceMesgFieldNum, value?.value);

  static const int referenceIndexFieldNum = 1;

  /// reference_index.
  int? get referenceIndex => intFieldValue(referenceIndexFieldNum);

  set referenceIndex(int? value) =>
      setFieldValue(referenceIndexFieldNum, value);

  static const int avgDepthFieldNum = 2;

  /// avg_depth, in m. 0 if above water
  double? get avgDepth => doubleFieldValue(avgDepthFieldNum);

  set avgDepth(double? value) => setFieldValue(avgDepthFieldNum, value);

  static const int maxDepthFieldNum = 3;

  /// max_depth, in m. 0 if above water
  double? get maxDepth => doubleFieldValue(maxDepthFieldNum);

  set maxDepth(double? value) => setFieldValue(maxDepthFieldNum, value);

  static const int surfaceIntervalFieldNum = 4;

  /// surface_interval, in s. Time since end of last dive
  int? get surfaceInterval => intFieldValue(surfaceIntervalFieldNum);

  set surfaceInterval(int? value) =>
      setFieldValue(surfaceIntervalFieldNum, value);

  static const int startCnsFieldNum = 5;

  /// start_cns, in percent.
  int? get startCns => intFieldValue(startCnsFieldNum);

  set startCns(int? value) => setFieldValue(startCnsFieldNum, value);

  static const int endCnsFieldNum = 6;

  /// end_cns, in percent.
  int? get endCns => intFieldValue(endCnsFieldNum);

  set endCns(int? value) => setFieldValue(endCnsFieldNum, value);

  static const int startN2FieldNum = 7;

  /// start_n2, in percent.
  int? get startN2 => intFieldValue(startN2FieldNum);

  set startN2(int? value) => setFieldValue(startN2FieldNum, value);

  static const int endN2FieldNum = 8;

  /// end_n2, in percent.
  int? get endN2 => intFieldValue(endN2FieldNum);

  set endN2(int? value) => setFieldValue(endN2FieldNum, value);

  static const int o2ToxicityFieldNum = 9;

  /// o2_toxicity, in OTUs.
  int? get o2Toxicity => intFieldValue(o2ToxicityFieldNum);

  set o2Toxicity(int? value) => setFieldValue(o2ToxicityFieldNum, value);

  static const int diveNumberFieldNum = 10;

  /// dive_number.
  int? get diveNumber => intFieldValue(diveNumberFieldNum);

  set diveNumber(int? value) => setFieldValue(diveNumberFieldNum, value);

  static const int bottomTimeFieldNum = 11;

  /// bottom_time, in s.
  double? get bottomTime => doubleFieldValue(bottomTimeFieldNum);

  set bottomTime(double? value) => setFieldValue(bottomTimeFieldNum, value);

  static const int avgPressureSacFieldNum = 12;

  /// avg_pressure_sac, in bar/min. Average pressure-based surface air consumption
  double? get avgPressureSac => doubleFieldValue(avgPressureSacFieldNum);

  set avgPressureSac(double? value) =>
      setFieldValue(avgPressureSacFieldNum, value);

  static const int avgVolumeSacFieldNum = 13;

  /// avg_volume_sac, in L/min. Average volumetric surface air consumption
  double? get avgVolumeSac => doubleFieldValue(avgVolumeSacFieldNum);

  set avgVolumeSac(double? value) => setFieldValue(avgVolumeSacFieldNum, value);

  static const int avgRmvFieldNum = 14;

  /// avg_rmv, in L/min. Average respiratory minute volume
  double? get avgRmv => doubleFieldValue(avgRmvFieldNum);

  set avgRmv(double? value) => setFieldValue(avgRmvFieldNum, value);

  static const int descentTimeFieldNum = 15;

  /// descent_time, in s. Time to reach deepest level stop
  double? get descentTime => doubleFieldValue(descentTimeFieldNum);

  set descentTime(double? value) => setFieldValue(descentTimeFieldNum, value);

  static const int ascentTimeFieldNum = 16;

  /// ascent_time, in s. Time after leaving bottom until reaching surface
  double? get ascentTime => doubleFieldValue(ascentTimeFieldNum);

  set ascentTime(double? value) => setFieldValue(ascentTimeFieldNum, value);

  static const int avgAscentRateFieldNum = 17;

  /// avg_ascent_rate, in m/s. Average ascent rate, not including descents or stops
  double? get avgAscentRate => doubleFieldValue(avgAscentRateFieldNum);

  set avgAscentRate(double? value) =>
      setFieldValue(avgAscentRateFieldNum, value);

  static const int avgDescentRateFieldNum = 22;

  /// avg_descent_rate, in m/s. Average descent rate, not including ascents or stops
  double? get avgDescentRate => doubleFieldValue(avgDescentRateFieldNum);

  set avgDescentRate(double? value) =>
      setFieldValue(avgDescentRateFieldNum, value);

  static const int maxAscentRateFieldNum = 23;

  /// max_ascent_rate, in m/s. Maximum ascent rate
  double? get maxAscentRate => doubleFieldValue(maxAscentRateFieldNum);

  set maxAscentRate(double? value) =>
      setFieldValue(maxAscentRateFieldNum, value);

  static const int maxDescentRateFieldNum = 24;

  /// max_descent_rate, in m/s. Maximum descent rate
  double? get maxDescentRate => doubleFieldValue(maxDescentRateFieldNum);

  set maxDescentRate(double? value) =>
      setFieldValue(maxDescentRateFieldNum, value);

  static const int hangTimeFieldNum = 25;

  /// hang_time, in s. Time spent neither ascending nor descending
  double? get hangTime => doubleFieldValue(hangTimeFieldNum);

  set hangTime(double? value) => setFieldValue(hangTimeFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[253] =
        Field('timestamp', 253, BaseType.uint32, 1.0, 0.0, 's', false);
    fields[0] =
        Field('reference_mesg', 0, BaseType.uint16, 1.0, 0.0, '', false);
    fields[1] =
        Field('reference_index', 1, BaseType.uint16, 1.0, 0.0, '', false);
    fields[2] = Field('avg_depth', 2, BaseType.uint32, 1000.0, 0.0, 'm', false);
    fields[3] = Field('max_depth', 3, BaseType.uint32, 1000.0, 0.0, 'm', false);
    fields[4] =
        Field('surface_interval', 4, BaseType.uint32, 1.0, 0.0, 's', false);
    fields[5] =
        Field('start_cns', 5, BaseType.uint8, 1.0, 0.0, 'percent', false);
    fields[6] = Field('end_cns', 6, BaseType.uint8, 1.0, 0.0, 'percent', false);
    fields[7] =
        Field('start_n2', 7, BaseType.uint16, 1.0, 0.0, 'percent', false);
    fields[8] = Field('end_n2', 8, BaseType.uint16, 1.0, 0.0, 'percent', false);
    fields[9] =
        Field('o2_toxicity', 9, BaseType.uint16, 1.0, 0.0, 'OTUs', false);
    fields[10] = Field('dive_number', 10, BaseType.uint32, 1.0, 0.0, '', false);
    fields[11] =
        Field('bottom_time', 11, BaseType.uint32, 1000.0, 0.0, 's', false);
    fields[12] = Field(
        'avg_pressure_sac', 12, BaseType.uint16, 100.0, 0.0, 'bar/min', false);
    fields[13] = Field(
        'avg_volume_sac', 13, BaseType.uint16, 100.0, 0.0, 'L/min', false);
    fields[14] =
        Field('avg_rmv', 14, BaseType.uint16, 100.0, 0.0, 'L/min', false);
    fields[15] =
        Field('descent_time', 15, BaseType.uint32, 1000.0, 0.0, 's', false);
    fields[16] =
        Field('ascent_time', 16, BaseType.uint32, 1000.0, 0.0, 's', false);
    fields[17] = Field(
        'avg_ascent_rate', 17, BaseType.sint32, 1000.0, 0.0, 'm/s', false);
    fields[22] = Field(
        'avg_descent_rate', 22, BaseType.uint32, 1000.0, 0.0, 'm/s', false);
    fields[23] = Field(
        'max_ascent_rate', 23, BaseType.uint32, 1000.0, 0.0, 'm/s', false);
    fields[24] = Field(
        'max_descent_rate', 24, BaseType.uint32, 1000.0, 0.0, 'm/s', false);
    fields[25] =
        Field('hang_time', 25, BaseType.uint32, 1000.0, 0.0, 's', false);
    return fields;
  }
}
