/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `dive_settings` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class DiveSettingsMesg extends Mesg {
  DiveSettingsMesg() : super('dive_settings', MesgNum.diveSettings);

  /// A deep copy of [mesg] reinterpreted as a `dive_settings`.
  DiveSettingsMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  DiveSettingsMesg.adopt(super.mesg) : super.adopt();

  static const int timestampFieldNum = 253;

  /// timestamp.
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int messageIndexFieldNum = 254;

  /// message_index.
  int? get messageIndex => intFieldValue(messageIndexFieldNum);

  set messageIndex(int? value) => setFieldValue(messageIndexFieldNum, value);

  static const int name_FieldNum = 0;

  /// name.
  String? get name_ => stringFieldValue(name_FieldNum);

  set name_(String? value) => setFieldValue(name_FieldNum, value);

  static const int modelFieldNum = 1;

  /// model.
  TissueModelType? get model {
    final value = intFieldValue(modelFieldNum);
    return value == null ? null : TissueModelType.fromValue(value);
  }

  set model(TissueModelType? value) =>
      setFieldValue(modelFieldNum, value?.value);

  static const int gfLowFieldNum = 2;

  /// gf_low, in percent.
  int? get gfLow => intFieldValue(gfLowFieldNum);

  set gfLow(int? value) => setFieldValue(gfLowFieldNum, value);

  static const int gfHighFieldNum = 3;

  /// gf_high, in percent.
  int? get gfHigh => intFieldValue(gfHighFieldNum);

  set gfHigh(int? value) => setFieldValue(gfHighFieldNum, value);

  static const int waterTypeFieldNum = 4;

  /// water_type.
  WaterType? get waterType {
    final value = intFieldValue(waterTypeFieldNum);
    return value == null ? null : WaterType.fromValue(value);
  }

  set waterType(WaterType? value) =>
      setFieldValue(waterTypeFieldNum, value?.value);

  static const int waterDensityFieldNum = 5;

  /// water_density, in kg/m^3. Fresh water is usually 1000; salt water is usually 1025
  double? get waterDensity => doubleFieldValue(waterDensityFieldNum);

  set waterDensity(double? value) => setFieldValue(waterDensityFieldNum, value);

  static const int po2WarnFieldNum = 6;

  /// po2_warn, in percent. Typically 1.40
  double? get po2Warn => doubleFieldValue(po2WarnFieldNum);

  set po2Warn(double? value) => setFieldValue(po2WarnFieldNum, value);

  static const int po2CriticalFieldNum = 7;

  /// po2_critical, in percent. Typically 1.60
  double? get po2Critical => doubleFieldValue(po2CriticalFieldNum);

  set po2Critical(double? value) => setFieldValue(po2CriticalFieldNum, value);

  static const int po2DecoFieldNum = 8;

  /// po2_deco, in percent.
  double? get po2Deco => doubleFieldValue(po2DecoFieldNum);

  set po2Deco(double? value) => setFieldValue(po2DecoFieldNum, value);

  static const int safetyStopEnabledFieldNum = 9;

  /// safety_stop_enabled.
  bool? get safetyStopEnabled {
    final value = intFieldValue(safetyStopEnabledFieldNum);
    return value == null ? null : value != 0;
  }

  set safetyStopEnabled(bool? value) => setFieldValue(
      safetyStopEnabledFieldNum, value == null ? null : (value ? 1 : 0));

  static const int bottomDepthFieldNum = 10;

  /// bottom_depth.
  double? get bottomDepth => doubleFieldValue(bottomDepthFieldNum);

  set bottomDepth(double? value) => setFieldValue(bottomDepthFieldNum, value);

  static const int bottomTimeFieldNum = 11;

  /// bottom_time.
  int? get bottomTime => intFieldValue(bottomTimeFieldNum);

  set bottomTime(int? value) => setFieldValue(bottomTimeFieldNum, value);

  static const int apneaCountdownEnabledFieldNum = 12;

  /// apnea_countdown_enabled.
  bool? get apneaCountdownEnabled {
    final value = intFieldValue(apneaCountdownEnabledFieldNum);
    return value == null ? null : value != 0;
  }

  set apneaCountdownEnabled(bool? value) => setFieldValue(
      apneaCountdownEnabledFieldNum, value == null ? null : (value ? 1 : 0));

  static const int apneaCountdownTimeFieldNum = 13;

  /// apnea_countdown_time.
  int? get apneaCountdownTime => intFieldValue(apneaCountdownTimeFieldNum);

  set apneaCountdownTime(int? value) =>
      setFieldValue(apneaCountdownTimeFieldNum, value);

  static const int backlightModeFieldNum = 14;

  /// backlight_mode.
  DiveBacklightMode? get backlightMode {
    final value = intFieldValue(backlightModeFieldNum);
    return value == null ? null : DiveBacklightMode.fromValue(value);
  }

  set backlightMode(DiveBacklightMode? value) =>
      setFieldValue(backlightModeFieldNum, value?.value);

  static const int backlightBrightnessFieldNum = 15;

  /// backlight_brightness.
  int? get backlightBrightness => intFieldValue(backlightBrightnessFieldNum);

  set backlightBrightness(int? value) =>
      setFieldValue(backlightBrightnessFieldNum, value);

  static const int backlightTimeoutFieldNum = 16;

  /// backlight_timeout.
  int? get backlightTimeout => intFieldValue(backlightTimeoutFieldNum);

  set backlightTimeout(int? value) =>
      setFieldValue(backlightTimeoutFieldNum, value);

  static const int repeatDiveIntervalFieldNum = 17;

  /// repeat_dive_interval, in s. Time between surfacing and ending the activity
  int? get repeatDiveInterval => intFieldValue(repeatDiveIntervalFieldNum);

  set repeatDiveInterval(int? value) =>
      setFieldValue(repeatDiveIntervalFieldNum, value);

  static const int safetyStopTimeFieldNum = 18;

  /// safety_stop_time, in s. Time at safety stop (if enabled)
  int? get safetyStopTime => intFieldValue(safetyStopTimeFieldNum);

  set safetyStopTime(int? value) =>
      setFieldValue(safetyStopTimeFieldNum, value);

  static const int heartRateSourceTypeFieldNum = 19;

  /// heart_rate_source_type.
  SourceType? get heartRateSourceType {
    final value = intFieldValue(heartRateSourceTypeFieldNum);
    return value == null ? null : SourceType.fromValue(value);
  }

  set heartRateSourceType(SourceType? value) =>
      setFieldValue(heartRateSourceTypeFieldNum, value?.value);

  static const int heartRateSourceFieldNum = 20;

  /// heart_rate_source.
  int? get heartRateSource => intFieldValue(heartRateSourceFieldNum);

  set heartRateSource(int? value) =>
      setFieldValue(heartRateSourceFieldNum, value);

  /// heart_rate_antplus_device_type: what heart_rate_source means when this message selects it.
  AntplusDeviceType? get heartRateAntplusDeviceType {
    final value = intFieldValue(heartRateSourceFieldNum, 0,
        const NamedSelector('heart_rate_antplus_device_type'));
    return value == null ? null : AntplusDeviceType.fromValue(value);
  }

  void setHeartRateAntplusDeviceType(AntplusDeviceType? value) => setFieldValue(
      heartRateSourceFieldNum,
      value?.value,
      0,
      const NamedSelector('heart_rate_antplus_device_type'));

  /// heart_rate_local_device_type: what heart_rate_source means when this message selects it.
  LocalDeviceType? get heartRateLocalDeviceType {
    final value = intFieldValue(heartRateSourceFieldNum, 0,
        const NamedSelector('heart_rate_local_device_type'));
    return value == null ? null : LocalDeviceType.fromValue(value);
  }

  void setHeartRateLocalDeviceType(LocalDeviceType? value) => setFieldValue(
      heartRateSourceFieldNum,
      value?.value,
      0,
      const NamedSelector('heart_rate_local_device_type'));

  static const int travelGasFieldNum = 21;

  /// travel_gas. Index of travel dive_gas message
  int? get travelGas => intFieldValue(travelGasFieldNum);

  set travelGas(int? value) => setFieldValue(travelGasFieldNum, value);

  static const int ccrLowSetpointSwitchModeFieldNum = 22;

  /// ccr_low_setpoint_switch_mode. If low PO2 should be switched to automatically
  CcrSetpointSwitchMode? get ccrLowSetpointSwitchMode {
    final value = intFieldValue(ccrLowSetpointSwitchModeFieldNum);
    return value == null ? null : CcrSetpointSwitchMode.fromValue(value);
  }

  set ccrLowSetpointSwitchMode(CcrSetpointSwitchMode? value) =>
      setFieldValue(ccrLowSetpointSwitchModeFieldNum, value?.value);

  static const int ccrLowSetpointFieldNum = 23;

  /// ccr_low_setpoint, in percent. Target PO2 when using low setpoint
  double? get ccrLowSetpoint => doubleFieldValue(ccrLowSetpointFieldNum);

  set ccrLowSetpoint(double? value) =>
      setFieldValue(ccrLowSetpointFieldNum, value);

  static const int ccrLowSetpointDepthFieldNum = 24;

  /// ccr_low_setpoint_depth, in m. Depth to switch to low setpoint in automatic mode
  double? get ccrLowSetpointDepth =>
      doubleFieldValue(ccrLowSetpointDepthFieldNum);

  set ccrLowSetpointDepth(double? value) =>
      setFieldValue(ccrLowSetpointDepthFieldNum, value);

  static const int ccrHighSetpointSwitchModeFieldNum = 25;

  /// ccr_high_setpoint_switch_mode. If high PO2 should be switched to automatically
  CcrSetpointSwitchMode? get ccrHighSetpointSwitchMode {
    final value = intFieldValue(ccrHighSetpointSwitchModeFieldNum);
    return value == null ? null : CcrSetpointSwitchMode.fromValue(value);
  }

  set ccrHighSetpointSwitchMode(CcrSetpointSwitchMode? value) =>
      setFieldValue(ccrHighSetpointSwitchModeFieldNum, value?.value);

  static const int ccrHighSetpointFieldNum = 26;

  /// ccr_high_setpoint, in percent. Target PO2 when using high setpoint
  double? get ccrHighSetpoint => doubleFieldValue(ccrHighSetpointFieldNum);

  set ccrHighSetpoint(double? value) =>
      setFieldValue(ccrHighSetpointFieldNum, value);

  static const int ccrHighSetpointDepthFieldNum = 27;

  /// ccr_high_setpoint_depth, in m. Depth to switch to high setpoint in automatic mode
  double? get ccrHighSetpointDepth =>
      doubleFieldValue(ccrHighSetpointDepthFieldNum);

  set ccrHighSetpointDepth(double? value) =>
      setFieldValue(ccrHighSetpointDepthFieldNum, value);

  static const int gasConsumptionDisplayFieldNum = 29;

  /// gas_consumption_display. Type of gas consumption rate to display. Some values are only valid if tank volume is known.
  GasConsumptionRateType? get gasConsumptionDisplay {
    final value = intFieldValue(gasConsumptionDisplayFieldNum);
    return value == null ? null : GasConsumptionRateType.fromValue(value);
  }

  set gasConsumptionDisplay(GasConsumptionRateType? value) =>
      setFieldValue(gasConsumptionDisplayFieldNum, value?.value);

  static const int upKeyEnabledFieldNum = 30;

  /// up_key_enabled. Indicates whether the up key is enabled during dives
  bool? get upKeyEnabled {
    final value = intFieldValue(upKeyEnabledFieldNum);
    return value == null ? null : value != 0;
  }

  set upKeyEnabled(bool? value) => setFieldValue(
      upKeyEnabledFieldNum, value == null ? null : (value ? 1 : 0));

  static const int diveSoundsFieldNum = 35;

  /// dive_sounds. Sounds and vibration enabled or disabled in-dive
  Tone? get diveSounds {
    final value = intFieldValue(diveSoundsFieldNum);
    return value == null ? null : Tone.fromValue(value);
  }

  set diveSounds(Tone? value) =>
      setFieldValue(diveSoundsFieldNum, value?.value);

  static const int lastStopMultipleFieldNum = 36;

  /// last_stop_multiple. Usually 1.0/1.5/2.0 representing 3/4.5/6m or 10/15/20ft
  double? get lastStopMultiple => doubleFieldValue(lastStopMultipleFieldNum);

  set lastStopMultiple(double? value) =>
      setFieldValue(lastStopMultipleFieldNum, value);

  static const int noFlyTimeModeFieldNum = 37;

  /// no_fly_time_mode. Indicates which guidelines to use for no-fly surface interval.
  NoFlyTimeMode? get noFlyTimeMode {
    final value = intFieldValue(noFlyTimeModeFieldNum);
    return value == null ? null : NoFlyTimeMode.fromValue(value);
  }

  set noFlyTimeMode(NoFlyTimeMode? value) =>
      setFieldValue(noFlyTimeModeFieldNum, value?.value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[253] = Field('timestamp', 253, BaseType.uint32, 1.0, 0.0, '', false);
    fields[254] =
        Field('message_index', 254, BaseType.uint16, 1.0, 0.0, '', false);
    fields[0] = Field('name', 0, BaseType.string, 1.0, 0.0, '', false);
    fields[1] = Field('model', 1, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[2] = Field('gf_low', 2, BaseType.uint8, 1.0, 0.0, 'percent', false);
    fields[3] = Field('gf_high', 3, BaseType.uint8, 1.0, 0.0, 'percent', false);
    fields[4] = Field('water_type', 4, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[5] =
        Field('water_density', 5, BaseType.float32, 1.0, 0.0, 'kg/m^3', false);
    fields[6] =
        Field('po2_warn', 6, BaseType.uint8, 100.0, 0.0, 'percent', false);
    fields[7] =
        Field('po2_critical', 7, BaseType.uint8, 100.0, 0.0, 'percent', false);
    fields[8] =
        Field('po2_deco', 8, BaseType.uint8, 100.0, 0.0, 'percent', false);
    fields[9] =
        Field('safety_stop_enabled', 9, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[10] =
        Field('bottom_depth', 10, BaseType.float32, 1.0, 0.0, '', false);
    fields[11] = Field('bottom_time', 11, BaseType.uint32, 1.0, 0.0, '', false);
    fields[12] = Field(
        'apnea_countdown_enabled', 12, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[13] =
        Field('apnea_countdown_time', 13, BaseType.uint32, 1.0, 0.0, '', false);
    fields[14] =
        Field('backlight_mode', 14, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[15] =
        Field('backlight_brightness', 15, BaseType.uint8, 1.0, 0.0, '', false);
    fields[16] =
        Field('backlight_timeout', 16, BaseType.uint8, 1.0, 0.0, '', false);
    fields[17] = Field(
        'repeat_dive_interval', 17, BaseType.uint16, 1.0, 0.0, 's', false);
    fields[18] =
        Field('safety_stop_time', 18, BaseType.uint16, 1.0, 0.0, 's', false);
    fields[19] = Field(
        'heart_rate_source_type', 19, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[20] = Field(
        'heart_rate_source', 20, BaseType.uint8, 1.0, 0.0, '', false)
      ..addSubField(SubField(
          'heart_rate_antplus_device_type', BaseType.uint8, 1.0, 0.0, '')
        ..addMap(19, 1))
      ..addSubField(
          SubField('heart_rate_local_device_type', BaseType.uint8, 1.0, 0.0, '')
            ..addMap(19, 5));
    fields[21] = Field('travel_gas', 21, BaseType.uint16, 1.0, 0.0, '', false);
    fields[22] = Field('ccr_low_setpoint_switch_mode', 22, BaseType.fitEnum,
        1.0, 0.0, '', false);
    fields[23] = Field(
        'ccr_low_setpoint', 23, BaseType.uint8, 100.0, 0.0, 'percent', false);
    fields[24] = Field(
        'ccr_low_setpoint_depth', 24, BaseType.uint32, 1000.0, 0.0, 'm', false);
    fields[25] = Field('ccr_high_setpoint_switch_mode', 25, BaseType.fitEnum,
        1.0, 0.0, '', false);
    fields[26] = Field(
        'ccr_high_setpoint', 26, BaseType.uint8, 100.0, 0.0, 'percent', false);
    fields[27] = Field('ccr_high_setpoint_depth', 27, BaseType.uint32, 1000.0,
        0.0, 'm', false);
    fields[29] = Field(
        'gas_consumption_display', 29, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[30] =
        Field('up_key_enabled', 30, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[35] =
        Field('dive_sounds', 35, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[36] =
        Field('last_stop_multiple', 36, BaseType.uint8, 10.0, 0.0, '', false);
    fields[37] =
        Field('no_fly_time_mode', 37, BaseType.fitEnum, 1.0, 0.0, '', false);
    return fields;
  }
}
