/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `field_capabilities` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class FieldCapabilitiesMesg extends Mesg {
  FieldCapabilitiesMesg()
      : super('field_capabilities', MesgNum.fieldCapabilities);

  /// A deep copy of [mesg] reinterpreted as a `field_capabilities`.
  FieldCapabilitiesMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  FieldCapabilitiesMesg.adopt(super.mesg) : super.adopt();

  static const int messageIndexFieldNum = 254;

  /// message_index.
  int? get messageIndex => intFieldValue(messageIndexFieldNum);

  set messageIndex(int? value) => setFieldValue(messageIndexFieldNum, value);

  static const int fileFieldNum = 0;

  /// file.
  FitFile? get file {
    final value = intFieldValue(fileFieldNum);
    return value == null ? null : FitFile.fromValue(value);
  }

  set file(FitFile? value) => setFieldValue(fileFieldNum, value?.value);

  static const int mesgNumFieldNum = 1;

  /// mesg_num.
  FitMesgNum? get mesgNum {
    final value = intFieldValue(mesgNumFieldNum);
    return value == null ? null : FitMesgNum.fromValue(value);
  }

  set mesgNum(FitMesgNum? value) =>
      setFieldValue(mesgNumFieldNum, value?.value);

  static const int fieldNumFieldNum = 2;

  /// field_num.
  int? get fieldNum => intFieldValue(fieldNumFieldNum);

  set fieldNum(int? value) => setFieldValue(fieldNumFieldNum, value);

  static const int countFieldNum = 3;

  /// count.
  int? get count => intFieldValue(countFieldNum);

  set count(int? value) => setFieldValue(countFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[254] =
        Field('message_index', 254, BaseType.uint16, 1.0, 0.0, '', false);
    fields[0] = Field('file', 0, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[1] = Field('mesg_num', 1, BaseType.uint16, 1.0, 0.0, '', false);
    fields[2] = Field('field_num', 2, BaseType.uint8, 1.0, 0.0, '', false);
    fields[3] = Field('count', 3, BaseType.uint16, 1.0, 0.0, '', false);
    return fields;
  }
}
