/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `field_description` message.
///
/// Must be logged before developer field is used
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class FieldDescriptionMesg extends Mesg {
  FieldDescriptionMesg() : super('field_description', MesgNum.fieldDescription);

  /// A deep copy of [mesg] reinterpreted as a `field_description`.
  FieldDescriptionMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  FieldDescriptionMesg.adopt(super.mesg) : super.adopt();

  static const int developerDataIndexFieldNum = 0;

  /// developer_data_index.
  int? get developerDataIndex => intFieldValue(developerDataIndexFieldNum);

  set developerDataIndex(int? value) =>
      setFieldValue(developerDataIndexFieldNum, value);

  static const int fieldDefinitionNumberFieldNum = 1;

  /// field_definition_number.
  int? get fieldDefinitionNumber =>
      intFieldValue(fieldDefinitionNumberFieldNum);

  set fieldDefinitionNumber(int? value) =>
      setFieldValue(fieldDefinitionNumberFieldNum, value);

  static const int fitBaseTypeIdFieldNum = 2;

  /// fit_base_type_id.
  FitBaseType? get fitBaseTypeId {
    final value = intFieldValue(fitBaseTypeIdFieldNum);
    return value == null ? null : FitBaseType.fromValue(value);
  }

  set fitBaseTypeId(FitBaseType? value) =>
      setFieldValue(fitBaseTypeIdFieldNum, value?.value);

  static const int fieldNameFieldNum = 3;

  /// Number of values stored in field_name.
  int get numFieldName => getField(fieldNameFieldNum)?.numValues ?? 0;

  /// field_name.
  List<String?>? get fieldName {
    final field = getField(fieldNameFieldNum);
    if (field == null) return null;
    return List<String?>.generate(field.numValues, getFieldName);
  }

  set fieldName(List<String?>? value) {
    removeField(fieldNameFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setFieldName(index, value[index]);
    }
  }

  String? getFieldName(int index) => stringFieldValue(fieldNameFieldNum, index);

  void setFieldName(int index, String? value) =>
      setFieldValue(fieldNameFieldNum, value, index);

  static const int arrayFieldNum = 4;

  /// array.
  int? get array => intFieldValue(arrayFieldNum);

  set array(int? value) => setFieldValue(arrayFieldNum, value);

  static const int componentsFieldNum = 5;

  /// components.
  String? get components => stringFieldValue(componentsFieldNum);

  set components(String? value) => setFieldValue(componentsFieldNum, value);

  static const int scaleFieldNum = 6;

  /// scale.
  int? get scale => intFieldValue(scaleFieldNum);

  set scale(int? value) => setFieldValue(scaleFieldNum, value);

  static const int offsetFieldNum = 7;

  /// offset.
  int? get offset => intFieldValue(offsetFieldNum);

  set offset(int? value) => setFieldValue(offsetFieldNum, value);

  static const int unitsFieldNum = 8;

  /// Number of values stored in units.
  int get numUnits => getField(unitsFieldNum)?.numValues ?? 0;

  /// units.
  List<String?>? get units {
    final field = getField(unitsFieldNum);
    if (field == null) return null;
    return List<String?>.generate(field.numValues, getUnits);
  }

  set units(List<String?>? value) {
    removeField(unitsFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setUnits(index, value[index]);
    }
  }

  String? getUnits(int index) => stringFieldValue(unitsFieldNum, index);

  void setUnits(int index, String? value) =>
      setFieldValue(unitsFieldNum, value, index);

  static const int bitsFieldNum = 9;

  /// bits.
  String? get bits => stringFieldValue(bitsFieldNum);

  set bits(String? value) => setFieldValue(bitsFieldNum, value);

  static const int accumulateFieldNum = 10;

  /// accumulate.
  String? get accumulate => stringFieldValue(accumulateFieldNum);

  set accumulate(String? value) => setFieldValue(accumulateFieldNum, value);

  static const int fitBaseUnitIdFieldNum = 13;

  /// fit_base_unit_id.
  FitBaseUnit? get fitBaseUnitId {
    final value = intFieldValue(fitBaseUnitIdFieldNum);
    return value == null ? null : FitBaseUnit.fromValue(value);
  }

  set fitBaseUnitId(FitBaseUnit? value) =>
      setFieldValue(fitBaseUnitIdFieldNum, value?.value);

  static const int nativeMesgNumFieldNum = 14;

  /// native_mesg_num.
  FitMesgNum? get nativeMesgNum {
    final value = intFieldValue(nativeMesgNumFieldNum);
    return value == null ? null : FitMesgNum.fromValue(value);
  }

  set nativeMesgNum(FitMesgNum? value) =>
      setFieldValue(nativeMesgNumFieldNum, value?.value);

  static const int nativeFieldNumFieldNum = 15;

  /// native_field_num.
  int? get nativeFieldNum => intFieldValue(nativeFieldNumFieldNum);

  set nativeFieldNum(int? value) =>
      setFieldValue(nativeFieldNumFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[0] =
        Field('developer_data_index', 0, BaseType.uint8, 1.0, 0.0, '', false);
    fields[1] = Field(
        'field_definition_number', 1, BaseType.uint8, 1.0, 0.0, '', false);
    fields[2] =
        Field('fit_base_type_id', 2, BaseType.uint8, 1.0, 0.0, '', false);
    fields[3] = Field('field_name', 3, BaseType.string, 1.0, 0.0, '', false);
    fields[4] = Field('array', 4, BaseType.uint8, 1.0, 0.0, '', false);
    fields[5] = Field('components', 5, BaseType.string, 1.0, 0.0, '', false);
    fields[6] = Field('scale', 6, BaseType.uint8, 1.0, 0.0, '', false);
    fields[7] = Field('offset', 7, BaseType.sint8, 1.0, 0.0, '', false);
    fields[8] = Field('units', 8, BaseType.string, 1.0, 0.0, '', false);
    fields[9] = Field('bits', 9, BaseType.string, 1.0, 0.0, '', false);
    fields[10] = Field('accumulate', 10, BaseType.string, 1.0, 0.0, '', false);
    fields[13] =
        Field('fit_base_unit_id', 13, BaseType.uint16, 1.0, 0.0, '', false);
    fields[14] =
        Field('native_mesg_num', 14, BaseType.uint16, 1.0, 0.0, '', false);
    fields[15] =
        Field('native_field_num', 15, BaseType.uint8, 1.0, 0.0, '', false);
    return fields;
  }
}
