/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `gyroscope_data` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class GyroscopeDataMesg extends Mesg {
  GyroscopeDataMesg() : super('gyroscope_data', MesgNum.gyroscopeData);

  /// A deep copy of [mesg] reinterpreted as a `gyroscope_data`.
  GyroscopeDataMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  GyroscopeDataMesg.adopt(super.mesg) : super.adopt();

  static const int timestampFieldNum = 253;

  /// timestamp, in s. Whole second part of the timestamp
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int timestampMsFieldNum = 0;

  /// timestamp_ms, in ms. Millisecond part of the timestamp.
  int? get timestampMs => intFieldValue(timestampMsFieldNum);

  set timestampMs(int? value) => setFieldValue(timestampMsFieldNum, value);

  static const int sampleTimeOffsetFieldNum = 1;

  /// Number of values stored in sample_time_offset.
  int get numSampleTimeOffset =>
      getField(sampleTimeOffsetFieldNum)?.numValues ?? 0;

  /// sample_time_offset, in ms. Each time in the array describes the time at which the gyro sample with the corrosponding index was taken. Limited to 30 samples in each message. The samples may span across seconds. Array size must match the number of samples in gyro_x and gyro_y and gyro_z
  List<int?>? get sampleTimeOffset {
    final field = getField(sampleTimeOffsetFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getSampleTimeOffset);
  }

  set sampleTimeOffset(List<int?>? value) {
    removeField(sampleTimeOffsetFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setSampleTimeOffset(index, value[index]);
    }
  }

  int? getSampleTimeOffset(int index) =>
      intFieldValue(sampleTimeOffsetFieldNum, index);

  void setSampleTimeOffset(int index, int? value) =>
      setFieldValue(sampleTimeOffsetFieldNum, value, index);

  static const int gyroXFieldNum = 2;

  /// Number of values stored in gyro_x.
  int get numGyroX => getField(gyroXFieldNum)?.numValues ?? 0;

  /// gyro_x, in counts. These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
  List<int?>? get gyroX {
    final field = getField(gyroXFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getGyroX);
  }

  set gyroX(List<int?>? value) {
    removeField(gyroXFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setGyroX(index, value[index]);
    }
  }

  int? getGyroX(int index) => intFieldValue(gyroXFieldNum, index);

  void setGyroX(int index, int? value) =>
      setFieldValue(gyroXFieldNum, value, index);

  static const int gyroYFieldNum = 3;

  /// Number of values stored in gyro_y.
  int get numGyroY => getField(gyroYFieldNum)?.numValues ?? 0;

  /// gyro_y, in counts. These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
  List<int?>? get gyroY {
    final field = getField(gyroYFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getGyroY);
  }

  set gyroY(List<int?>? value) {
    removeField(gyroYFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setGyroY(index, value[index]);
    }
  }

  int? getGyroY(int index) => intFieldValue(gyroYFieldNum, index);

  void setGyroY(int index, int? value) =>
      setFieldValue(gyroYFieldNum, value, index);

  static const int gyroZFieldNum = 4;

  /// Number of values stored in gyro_z.
  int get numGyroZ => getField(gyroZFieldNum)?.numValues ?? 0;

  /// gyro_z, in counts. These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
  List<int?>? get gyroZ {
    final field = getField(gyroZFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getGyroZ);
  }

  set gyroZ(List<int?>? value) {
    removeField(gyroZFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setGyroZ(index, value[index]);
    }
  }

  int? getGyroZ(int index) => intFieldValue(gyroZFieldNum, index);

  void setGyroZ(int index, int? value) =>
      setFieldValue(gyroZFieldNum, value, index);

  static const int calibratedGyroXFieldNum = 5;

  /// Number of values stored in calibrated_gyro_x.
  int get numCalibratedGyroX =>
      getField(calibratedGyroXFieldNum)?.numValues ?? 0;

  /// calibrated_gyro_x, in deg/s. Calibrated gyro reading
  List<double?>? get calibratedGyroX {
    final field = getField(calibratedGyroXFieldNum);
    if (field == null) return null;
    return List<double?>.generate(field.numValues, getCalibratedGyroX);
  }

  set calibratedGyroX(List<double?>? value) {
    removeField(calibratedGyroXFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setCalibratedGyroX(index, value[index]);
    }
  }

  double? getCalibratedGyroX(int index) =>
      doubleFieldValue(calibratedGyroXFieldNum, index);

  void setCalibratedGyroX(int index, double? value) =>
      setFieldValue(calibratedGyroXFieldNum, value, index);

  static const int calibratedGyroYFieldNum = 6;

  /// Number of values stored in calibrated_gyro_y.
  int get numCalibratedGyroY =>
      getField(calibratedGyroYFieldNum)?.numValues ?? 0;

  /// calibrated_gyro_y, in deg/s. Calibrated gyro reading
  List<double?>? get calibratedGyroY {
    final field = getField(calibratedGyroYFieldNum);
    if (field == null) return null;
    return List<double?>.generate(field.numValues, getCalibratedGyroY);
  }

  set calibratedGyroY(List<double?>? value) {
    removeField(calibratedGyroYFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setCalibratedGyroY(index, value[index]);
    }
  }

  double? getCalibratedGyroY(int index) =>
      doubleFieldValue(calibratedGyroYFieldNum, index);

  void setCalibratedGyroY(int index, double? value) =>
      setFieldValue(calibratedGyroYFieldNum, value, index);

  static const int calibratedGyroZFieldNum = 7;

  /// Number of values stored in calibrated_gyro_z.
  int get numCalibratedGyroZ =>
      getField(calibratedGyroZFieldNum)?.numValues ?? 0;

  /// calibrated_gyro_z, in deg/s. Calibrated gyro reading
  List<double?>? get calibratedGyroZ {
    final field = getField(calibratedGyroZFieldNum);
    if (field == null) return null;
    return List<double?>.generate(field.numValues, getCalibratedGyroZ);
  }

  set calibratedGyroZ(List<double?>? value) {
    removeField(calibratedGyroZFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setCalibratedGyroZ(index, value[index]);
    }
  }

  double? getCalibratedGyroZ(int index) =>
      doubleFieldValue(calibratedGyroZFieldNum, index);

  void setCalibratedGyroZ(int index, double? value) =>
      setFieldValue(calibratedGyroZFieldNum, value, index);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[253] =
        Field('timestamp', 253, BaseType.uint32, 1.0, 0.0, 's', false);
    fields[0] =
        Field('timestamp_ms', 0, BaseType.uint16, 1.0, 0.0, 'ms', false);
    fields[1] =
        Field('sample_time_offset', 1, BaseType.uint16, 1.0, 0.0, 'ms', false);
    fields[2] = Field('gyro_x', 2, BaseType.uint16, 1.0, 0.0, 'counts', false);
    fields[3] = Field('gyro_y', 3, BaseType.uint16, 1.0, 0.0, 'counts', false);
    fields[4] = Field('gyro_z', 4, BaseType.uint16, 1.0, 0.0, 'counts', false);
    fields[5] = Field(
        'calibrated_gyro_x', 5, BaseType.float32, 1.0, 0.0, 'deg/s', false);
    fields[6] = Field(
        'calibrated_gyro_y', 6, BaseType.float32, 1.0, 0.0, 'deg/s', false);
    fields[7] = Field(
        'calibrated_gyro_z', 7, BaseType.float32, 1.0, 0.0, 'deg/s', false);
    return fields;
  }
}
