/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `hrm_profile` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class HrmProfileMesg extends Mesg {
  HrmProfileMesg() : super('hrm_profile', MesgNum.hrmProfile);

  /// A deep copy of [mesg] reinterpreted as a `hrm_profile`.
  HrmProfileMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  HrmProfileMesg.adopt(super.mesg) : super.adopt();

  static const int messageIndexFieldNum = 254;

  /// message_index.
  int? get messageIndex => intFieldValue(messageIndexFieldNum);

  set messageIndex(int? value) => setFieldValue(messageIndexFieldNum, value);

  static const int enabledFieldNum = 0;

  /// enabled.
  bool? get enabled {
    final value = intFieldValue(enabledFieldNum);
    return value == null ? null : value != 0;
  }

  set enabled(bool? value) =>
      setFieldValue(enabledFieldNum, value == null ? null : (value ? 1 : 0));

  static const int hrmAntIdFieldNum = 1;

  /// hrm_ant_id.
  int? get hrmAntId => intFieldValue(hrmAntIdFieldNum);

  set hrmAntId(int? value) => setFieldValue(hrmAntIdFieldNum, value);

  static const int logHrvFieldNum = 2;

  /// log_hrv.
  bool? get logHrv {
    final value = intFieldValue(logHrvFieldNum);
    return value == null ? null : value != 0;
  }

  set logHrv(bool? value) =>
      setFieldValue(logHrvFieldNum, value == null ? null : (value ? 1 : 0));

  static const int hrmAntIdTransTypeFieldNum = 3;

  /// hrm_ant_id_trans_type.
  int? get hrmAntIdTransType => intFieldValue(hrmAntIdTransTypeFieldNum);

  set hrmAntIdTransType(int? value) =>
      setFieldValue(hrmAntIdTransTypeFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[254] =
        Field('message_index', 254, BaseType.uint16, 1.0, 0.0, '', false);
    fields[0] = Field('enabled', 0, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[1] = Field('hrm_ant_id', 1, BaseType.uint16z, 1.0, 0.0, '', false);
    fields[2] = Field('log_hrv', 2, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[3] =
        Field('hrm_ant_id_trans_type', 3, BaseType.uint8z, 1.0, 0.0, '', false);
    return fields;
  }
}
