/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `hrv_value` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class HrvValueMesg extends Mesg {
  HrvValueMesg() : super('hrv_value', MesgNum.hrvValue);

  /// A deep copy of [mesg] reinterpreted as a `hrv_value`.
  HrvValueMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  HrvValueMesg.adopt(super.mesg) : super.adopt();

  static const int timestampFieldNum = 253;

  /// timestamp.
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int valueFieldNum = 0;

  /// value, in ms. 5 minute RMSSD
  double? get value => doubleFieldValue(valueFieldNum);

  set value(double? value) => setFieldValue(valueFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[253] = Field('timestamp', 253, BaseType.uint32, 1.0, 0.0, '', false);
    fields[0] = Field('value', 0, BaseType.uint16, 128.0, 0.0, 'ms', false);
    return fields;
  }
}
