/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `hsa_respiration_data` message.
///
/// User's current respiration data used for HSA custom data logging
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class HsaRespirationDataMesg extends Mesg {
  HsaRespirationDataMesg()
      : super('hsa_respiration_data', MesgNum.hsaRespirationData);

  /// A deep copy of [mesg] reinterpreted as a `hsa_respiration_data`.
  HsaRespirationDataMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  HsaRespirationDataMesg.adopt(super.mesg) : super.adopt();

  static const int timestampFieldNum = 253;

  /// timestamp, in s.
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int processingIntervalFieldNum = 0;

  /// processing_interval, in s. Processing interval length in seconds
  int? get processingInterval => intFieldValue(processingIntervalFieldNum);

  set processingInterval(int? value) =>
      setFieldValue(processingIntervalFieldNum, value);

  static const int respirationRateFieldNum = 1;

  /// Number of values stored in respiration_rate.
  int get numRespirationRate =>
      getField(respirationRateFieldNum)?.numValues ?? 0;

  /// respiration_rate, in breaths/min. Breaths / min: [1,100] Invalid: 255 Excess motion: 254 Off wrist: 253 Not available: 252 Blank: 2.4
  List<double?>? get respirationRate {
    final field = getField(respirationRateFieldNum);
    if (field == null) return null;
    return List<double?>.generate(field.numValues, getRespirationRate);
  }

  set respirationRate(List<double?>? value) {
    removeField(respirationRateFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setRespirationRate(index, value[index]);
    }
  }

  double? getRespirationRate(int index) =>
      doubleFieldValue(respirationRateFieldNum, index);

  void setRespirationRate(int index, double? value) =>
      setFieldValue(respirationRateFieldNum, value, index);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[253] =
        Field('timestamp', 253, BaseType.uint32, 1.0, 0.0, 's', false);
    fields[0] =
        Field('processing_interval', 0, BaseType.uint16, 1.0, 0.0, 's', false);
    fields[1] = Field('respiration_rate', 1, BaseType.sint16, 100.0, 0.0,
        'breaths/min', false);
    return fields;
  }
}
