/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `hsa_accelerometer_data` message.
///
/// Raw accelerometer data used for HSA custom data logging
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class HsaAccelerometerDataMesg extends Mesg {
  HsaAccelerometerDataMesg()
      : super('hsa_accelerometer_data', MesgNum.hsaAccelerometerData);

  /// A deep copy of [mesg] reinterpreted as a `hsa_accelerometer_data`.
  HsaAccelerometerDataMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  HsaAccelerometerDataMesg.adopt(super.mesg) : super.adopt();

  static const int timestampFieldNum = 253;

  /// timestamp, in s.
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int timestampMsFieldNum = 0;

  /// timestamp_ms, in ms. Millisecond resolution of the timestamp
  int? get timestampMs => intFieldValue(timestampMsFieldNum);

  set timestampMs(int? value) => setFieldValue(timestampMsFieldNum, value);

  static const int samplingIntervalFieldNum = 1;

  /// sampling_interval, in ms. Sampling Interval in Milliseconds
  int? get samplingInterval => intFieldValue(samplingIntervalFieldNum);

  set samplingInterval(int? value) =>
      setFieldValue(samplingIntervalFieldNum, value);

  static const int accelXFieldNum = 2;

  /// Number of values stored in accel_x.
  int get numAccelX => getField(accelXFieldNum)?.numValues ?? 0;

  /// accel_x, in mG. X-Axis Measurement
  List<double?>? get accelX {
    final field = getField(accelXFieldNum);
    if (field == null) return null;
    return List<double?>.generate(field.numValues, getAccelX);
  }

  set accelX(List<double?>? value) {
    removeField(accelXFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setAccelX(index, value[index]);
    }
  }

  double? getAccelX(int index) => doubleFieldValue(accelXFieldNum, index);

  void setAccelX(int index, double? value) =>
      setFieldValue(accelXFieldNum, value, index);

  static const int accelYFieldNum = 3;

  /// Number of values stored in accel_y.
  int get numAccelY => getField(accelYFieldNum)?.numValues ?? 0;

  /// accel_y, in mG. Y-Axis Measurement
  List<double?>? get accelY {
    final field = getField(accelYFieldNum);
    if (field == null) return null;
    return List<double?>.generate(field.numValues, getAccelY);
  }

  set accelY(List<double?>? value) {
    removeField(accelYFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setAccelY(index, value[index]);
    }
  }

  double? getAccelY(int index) => doubleFieldValue(accelYFieldNum, index);

  void setAccelY(int index, double? value) =>
      setFieldValue(accelYFieldNum, value, index);

  static const int accelZFieldNum = 4;

  /// Number of values stored in accel_z.
  int get numAccelZ => getField(accelZFieldNum)?.numValues ?? 0;

  /// accel_z, in mG. Z-Axis Measurement
  List<double?>? get accelZ {
    final field = getField(accelZFieldNum);
    if (field == null) return null;
    return List<double?>.generate(field.numValues, getAccelZ);
  }

  set accelZ(List<double?>? value) {
    removeField(accelZFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setAccelZ(index, value[index]);
    }
  }

  double? getAccelZ(int index) => doubleFieldValue(accelZFieldNum, index);

  void setAccelZ(int index, double? value) =>
      setFieldValue(accelZFieldNum, value, index);

  static const int timestamp32kFieldNum = 5;

  /// timestamp_32k. 32 kHz timestamp
  int? get timestamp32k => intFieldValue(timestamp32kFieldNum);

  set timestamp32k(int? value) => setFieldValue(timestamp32kFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[253] =
        Field('timestamp', 253, BaseType.uint32, 1.0, 0.0, 's', false);
    fields[0] =
        Field('timestamp_ms', 0, BaseType.uint16, 1.0, 0.0, 'ms', false);
    fields[1] =
        Field('sampling_interval', 1, BaseType.uint16, 1.0, 0.0, 'ms', false);
    fields[2] = Field('accel_x', 2, BaseType.sint16, 1.024, 0.0, 'mG', false);
    fields[3] = Field('accel_y', 3, BaseType.sint16, 1.024, 0.0, 'mG', false);
    fields[4] = Field('accel_z', 4, BaseType.sint16, 1.024, 0.0, 'mG', false);
    fields[5] = Field('timestamp_32k', 5, BaseType.uint32, 1.0, 0.0, '', false);
    return fields;
  }
}
