/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `hsa_body_battery_data` message.
///
/// Body battery data used for HSA custom data logging
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class HsaBodyBatteryDataMesg extends Mesg {
  HsaBodyBatteryDataMesg()
      : super('hsa_body_battery_data', MesgNum.hsaBodyBatteryData);

  /// A deep copy of [mesg] reinterpreted as a `hsa_body_battery_data`.
  HsaBodyBatteryDataMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  HsaBodyBatteryDataMesg.adopt(super.mesg) : super.adopt();

  static const int timestampFieldNum = 253;

  /// timestamp, in s.
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int processingIntervalFieldNum = 0;

  /// processing_interval, in s. Processing interval length in seconds
  int? get processingInterval => intFieldValue(processingIntervalFieldNum);

  set processingInterval(int? value) =>
      setFieldValue(processingIntervalFieldNum, value);

  static const int levelFieldNum = 1;

  /// Number of values stored in level.
  int get numLevel => getField(levelFieldNum)?.numValues ?? 0;

  /// level, in percent. Body battery level: [0,100] Blank: -16
  List<int?>? get level {
    final field = getField(levelFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getLevel);
  }

  set level(List<int?>? value) {
    removeField(levelFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setLevel(index, value[index]);
    }
  }

  int? getLevel(int index) => intFieldValue(levelFieldNum, index);

  void setLevel(int index, int? value) =>
      setFieldValue(levelFieldNum, value, index);

  static const int chargedFieldNum = 2;

  /// Number of values stored in charged.
  int get numCharged => getField(chargedFieldNum)?.numValues ?? 0;

  /// charged. Body battery charged value
  List<int?>? get charged {
    final field = getField(chargedFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getCharged);
  }

  set charged(List<int?>? value) {
    removeField(chargedFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setCharged(index, value[index]);
    }
  }

  int? getCharged(int index) => intFieldValue(chargedFieldNum, index);

  void setCharged(int index, int? value) =>
      setFieldValue(chargedFieldNum, value, index);

  static const int unchargedFieldNum = 3;

  /// Number of values stored in uncharged.
  int get numUncharged => getField(unchargedFieldNum)?.numValues ?? 0;

  /// uncharged. Body battery uncharged value
  List<int?>? get uncharged {
    final field = getField(unchargedFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getUncharged);
  }

  set uncharged(List<int?>? value) {
    removeField(unchargedFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setUncharged(index, value[index]);
    }
  }

  int? getUncharged(int index) => intFieldValue(unchargedFieldNum, index);

  void setUncharged(int index, int? value) =>
      setFieldValue(unchargedFieldNum, value, index);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[253] =
        Field('timestamp', 253, BaseType.uint32, 1.0, 0.0, 's', false);
    fields[0] =
        Field('processing_interval', 0, BaseType.uint16, 1.0, 0.0, 's', false);
    fields[1] = Field('level', 1, BaseType.sint8, 1.0, 0.0, 'percent', false);
    fields[2] = Field('charged', 2, BaseType.sint16, 1.0, 0.0, '', false);
    fields[3] = Field('uncharged', 3, BaseType.sint16, 1.0, 0.0, '', false);
    return fields;
  }
}
