/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `jump` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class JumpMesg extends Mesg {
  JumpMesg() : super('jump', MesgNum.jump);

  /// A deep copy of [mesg] reinterpreted as a `jump`.
  JumpMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  JumpMesg.adopt(super.mesg) : super.adopt();

  static const int timestampFieldNum = 253;

  /// timestamp, in s.
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int distanceFieldNum = 0;

  /// distance, in m.
  double? get distance => doubleFieldValue(distanceFieldNum);

  set distance(double? value) => setFieldValue(distanceFieldNum, value);

  static const int heightFieldNum = 1;

  /// height, in m.
  double? get height => doubleFieldValue(heightFieldNum);

  set height(double? value) => setFieldValue(heightFieldNum, value);

  static const int rotationsFieldNum = 2;

  /// rotations.
  int? get rotations => intFieldValue(rotationsFieldNum);

  set rotations(int? value) => setFieldValue(rotationsFieldNum, value);

  static const int hangTimeFieldNum = 3;

  /// hang_time, in s.
  double? get hangTime => doubleFieldValue(hangTimeFieldNum);

  set hangTime(double? value) => setFieldValue(hangTimeFieldNum, value);

  static const int scoreFieldNum = 4;

  /// score. A score for a jump calculated based on hang time, rotations, and distance.
  double? get score => doubleFieldValue(scoreFieldNum);

  set score(double? value) => setFieldValue(scoreFieldNum, value);

  static const int positionLatFieldNum = 5;

  /// position_lat, in semicircles.
  int? get positionLat => intFieldValue(positionLatFieldNum);

  set positionLat(int? value) => setFieldValue(positionLatFieldNum, value);

  static const int positionLongFieldNum = 6;

  /// position_long, in semicircles.
  int? get positionLong => intFieldValue(positionLongFieldNum);

  set positionLong(int? value) => setFieldValue(positionLongFieldNum, value);

  static const int speedFieldNum = 7;

  /// speed, in m/s.
  double? get speed => doubleFieldValue(speedFieldNum);

  set speed(double? value) => setFieldValue(speedFieldNum, value);

  static const int enhancedSpeedFieldNum = 8;

  /// enhanced_speed, in m/s.
  double? get enhancedSpeed => doubleFieldValue(enhancedSpeedFieldNum);

  set enhancedSpeed(double? value) =>
      setFieldValue(enhancedSpeedFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[253] =
        Field('timestamp', 253, BaseType.uint32, 1.0, 0.0, 's', false);
    fields[0] = Field('distance', 0, BaseType.float32, 1.0, 0.0, 'm', false);
    fields[1] = Field('height', 1, BaseType.float32, 1.0, 0.0, 'm', false);
    fields[2] = Field('rotations', 2, BaseType.uint8, 1.0, 0.0, '', false);
    fields[3] = Field('hang_time', 3, BaseType.float32, 1.0, 0.0, 's', false);
    fields[4] = Field('score', 4, BaseType.float32, 1.0, 0.0, '', false);
    fields[5] = Field(
        'position_lat', 5, BaseType.sint32, 1.0, 0.0, 'semicircles', false);
    fields[6] = Field(
        'position_long', 6, BaseType.sint32, 1.0, 0.0, 'semicircles', false);
    fields[7] = Field('speed', 7, BaseType.uint16, 1000.0, 0.0, 'm/s', false)
      ..addComponent(const FieldComponent(8, false, 16, 1000.0, 0.0));
    fields[8] =
        Field('enhanced_speed', 8, BaseType.uint32, 1000.0, 0.0, 'm/s', false);
    return fields;
  }
}
