/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `length` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class LengthMesg extends Mesg {
  LengthMesg() : super('length', MesgNum.length);

  /// A deep copy of [mesg] reinterpreted as a `length`.
  LengthMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  LengthMesg.adopt(super.mesg) : super.adopt();

  static const int messageIndexFieldNum = 254;

  /// message_index.
  int? get messageIndex => intFieldValue(messageIndexFieldNum);

  set messageIndex(int? value) => setFieldValue(messageIndexFieldNum, value);

  static const int timestampFieldNum = 253;

  /// timestamp.
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int eventFieldNum = 0;

  /// event.
  Event? get event {
    final value = intFieldValue(eventFieldNum);
    return value == null ? null : Event.fromValue(value);
  }

  set event(Event? value) => setFieldValue(eventFieldNum, value?.value);

  static const int eventTypeFieldNum = 1;

  /// event_type.
  EventType? get eventType {
    final value = intFieldValue(eventTypeFieldNum);
    return value == null ? null : EventType.fromValue(value);
  }

  set eventType(EventType? value) =>
      setFieldValue(eventTypeFieldNum, value?.value);

  static const int startTimeFieldNum = 2;

  /// start_time.
  DateTime? get startTime {
    final value = intFieldValue(startTimeFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set startTime(DateTime? value) => setFieldValue(
      startTimeFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int totalElapsedTimeFieldNum = 3;

  /// total_elapsed_time, in s.
  double? get totalElapsedTime => doubleFieldValue(totalElapsedTimeFieldNum);

  set totalElapsedTime(double? value) =>
      setFieldValue(totalElapsedTimeFieldNum, value);

  static const int totalTimerTimeFieldNum = 4;

  /// total_timer_time, in s.
  double? get totalTimerTime => doubleFieldValue(totalTimerTimeFieldNum);

  set totalTimerTime(double? value) =>
      setFieldValue(totalTimerTimeFieldNum, value);

  static const int totalStrokesFieldNum = 5;

  /// total_strokes, in strokes.
  int? get totalStrokes => intFieldValue(totalStrokesFieldNum);

  set totalStrokes(int? value) => setFieldValue(totalStrokesFieldNum, value);

  static const int avgSpeedFieldNum = 6;

  /// avg_speed, in m/s.
  double? get avgSpeed => doubleFieldValue(avgSpeedFieldNum);

  set avgSpeed(double? value) => setFieldValue(avgSpeedFieldNum, value);

  static const int swimStrokeFieldNum = 7;

  /// swim_stroke, in swim_stroke.
  SwimStroke? get swimStroke {
    final value = intFieldValue(swimStrokeFieldNum);
    return value == null ? null : SwimStroke.fromValue(value);
  }

  set swimStroke(SwimStroke? value) =>
      setFieldValue(swimStrokeFieldNum, value?.value);

  static const int avgSwimmingCadenceFieldNum = 9;

  /// avg_swimming_cadence, in strokes/min.
  int? get avgSwimmingCadence => intFieldValue(avgSwimmingCadenceFieldNum);

  set avgSwimmingCadence(int? value) =>
      setFieldValue(avgSwimmingCadenceFieldNum, value);

  static const int eventGroupFieldNum = 10;

  /// event_group.
  int? get eventGroup => intFieldValue(eventGroupFieldNum);

  set eventGroup(int? value) => setFieldValue(eventGroupFieldNum, value);

  static const int totalCaloriesFieldNum = 11;

  /// total_calories, in kcal.
  int? get totalCalories => intFieldValue(totalCaloriesFieldNum);

  set totalCalories(int? value) => setFieldValue(totalCaloriesFieldNum, value);

  static const int lengthTypeFieldNum = 12;

  /// length_type.
  LengthType? get lengthType {
    final value = intFieldValue(lengthTypeFieldNum);
    return value == null ? null : LengthType.fromValue(value);
  }

  set lengthType(LengthType? value) =>
      setFieldValue(lengthTypeFieldNum, value?.value);

  static const int playerScoreFieldNum = 18;

  /// player_score.
  int? get playerScore => intFieldValue(playerScoreFieldNum);

  set playerScore(int? value) => setFieldValue(playerScoreFieldNum, value);

  static const int opponentScoreFieldNum = 19;

  /// opponent_score.
  int? get opponentScore => intFieldValue(opponentScoreFieldNum);

  set opponentScore(int? value) => setFieldValue(opponentScoreFieldNum, value);

  static const int strokeCountFieldNum = 20;

  /// Number of values stored in stroke_count.
  int get numStrokeCount => getField(strokeCountFieldNum)?.numValues ?? 0;

  /// stroke_count, in counts. stroke_type enum used as the index
  List<int?>? get strokeCount {
    final field = getField(strokeCountFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getStrokeCount);
  }

  set strokeCount(List<int?>? value) {
    removeField(strokeCountFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setStrokeCount(index, value[index]);
    }
  }

  int? getStrokeCount(int index) => intFieldValue(strokeCountFieldNum, index);

  void setStrokeCount(int index, int? value) =>
      setFieldValue(strokeCountFieldNum, value, index);

  static const int zoneCountFieldNum = 21;

  /// Number of values stored in zone_count.
  int get numZoneCount => getField(zoneCountFieldNum)?.numValues ?? 0;

  /// zone_count, in counts. zone number used as the index
  List<int?>? get zoneCount {
    final field = getField(zoneCountFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getZoneCount);
  }

  set zoneCount(List<int?>? value) {
    removeField(zoneCountFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setZoneCount(index, value[index]);
    }
  }

  int? getZoneCount(int index) => intFieldValue(zoneCountFieldNum, index);

  void setZoneCount(int index, int? value) =>
      setFieldValue(zoneCountFieldNum, value, index);

  static const int enhancedAvgRespirationRateFieldNum = 22;

  /// enhanced_avg_respiration_rate, in Breaths/min.
  double? get enhancedAvgRespirationRate =>
      doubleFieldValue(enhancedAvgRespirationRateFieldNum);

  set enhancedAvgRespirationRate(double? value) =>
      setFieldValue(enhancedAvgRespirationRateFieldNum, value);

  static const int enhancedMaxRespirationRateFieldNum = 23;

  /// enhanced_max_respiration_rate, in Breaths/min.
  double? get enhancedMaxRespirationRate =>
      doubleFieldValue(enhancedMaxRespirationRateFieldNum);

  set enhancedMaxRespirationRate(double? value) =>
      setFieldValue(enhancedMaxRespirationRateFieldNum, value);

  static const int avgRespirationRateFieldNum = 24;

  /// avg_respiration_rate.
  int? get avgRespirationRate => intFieldValue(avgRespirationRateFieldNum);

  set avgRespirationRate(int? value) =>
      setFieldValue(avgRespirationRateFieldNum, value);

  static const int maxRespirationRateFieldNum = 25;

  /// max_respiration_rate.
  int? get maxRespirationRate => intFieldValue(maxRespirationRateFieldNum);

  set maxRespirationRate(int? value) =>
      setFieldValue(maxRespirationRateFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[254] =
        Field('message_index', 254, BaseType.uint16, 1.0, 0.0, '', false);
    fields[253] = Field('timestamp', 253, BaseType.uint32, 1.0, 0.0, '', false);
    fields[0] = Field('event', 0, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[1] = Field('event_type', 1, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[2] = Field('start_time', 2, BaseType.uint32, 1.0, 0.0, '', false);
    fields[3] = Field(
        'total_elapsed_time', 3, BaseType.uint32, 1000.0, 0.0, 's', false);
    fields[4] =
        Field('total_timer_time', 4, BaseType.uint32, 1000.0, 0.0, 's', false);
    fields[5] =
        Field('total_strokes', 5, BaseType.uint16, 1.0, 0.0, 'strokes', false);
    fields[6] =
        Field('avg_speed', 6, BaseType.uint16, 1000.0, 0.0, 'm/s', false);
    fields[7] = Field(
        'swim_stroke', 7, BaseType.fitEnum, 1.0, 0.0, 'swim_stroke', false);
    fields[9] = Field('avg_swimming_cadence', 9, BaseType.uint8, 1.0, 0.0,
        'strokes/min', false);
    fields[10] = Field('event_group', 10, BaseType.uint8, 1.0, 0.0, '', false);
    fields[11] =
        Field('total_calories', 11, BaseType.uint16, 1.0, 0.0, 'kcal', false);
    fields[12] =
        Field('length_type', 12, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[18] =
        Field('player_score', 18, BaseType.uint16, 1.0, 0.0, '', false);
    fields[19] =
        Field('opponent_score', 19, BaseType.uint16, 1.0, 0.0, '', false);
    fields[20] =
        Field('stroke_count', 20, BaseType.uint16, 1.0, 0.0, 'counts', false);
    fields[21] =
        Field('zone_count', 21, BaseType.uint16, 1.0, 0.0, 'counts', false);
    fields[22] = Field('enhanced_avg_respiration_rate', 22, BaseType.uint16,
        100.0, 0.0, 'Breaths/min', false);
    fields[23] = Field('enhanced_max_respiration_rate', 23, BaseType.uint16,
        100.0, 0.0, 'Breaths/min', false);
    fields[24] =
        Field('avg_respiration_rate', 24, BaseType.uint8, 1.0, 0.0, '', false)
          ..addComponent(const FieldComponent(22, false, 8, 1.0, 0.0));
    fields[25] =
        Field('max_respiration_rate', 25, BaseType.uint8, 1.0, 0.0, '', false)
          ..addComponent(const FieldComponent(23, false, 8, 1.0, 0.0));
    return fields;
  }
}
