/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `met_zone` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class MetZoneMesg extends Mesg {
  MetZoneMesg() : super('met_zone', MesgNum.metZone);

  /// A deep copy of [mesg] reinterpreted as a `met_zone`.
  MetZoneMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  MetZoneMesg.adopt(super.mesg) : super.adopt();

  static const int messageIndexFieldNum = 254;

  /// message_index.
  int? get messageIndex => intFieldValue(messageIndexFieldNum);

  set messageIndex(int? value) => setFieldValue(messageIndexFieldNum, value);

  static const int highBpmFieldNum = 1;

  /// high_bpm.
  int? get highBpm => intFieldValue(highBpmFieldNum);

  set highBpm(int? value) => setFieldValue(highBpmFieldNum, value);

  static const int caloriesFieldNum = 2;

  /// calories, in kcal / min.
  double? get calories => doubleFieldValue(caloriesFieldNum);

  set calories(double? value) => setFieldValue(caloriesFieldNum, value);

  static const int fatCaloriesFieldNum = 3;

  /// fat_calories, in kcal / min.
  double? get fatCalories => doubleFieldValue(fatCaloriesFieldNum);

  set fatCalories(double? value) => setFieldValue(fatCaloriesFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[254] =
        Field('message_index', 254, BaseType.uint16, 1.0, 0.0, '', false);
    fields[1] = Field('high_bpm', 1, BaseType.uint8, 1.0, 0.0, '', false);
    fields[2] =
        Field('calories', 2, BaseType.uint16, 10.0, 0.0, 'kcal / min', false);
    fields[3] = Field(
        'fat_calories', 3, BaseType.uint8, 10.0, 0.0, 'kcal / min', false);
    return fields;
  }
}
