/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `monitoring` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class MonitoringMesg extends Mesg {
  MonitoringMesg() : super('monitoring', MesgNum.monitoring);

  /// A deep copy of [mesg] reinterpreted as a `monitoring`.
  MonitoringMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  MonitoringMesg.adopt(super.mesg) : super.adopt();

  static const int timestampFieldNum = 253;

  /// timestamp, in s. Must align to logging interval, for example, time must be 00:00:00 for daily log.
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int deviceIndexFieldNum = 0;

  /// device_index. Associates this data to device_info message. Not required for file with single device (sensor).
  int? get deviceIndex => intFieldValue(deviceIndexFieldNum);

  set deviceIndex(int? value) => setFieldValue(deviceIndexFieldNum, value);

  static const int caloriesFieldNum = 1;

  /// calories, in kcal. Accumulated total calories. Maintained by MonitoringReader for each activity_type. See SDK documentation
  int? get calories => intFieldValue(caloriesFieldNum);

  set calories(int? value) => setFieldValue(caloriesFieldNum, value);

  static const int distanceFieldNum = 2;

  /// distance, in m. Accumulated distance. Maintained by MonitoringReader for each activity_type. See SDK documentation.
  double? get distance => doubleFieldValue(distanceFieldNum);

  set distance(double? value) => setFieldValue(distanceFieldNum, value);

  static const int cyclesFieldNum = 3;

  /// cycles, in cycles. Accumulated cycles. Maintained by MonitoringReader for each activity_type. See SDK documentation.
  double? get cycles => doubleFieldValue(cyclesFieldNum);

  set cycles(double? value) => setFieldValue(cyclesFieldNum, value);

  /// steps: what cycles means when this message selects it.
  int? get steps =>
      intFieldValue(cyclesFieldNum, 0, const NamedSelector('steps'));

  void setSteps(int? value) =>
      setFieldValue(cyclesFieldNum, value, 0, const NamedSelector('steps'));

  /// strokes: what cycles means when this message selects it.
  double? get strokes =>
      doubleFieldValue(cyclesFieldNum, 0, const NamedSelector('strokes'));

  void setStrokes(double? value) =>
      setFieldValue(cyclesFieldNum, value, 0, const NamedSelector('strokes'));

  static const int activeTimeFieldNum = 4;

  /// active_time, in s.
  double? get activeTime => doubleFieldValue(activeTimeFieldNum);

  set activeTime(double? value) => setFieldValue(activeTimeFieldNum, value);

  static const int activityTypeFieldNum = 5;

  /// activity_type.
  ActivityType? get activityType {
    final value = intFieldValue(activityTypeFieldNum);
    return value == null ? null : ActivityType.fromValue(value);
  }

  set activityType(ActivityType? value) =>
      setFieldValue(activityTypeFieldNum, value?.value);

  static const int activitySubtypeFieldNum = 6;

  /// activity_subtype.
  ActivitySubtype? get activitySubtype {
    final value = intFieldValue(activitySubtypeFieldNum);
    return value == null ? null : ActivitySubtype.fromValue(value);
  }

  set activitySubtype(ActivitySubtype? value) =>
      setFieldValue(activitySubtypeFieldNum, value?.value);

  static const int activityLevelFieldNum = 7;

  /// activity_level.
  ActivityLevel? get activityLevel {
    final value = intFieldValue(activityLevelFieldNum);
    return value == null ? null : ActivityLevel.fromValue(value);
  }

  set activityLevel(ActivityLevel? value) =>
      setFieldValue(activityLevelFieldNum, value?.value);

  static const int distance16FieldNum = 8;

  /// distance_16, in 100 * m.
  int? get distance16 => intFieldValue(distance16FieldNum);

  set distance16(int? value) => setFieldValue(distance16FieldNum, value);

  static const int cycles16FieldNum = 9;

  /// cycles_16, in 2 * cycles (steps).
  int? get cycles16 => intFieldValue(cycles16FieldNum);

  set cycles16(int? value) => setFieldValue(cycles16FieldNum, value);

  static const int activeTime16FieldNum = 10;

  /// active_time_16, in s.
  int? get activeTime16 => intFieldValue(activeTime16FieldNum);

  set activeTime16(int? value) => setFieldValue(activeTime16FieldNum, value);

  static const int localTimestampFieldNum = 11;

  /// local_timestamp. Must align to logging interval, for example, time must be 00:00:00 for daily log.
  DateTime? get localTimestamp {
    final value = intFieldValue(localTimestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set localTimestamp(DateTime? value) => setFieldValue(localTimestampFieldNum,
      value == null ? null : FitDateTime.toTimestamp(value));

  static const int temperatureFieldNum = 12;

  /// temperature, in C. Avg temperature during the logging interval ended at timestamp
  double? get temperature => doubleFieldValue(temperatureFieldNum);

  set temperature(double? value) => setFieldValue(temperatureFieldNum, value);

  static const int temperatureMinFieldNum = 14;

  /// temperature_min, in C. Min temperature during the logging interval ended at timestamp
  double? get temperatureMin => doubleFieldValue(temperatureMinFieldNum);

  set temperatureMin(double? value) =>
      setFieldValue(temperatureMinFieldNum, value);

  static const int temperatureMaxFieldNum = 15;

  /// temperature_max, in C. Max temperature during the logging interval ended at timestamp
  double? get temperatureMax => doubleFieldValue(temperatureMaxFieldNum);

  set temperatureMax(double? value) =>
      setFieldValue(temperatureMaxFieldNum, value);

  static const int activityTimeFieldNum = 16;

  /// Number of values stored in activity_time.
  int get numActivityTime => getField(activityTimeFieldNum)?.numValues ?? 0;

  /// activity_time, in minutes. Indexed using minute_activity_level enum
  List<int?>? get activityTime {
    final field = getField(activityTimeFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getActivityTime);
  }

  set activityTime(List<int?>? value) {
    removeField(activityTimeFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setActivityTime(index, value[index]);
    }
  }

  int? getActivityTime(int index) => intFieldValue(activityTimeFieldNum, index);

  void setActivityTime(int index, int? value) =>
      setFieldValue(activityTimeFieldNum, value, index);

  static const int activeCaloriesFieldNum = 19;

  /// active_calories, in kcal.
  int? get activeCalories => intFieldValue(activeCaloriesFieldNum);

  set activeCalories(int? value) =>
      setFieldValue(activeCaloriesFieldNum, value);

  static const int currentActivityTypeIntensityFieldNum = 24;

  /// current_activity_type_intensity. Indicates single type / intensity for duration since last monitoring message.
  int? get currentActivityTypeIntensity =>
      intFieldValue(currentActivityTypeIntensityFieldNum);

  set currentActivityTypeIntensity(int? value) =>
      setFieldValue(currentActivityTypeIntensityFieldNum, value);

  static const int timestampMin8FieldNum = 25;

  /// timestamp_min_8, in min.
  int? get timestampMin8 => intFieldValue(timestampMin8FieldNum);

  set timestampMin8(int? value) => setFieldValue(timestampMin8FieldNum, value);

  static const int timestamp16FieldNum = 26;

  /// timestamp_16, in s.
  int? get timestamp16 => intFieldValue(timestamp16FieldNum);

  set timestamp16(int? value) => setFieldValue(timestamp16FieldNum, value);

  static const int heartRateFieldNum = 27;

  /// heart_rate, in bpm.
  int? get heartRate => intFieldValue(heartRateFieldNum);

  set heartRate(int? value) => setFieldValue(heartRateFieldNum, value);

  static const int intensityFieldNum = 28;

  /// intensity.
  double? get intensity => doubleFieldValue(intensityFieldNum);

  set intensity(double? value) => setFieldValue(intensityFieldNum, value);

  static const int durationMinFieldNum = 29;

  /// duration_min, in min.
  int? get durationMin => intFieldValue(durationMinFieldNum);

  set durationMin(int? value) => setFieldValue(durationMinFieldNum, value);

  static const int durationFieldNum = 30;

  /// duration, in s.
  int? get duration => intFieldValue(durationFieldNum);

  set duration(int? value) => setFieldValue(durationFieldNum, value);

  static const int ascentFieldNum = 31;

  /// ascent, in m.
  double? get ascent => doubleFieldValue(ascentFieldNum);

  set ascent(double? value) => setFieldValue(ascentFieldNum, value);

  static const int descentFieldNum = 32;

  /// descent, in m.
  double? get descent => doubleFieldValue(descentFieldNum);

  set descent(double? value) => setFieldValue(descentFieldNum, value);

  static const int moderateActivityMinutesFieldNum = 33;

  /// moderate_activity_minutes, in minutes.
  int? get moderateActivityMinutes =>
      intFieldValue(moderateActivityMinutesFieldNum);

  set moderateActivityMinutes(int? value) =>
      setFieldValue(moderateActivityMinutesFieldNum, value);

  static const int vigorousActivityMinutesFieldNum = 34;

  /// vigorous_activity_minutes, in minutes.
  int? get vigorousActivityMinutes =>
      intFieldValue(vigorousActivityMinutesFieldNum);

  set vigorousActivityMinutes(int? value) =>
      setFieldValue(vigorousActivityMinutesFieldNum, value);

  static const int pushesFieldNum = 41;

  /// pushes. Wheelchair Pushes
  int? get pushes => intFieldValue(pushesFieldNum);

  set pushes(int? value) => setFieldValue(pushesFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[253] =
        Field('timestamp', 253, BaseType.uint32, 1.0, 0.0, 's', false);
    fields[0] = Field('device_index', 0, BaseType.uint8, 1.0, 0.0, '', false);
    fields[1] = Field('calories', 1, BaseType.uint16, 1.0, 0.0, 'kcal', false);
    fields[2] = Field('distance', 2, BaseType.uint32, 100.0, 0.0, 'm', false);
    fields[3] = Field('cycles', 3, BaseType.uint32, 2.0, 0.0, 'cycles', false)
      ..addSubField(SubField('steps', BaseType.uint32, 1.0, 0.0, 'steps')
        ..addMap(5, 6)
        ..addMap(5, 1))
      ..addSubField(SubField('strokes', BaseType.uint32, 2.0, 0.0, 'strokes')
        ..addMap(5, 2)
        ..addMap(5, 5));
    fields[4] =
        Field('active_time', 4, BaseType.uint32, 1000.0, 0.0, 's', false);
    fields[5] =
        Field('activity_type', 5, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[6] =
        Field('activity_subtype', 6, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[7] =
        Field('activity_level', 7, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[8] =
        Field('distance_16', 8, BaseType.uint16, 1.0, 0.0, '100 * m', false);
    fields[9] = Field(
        'cycles_16', 9, BaseType.uint16, 1.0, 0.0, '2 * cycles (steps)', false);
    fields[10] =
        Field('active_time_16', 10, BaseType.uint16, 1.0, 0.0, 's', false);
    fields[11] =
        Field('local_timestamp', 11, BaseType.uint32, 1.0, 0.0, '', false);
    fields[12] =
        Field('temperature', 12, BaseType.sint16, 100.0, 0.0, 'C', false);
    fields[14] =
        Field('temperature_min', 14, BaseType.sint16, 100.0, 0.0, 'C', false);
    fields[15] =
        Field('temperature_max', 15, BaseType.sint16, 100.0, 0.0, 'C', false);
    fields[16] =
        Field('activity_time', 16, BaseType.uint16, 1.0, 0.0, 'minutes', false);
    fields[19] =
        Field('active_calories', 19, BaseType.uint16, 1.0, 0.0, 'kcal', false);
    fields[24] = Field('current_activity_type_intensity', 24, BaseType.byte,
        1.0, 0.0, '', false)
      ..addComponent(const FieldComponent(5, false, 5, 1.0, 0.0))
      ..addComponent(const FieldComponent(28, false, 3, 1.0, 0.0));
    fields[25] =
        Field('timestamp_min_8', 25, BaseType.uint8, 1.0, 0.0, 'min', false);
    fields[26] =
        Field('timestamp_16', 26, BaseType.uint16, 1.0, 0.0, 's', false);
    fields[27] =
        Field('heart_rate', 27, BaseType.uint8, 1.0, 0.0, 'bpm', false);
    fields[28] = Field('intensity', 28, BaseType.uint8, 10.0, 0.0, '', false);
    fields[29] =
        Field('duration_min', 29, BaseType.uint16, 1.0, 0.0, 'min', false);
    fields[30] = Field('duration', 30, BaseType.uint32, 1.0, 0.0, 's', false);
    fields[31] = Field('ascent', 31, BaseType.uint32, 1000.0, 0.0, 'm', false);
    fields[32] = Field('descent', 32, BaseType.uint32, 1000.0, 0.0, 'm', false);
    fields[33] = Field('moderate_activity_minutes', 33, BaseType.uint16, 1.0,
        0.0, 'minutes', false);
    fields[34] = Field('vigorous_activity_minutes', 34, BaseType.uint16, 1.0,
        0.0, 'minutes', false);
    fields[41] = Field('pushes', 41, BaseType.uint32, 1.0, 0.0, '', false);
    return fields;
  }
}
