/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `monitoring_info` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class MonitoringInfoMesg extends Mesg {
  MonitoringInfoMesg() : super('monitoring_info', MesgNum.monitoringInfo);

  /// A deep copy of [mesg] reinterpreted as a `monitoring_info`.
  MonitoringInfoMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  MonitoringInfoMesg.adopt(super.mesg) : super.adopt();

  static const int timestampFieldNum = 253;

  /// timestamp, in s.
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int localTimestampFieldNum = 0;

  /// local_timestamp, in s. Use to convert activity timestamps to local time if device does not support time zone and daylight savings time correction.
  DateTime? get localTimestamp {
    final value = intFieldValue(localTimestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set localTimestamp(DateTime? value) => setFieldValue(localTimestampFieldNum,
      value == null ? null : FitDateTime.toTimestamp(value));

  static const int activityTypeFieldNum = 1;

  /// Number of values stored in activity_type.
  int get numActivityType => getField(activityTypeFieldNum)?.numValues ?? 0;

  /// activity_type.
  List<ActivityType?>? get activityType {
    final field = getField(activityTypeFieldNum);
    if (field == null) return null;
    return List<ActivityType?>.generate(field.numValues, getActivityType);
  }

  set activityType(List<ActivityType?>? value) {
    removeField(activityTypeFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setActivityType(index, value[index]);
    }
  }

  ActivityType? getActivityType(int index) {
    final value = intFieldValue(activityTypeFieldNum, index);
    return value == null ? null : ActivityType.fromValue(value);
  }

  void setActivityType(int index, ActivityType? value) =>
      setFieldValue(activityTypeFieldNum, value?.value, index);

  static const int cyclesToDistanceFieldNum = 3;

  /// Number of values stored in cycles_to_distance.
  int get numCyclesToDistance =>
      getField(cyclesToDistanceFieldNum)?.numValues ?? 0;

  /// cycles_to_distance, in m/cycle. Indexed by activity_type
  List<double?>? get cyclesToDistance {
    final field = getField(cyclesToDistanceFieldNum);
    if (field == null) return null;
    return List<double?>.generate(field.numValues, getCyclesToDistance);
  }

  set cyclesToDistance(List<double?>? value) {
    removeField(cyclesToDistanceFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setCyclesToDistance(index, value[index]);
    }
  }

  double? getCyclesToDistance(int index) =>
      doubleFieldValue(cyclesToDistanceFieldNum, index);

  void setCyclesToDistance(int index, double? value) =>
      setFieldValue(cyclesToDistanceFieldNum, value, index);

  static const int cyclesToCaloriesFieldNum = 4;

  /// Number of values stored in cycles_to_calories.
  int get numCyclesToCalories =>
      getField(cyclesToCaloriesFieldNum)?.numValues ?? 0;

  /// cycles_to_calories, in kcal/cycle. Indexed by activity_type
  List<double?>? get cyclesToCalories {
    final field = getField(cyclesToCaloriesFieldNum);
    if (field == null) return null;
    return List<double?>.generate(field.numValues, getCyclesToCalories);
  }

  set cyclesToCalories(List<double?>? value) {
    removeField(cyclesToCaloriesFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setCyclesToCalories(index, value[index]);
    }
  }

  double? getCyclesToCalories(int index) =>
      doubleFieldValue(cyclesToCaloriesFieldNum, index);

  void setCyclesToCalories(int index, double? value) =>
      setFieldValue(cyclesToCaloriesFieldNum, value, index);

  static const int restingMetabolicRateFieldNum = 5;

  /// resting_metabolic_rate, in kcal / day.
  int? get restingMetabolicRate => intFieldValue(restingMetabolicRateFieldNum);

  set restingMetabolicRate(int? value) =>
      setFieldValue(restingMetabolicRateFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[253] =
        Field('timestamp', 253, BaseType.uint32, 1.0, 0.0, 's', false);
    fields[0] =
        Field('local_timestamp', 0, BaseType.uint32, 1.0, 0.0, 's', false);
    fields[1] =
        Field('activity_type', 1, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[3] = Field('cycles_to_distance', 3, BaseType.uint16, 5000.0, 0.0,
        'm/cycle', false);
    fields[4] = Field('cycles_to_calories', 4, BaseType.uint16, 5000.0, 0.0,
        'kcal/cycle', false);
    fields[5] = Field('resting_metabolic_rate', 5, BaseType.uint16, 1.0, 0.0,
        'kcal / day', false);
    return fields;
  }
}
