/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `segment_file` message.
///
/// Summary of the unique segment and leaderboard information associated with a segment file. This message is used to compile a segment list file describing all segment files on a device. The segment list file is used when refreshing the contents of a segment file with the latest available leaderboard information.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class SegmentFileMesg extends Mesg {
  SegmentFileMesg() : super('segment_file', MesgNum.segmentFile);

  /// A deep copy of [mesg] reinterpreted as a `segment_file`.
  SegmentFileMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  SegmentFileMesg.adopt(super.mesg) : super.adopt();

  static const int messageIndexFieldNum = 254;

  /// message_index.
  int? get messageIndex => intFieldValue(messageIndexFieldNum);

  set messageIndex(int? value) => setFieldValue(messageIndexFieldNum, value);

  static const int fileUuidFieldNum = 1;

  /// file_uuid. UUID of the segment file
  String? get fileUuid => stringFieldValue(fileUuidFieldNum);

  set fileUuid(String? value) => setFieldValue(fileUuidFieldNum, value);

  static const int enabledFieldNum = 3;

  /// enabled. Enabled state of the segment file
  bool? get enabled {
    final value = intFieldValue(enabledFieldNum);
    return value == null ? null : value != 0;
  }

  set enabled(bool? value) =>
      setFieldValue(enabledFieldNum, value == null ? null : (value ? 1 : 0));

  static const int userProfilePrimaryKeyFieldNum = 4;

  /// user_profile_primary_key. Primary key of the user that created the segment file
  int? get userProfilePrimaryKey =>
      intFieldValue(userProfilePrimaryKeyFieldNum);

  set userProfilePrimaryKey(int? value) =>
      setFieldValue(userProfilePrimaryKeyFieldNum, value);

  static const int leaderTypeFieldNum = 7;

  /// Number of values stored in leader_type.
  int get numLeaderType => getField(leaderTypeFieldNum)?.numValues ?? 0;

  /// leader_type. Leader type of each leader in the segment file
  List<SegmentLeaderboardType?>? get leaderType {
    final field = getField(leaderTypeFieldNum);
    if (field == null) return null;
    return List<SegmentLeaderboardType?>.generate(
        field.numValues, getLeaderType);
  }

  set leaderType(List<SegmentLeaderboardType?>? value) {
    removeField(leaderTypeFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setLeaderType(index, value[index]);
    }
  }

  SegmentLeaderboardType? getLeaderType(int index) {
    final value = intFieldValue(leaderTypeFieldNum, index);
    return value == null ? null : SegmentLeaderboardType.fromValue(value);
  }

  void setLeaderType(int index, SegmentLeaderboardType? value) =>
      setFieldValue(leaderTypeFieldNum, value?.value, index);

  static const int leaderGroupPrimaryKeyFieldNum = 8;

  /// Number of values stored in leader_group_primary_key.
  int get numLeaderGroupPrimaryKey =>
      getField(leaderGroupPrimaryKeyFieldNum)?.numValues ?? 0;

  /// leader_group_primary_key. Group primary key of each leader in the segment file
  List<int?>? get leaderGroupPrimaryKey {
    final field = getField(leaderGroupPrimaryKeyFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getLeaderGroupPrimaryKey);
  }

  set leaderGroupPrimaryKey(List<int?>? value) {
    removeField(leaderGroupPrimaryKeyFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setLeaderGroupPrimaryKey(index, value[index]);
    }
  }

  int? getLeaderGroupPrimaryKey(int index) =>
      intFieldValue(leaderGroupPrimaryKeyFieldNum, index);

  void setLeaderGroupPrimaryKey(int index, int? value) =>
      setFieldValue(leaderGroupPrimaryKeyFieldNum, value, index);

  static const int leaderActivityIdFieldNum = 9;

  /// Number of values stored in leader_activity_id.
  int get numLeaderActivityId =>
      getField(leaderActivityIdFieldNum)?.numValues ?? 0;

  /// leader_activity_id. Activity ID of each leader in the segment file
  List<int?>? get leaderActivityId {
    final field = getField(leaderActivityIdFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getLeaderActivityId);
  }

  set leaderActivityId(List<int?>? value) {
    removeField(leaderActivityIdFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setLeaderActivityId(index, value[index]);
    }
  }

  int? getLeaderActivityId(int index) =>
      intFieldValue(leaderActivityIdFieldNum, index);

  void setLeaderActivityId(int index, int? value) =>
      setFieldValue(leaderActivityIdFieldNum, value, index);

  static const int leaderActivityIdStringFieldNum = 10;

  /// Number of values stored in leader_activity_id_string.
  int get numLeaderActivityIdString =>
      getField(leaderActivityIdStringFieldNum)?.numValues ?? 0;

  /// leader_activity_id_string. String version of the activity ID of each leader in the segment file. 21 characters long for each ID, express in decimal
  List<String?>? get leaderActivityIdString {
    final field = getField(leaderActivityIdStringFieldNum);
    if (field == null) return null;
    return List<String?>.generate(field.numValues, getLeaderActivityIdString);
  }

  set leaderActivityIdString(List<String?>? value) {
    removeField(leaderActivityIdStringFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setLeaderActivityIdString(index, value[index]);
    }
  }

  String? getLeaderActivityIdString(int index) =>
      stringFieldValue(leaderActivityIdStringFieldNum, index);

  void setLeaderActivityIdString(int index, String? value) =>
      setFieldValue(leaderActivityIdStringFieldNum, value, index);

  static const int defaultRaceLeaderFieldNum = 11;

  /// default_race_leader. Index for the Leader Board entry selected as the default race participant
  int? get defaultRaceLeader => intFieldValue(defaultRaceLeaderFieldNum);

  set defaultRaceLeader(int? value) =>
      setFieldValue(defaultRaceLeaderFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[254] =
        Field('message_index', 254, BaseType.uint16, 1.0, 0.0, '', false);
    fields[1] = Field('file_uuid', 1, BaseType.string, 1.0, 0.0, '', false);
    fields[3] = Field('enabled', 3, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[4] = Field(
        'user_profile_primary_key', 4, BaseType.uint32, 1.0, 0.0, '', false);
    fields[7] = Field('leader_type', 7, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[8] = Field(
        'leader_group_primary_key', 8, BaseType.uint32, 1.0, 0.0, '', false);
    fields[9] =
        Field('leader_activity_id', 9, BaseType.uint32, 1.0, 0.0, '', false);
    fields[10] = Field(
        'leader_activity_id_string', 10, BaseType.string, 1.0, 0.0, '', false);
    fields[11] =
        Field('default_race_leader', 11, BaseType.uint8, 1.0, 0.0, '', false);
    return fields;
  }
}
