/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `slave_device` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class SlaveDeviceMesg extends Mesg {
  SlaveDeviceMesg() : super('slave_device', MesgNum.slaveDevice);

  /// A deep copy of [mesg] reinterpreted as a `slave_device`.
  SlaveDeviceMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  SlaveDeviceMesg.adopt(super.mesg) : super.adopt();

  static const int manufacturerFieldNum = 0;

  /// manufacturer.
  Manufacturer? get manufacturer {
    final value = intFieldValue(manufacturerFieldNum);
    return value == null ? null : Manufacturer.fromValue(value);
  }

  set manufacturer(Manufacturer? value) =>
      setFieldValue(manufacturerFieldNum, value?.value);

  static const int productFieldNum = 1;

  /// product.
  int? get product => intFieldValue(productFieldNum);

  set product(int? value) => setFieldValue(productFieldNum, value);

  /// favero_product: what product means when this message selects it.
  FaveroProduct? get faveroProduct {
    final value = intFieldValue(
        productFieldNum, 0, const NamedSelector('favero_product'));
    return value == null ? null : FaveroProduct.fromValue(value);
  }

  void setFaveroProduct(FaveroProduct? value) => setFieldValue(
      productFieldNum, value?.value, 0, const NamedSelector('favero_product'));

  /// garmin_product: what product means when this message selects it.
  GarminProduct? get garminProduct {
    final value = intFieldValue(
        productFieldNum, 0, const NamedSelector('garmin_product'));
    return value == null ? null : GarminProduct.fromValue(value);
  }

  void setGarminProduct(GarminProduct? value) => setFieldValue(
      productFieldNum, value?.value, 0, const NamedSelector('garmin_product'));

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[0] = Field('manufacturer', 0, BaseType.uint16, 1.0, 0.0, '', false);
    fields[1] = Field('product', 1, BaseType.uint16, 1.0, 0.0, '', false)
      ..addSubField(SubField('favero_product', BaseType.uint16, 1.0, 0.0, '')
        ..addMap(0, 263))
      ..addSubField(SubField('garmin_product', BaseType.uint16, 1.0, 0.0, '')
        ..addMap(0, 1)
        ..addMap(0, 15)
        ..addMap(0, 13)
        ..addMap(0, 89));
    return fields;
  }
}
