/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `sleep_assessment` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class SleepAssessmentMesg extends Mesg {
  SleepAssessmentMesg() : super('sleep_assessment', MesgNum.sleepAssessment);

  /// A deep copy of [mesg] reinterpreted as a `sleep_assessment`.
  SleepAssessmentMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  SleepAssessmentMesg.adopt(super.mesg) : super.adopt();

  static const int combinedAwakeScoreFieldNum = 0;

  /// combined_awake_score. Average of awake_time_score and awakenings_count_score. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
  int? get combinedAwakeScore => intFieldValue(combinedAwakeScoreFieldNum);

  set combinedAwakeScore(int? value) =>
      setFieldValue(combinedAwakeScoreFieldNum, value);

  static const int awakeTimeScoreFieldNum = 1;

  /// awake_time_score. Score that evaluates the total time spent awake between sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
  int? get awakeTimeScore => intFieldValue(awakeTimeScoreFieldNum);

  set awakeTimeScore(int? value) =>
      setFieldValue(awakeTimeScoreFieldNum, value);

  static const int awakeningsCountScoreFieldNum = 2;

  /// awakenings_count_score. Score that evaluates the number of awakenings that interrupt sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
  int? get awakeningsCountScore => intFieldValue(awakeningsCountScoreFieldNum);

  set awakeningsCountScore(int? value) =>
      setFieldValue(awakeningsCountScoreFieldNum, value);

  static const int deepSleepScoreFieldNum = 3;

  /// deep_sleep_score. Score that evaluates the amount of deep sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
  int? get deepSleepScore => intFieldValue(deepSleepScoreFieldNum);

  set deepSleepScore(int? value) =>
      setFieldValue(deepSleepScoreFieldNum, value);

  static const int sleepDurationScoreFieldNum = 4;

  /// sleep_duration_score. Score that evaluates the quality of sleep based on sleep stages, heart-rate variability and possible awakenings during the night. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
  int? get sleepDurationScore => intFieldValue(sleepDurationScoreFieldNum);

  set sleepDurationScore(int? value) =>
      setFieldValue(sleepDurationScoreFieldNum, value);

  static const int lightSleepScoreFieldNum = 5;

  /// light_sleep_score. Score that evaluates the amount of light sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
  int? get lightSleepScore => intFieldValue(lightSleepScoreFieldNum);

  set lightSleepScore(int? value) =>
      setFieldValue(lightSleepScoreFieldNum, value);

  static const int overallSleepScoreFieldNum = 6;

  /// overall_sleep_score. Total score that summarizes the overall quality of sleep, combining sleep duration and quality. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
  int? get overallSleepScore => intFieldValue(overallSleepScoreFieldNum);

  set overallSleepScore(int? value) =>
      setFieldValue(overallSleepScoreFieldNum, value);

  static const int sleepQualityScoreFieldNum = 7;

  /// sleep_quality_score. Score that evaluates the quality of sleep based on sleep stages, heart-rate variability and possible awakenings during the night. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
  int? get sleepQualityScore => intFieldValue(sleepQualityScoreFieldNum);

  set sleepQualityScore(int? value) =>
      setFieldValue(sleepQualityScoreFieldNum, value);

  static const int sleepRecoveryScoreFieldNum = 8;

  /// sleep_recovery_score. Score that evaluates stress and recovery during sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
  int? get sleepRecoveryScore => intFieldValue(sleepRecoveryScoreFieldNum);

  set sleepRecoveryScore(int? value) =>
      setFieldValue(sleepRecoveryScoreFieldNum, value);

  static const int remSleepScoreFieldNum = 9;

  /// rem_sleep_score. Score that evaluates the amount of REM sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
  int? get remSleepScore => intFieldValue(remSleepScoreFieldNum);

  set remSleepScore(int? value) => setFieldValue(remSleepScoreFieldNum, value);

  static const int sleepRestlessnessScoreFieldNum = 10;

  /// sleep_restlessness_score. Score that evaluates the amount of restlessness during sleep. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
  int? get sleepRestlessnessScore =>
      intFieldValue(sleepRestlessnessScoreFieldNum);

  set sleepRestlessnessScore(int? value) =>
      setFieldValue(sleepRestlessnessScoreFieldNum, value);

  static const int awakeningsCountFieldNum = 11;

  /// awakenings_count. The number of awakenings during sleep.
  int? get awakeningsCount => intFieldValue(awakeningsCountFieldNum);

  set awakeningsCount(int? value) =>
      setFieldValue(awakeningsCountFieldNum, value);

  static const int interruptionsScoreFieldNum = 14;

  /// interruptions_score. Score that evaluates the sleep interruptions. If valid: 0 (worst) to 100 (best). If unknown: FIT_UINT8_INVALID.
  int? get interruptionsScore => intFieldValue(interruptionsScoreFieldNum);

  set interruptionsScore(int? value) =>
      setFieldValue(interruptionsScoreFieldNum, value);

  static const int averageStressDuringSleepFieldNum = 15;

  /// average_stress_during_sleep. Excludes stress during awake periods in the sleep window
  double? get averageStressDuringSleep =>
      doubleFieldValue(averageStressDuringSleepFieldNum);

  set averageStressDuringSleep(double? value) =>
      setFieldValue(averageStressDuringSleepFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[0] =
        Field('combined_awake_score', 0, BaseType.uint8, 1.0, 0.0, '', false);
    fields[1] =
        Field('awake_time_score', 1, BaseType.uint8, 1.0, 0.0, '', false);
    fields[2] =
        Field('awakenings_count_score', 2, BaseType.uint8, 1.0, 0.0, '', false);
    fields[3] =
        Field('deep_sleep_score', 3, BaseType.uint8, 1.0, 0.0, '', false);
    fields[4] =
        Field('sleep_duration_score', 4, BaseType.uint8, 1.0, 0.0, '', false);
    fields[5] =
        Field('light_sleep_score', 5, BaseType.uint8, 1.0, 0.0, '', false);
    fields[6] =
        Field('overall_sleep_score', 6, BaseType.uint8, 1.0, 0.0, '', false);
    fields[7] =
        Field('sleep_quality_score', 7, BaseType.uint8, 1.0, 0.0, '', false);
    fields[8] =
        Field('sleep_recovery_score', 8, BaseType.uint8, 1.0, 0.0, '', false);
    fields[9] =
        Field('rem_sleep_score', 9, BaseType.uint8, 1.0, 0.0, '', false);
    fields[10] = Field(
        'sleep_restlessness_score', 10, BaseType.uint8, 1.0, 0.0, '', false);
    fields[11] =
        Field('awakenings_count', 11, BaseType.uint8, 1.0, 0.0, '', false);
    fields[14] =
        Field('interruptions_score', 14, BaseType.uint8, 1.0, 0.0, '', false);
    fields[15] = Field('average_stress_during_sleep', 15, BaseType.uint16,
        100.0, 0.0, '', false);
    return fields;
  }
}
