/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `split_summary` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class SplitSummaryMesg extends Mesg {
  SplitSummaryMesg() : super('split_summary', MesgNum.splitSummary);

  /// A deep copy of [mesg] reinterpreted as a `split_summary`.
  SplitSummaryMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  SplitSummaryMesg.adopt(super.mesg) : super.adopt();

  static const int messageIndexFieldNum = 254;

  /// message_index.
  int? get messageIndex => intFieldValue(messageIndexFieldNum);

  set messageIndex(int? value) => setFieldValue(messageIndexFieldNum, value);

  static const int splitTypeFieldNum = 0;

  /// split_type.
  SplitType? get splitType {
    final value = intFieldValue(splitTypeFieldNum);
    return value == null ? null : SplitType.fromValue(value);
  }

  set splitType(SplitType? value) =>
      setFieldValue(splitTypeFieldNum, value?.value);

  static const int numSplitsFieldNum = 3;

  /// num_splits.
  int? get numSplits => intFieldValue(numSplitsFieldNum);

  set numSplits(int? value) => setFieldValue(numSplitsFieldNum, value);

  static const int totalTimerTimeFieldNum = 4;

  /// total_timer_time, in s.
  double? get totalTimerTime => doubleFieldValue(totalTimerTimeFieldNum);

  set totalTimerTime(double? value) =>
      setFieldValue(totalTimerTimeFieldNum, value);

  static const int totalDistanceFieldNum = 5;

  /// total_distance, in m.
  double? get totalDistance => doubleFieldValue(totalDistanceFieldNum);

  set totalDistance(double? value) =>
      setFieldValue(totalDistanceFieldNum, value);

  static const int avgSpeedFieldNum = 6;

  /// avg_speed, in m/s.
  double? get avgSpeed => doubleFieldValue(avgSpeedFieldNum);

  set avgSpeed(double? value) => setFieldValue(avgSpeedFieldNum, value);

  static const int maxSpeedFieldNum = 7;

  /// max_speed, in m/s.
  double? get maxSpeed => doubleFieldValue(maxSpeedFieldNum);

  set maxSpeed(double? value) => setFieldValue(maxSpeedFieldNum, value);

  static const int totalAscentFieldNum = 8;

  /// total_ascent, in m.
  int? get totalAscent => intFieldValue(totalAscentFieldNum);

  set totalAscent(int? value) => setFieldValue(totalAscentFieldNum, value);

  static const int totalDescentFieldNum = 9;

  /// total_descent, in m.
  int? get totalDescent => intFieldValue(totalDescentFieldNum);

  set totalDescent(int? value) => setFieldValue(totalDescentFieldNum, value);

  static const int avgHeartRateFieldNum = 10;

  /// avg_heart_rate, in bpm.
  int? get avgHeartRate => intFieldValue(avgHeartRateFieldNum);

  set avgHeartRate(int? value) => setFieldValue(avgHeartRateFieldNum, value);

  static const int maxHeartRateFieldNum = 11;

  /// max_heart_rate, in bpm.
  int? get maxHeartRate => intFieldValue(maxHeartRateFieldNum);

  set maxHeartRate(int? value) => setFieldValue(maxHeartRateFieldNum, value);

  static const int avgVertSpeedFieldNum = 12;

  /// avg_vert_speed, in m/s.
  double? get avgVertSpeed => doubleFieldValue(avgVertSpeedFieldNum);

  set avgVertSpeed(double? value) => setFieldValue(avgVertSpeedFieldNum, value);

  static const int totalCaloriesFieldNum = 13;

  /// total_calories, in kcal.
  int? get totalCalories => intFieldValue(totalCaloriesFieldNum);

  set totalCalories(int? value) => setFieldValue(totalCaloriesFieldNum, value);

  static const int activeTimeFieldNum = 65;

  /// active_time, in s. total active time in all split rounds
  double? get activeTime => doubleFieldValue(activeTimeFieldNum);

  set activeTime(double? value) => setFieldValue(activeTimeFieldNum, value);

  static const int totalMovingTimeFieldNum = 77;

  /// total_moving_time, in s.
  double? get totalMovingTime => doubleFieldValue(totalMovingTimeFieldNum);

  set totalMovingTime(double? value) =>
      setFieldValue(totalMovingTimeFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[254] =
        Field('message_index', 254, BaseType.uint16, 1.0, 0.0, '', false);
    fields[0] = Field('split_type', 0, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[3] = Field('num_splits', 3, BaseType.uint16, 1.0, 0.0, '', false);
    fields[4] =
        Field('total_timer_time', 4, BaseType.uint32, 1000.0, 0.0, 's', false);
    fields[5] =
        Field('total_distance', 5, BaseType.uint32, 100.0, 0.0, 'm', false);
    fields[6] =
        Field('avg_speed', 6, BaseType.uint32, 1000.0, 0.0, 'm/s', false);
    fields[7] =
        Field('max_speed', 7, BaseType.uint32, 1000.0, 0.0, 'm/s', false);
    fields[8] = Field('total_ascent', 8, BaseType.uint16, 1.0, 0.0, 'm', false);
    fields[9] =
        Field('total_descent', 9, BaseType.uint16, 1.0, 0.0, 'm', false);
    fields[10] =
        Field('avg_heart_rate', 10, BaseType.uint8, 1.0, 0.0, 'bpm', false);
    fields[11] =
        Field('max_heart_rate', 11, BaseType.uint8, 1.0, 0.0, 'bpm', false);
    fields[12] =
        Field('avg_vert_speed', 12, BaseType.sint32, 1000.0, 0.0, 'm/s', false);
    fields[13] =
        Field('total_calories', 13, BaseType.uint32, 1.0, 0.0, 'kcal', false);
    fields[65] =
        Field('active_time', 65, BaseType.uint32, 1000.0, 0.0, 's', false);
    fields[77] = Field(
        'total_moving_time', 77, BaseType.uint32, 1000.0, 0.0, 's', false);
    return fields;
  }
}
