/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `split_summary` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class SplitSummaryMesg extends Mesg {
  SplitSummaryMesg() : super('split_summary', MesgNum.splitSummary);

  /// A deep copy of [mesg] reinterpreted as a `split_summary`.
  SplitSummaryMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  SplitSummaryMesg.adopt(super.mesg) : super.adopt();

  static const int messageIndexFieldNum = 254;

  /// message_index.
  int? get messageIndex => intFieldValue(messageIndexFieldNum);

  set messageIndex(int? value) => setFieldValue(messageIndexFieldNum, value);

  static const int timestampFieldNum = 253;

  /// timestamp, in s.
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int splitTypeFieldNum = 0;

  /// split_type.
  SplitType? get splitType {
    final value = intFieldValue(splitTypeFieldNum);
    return value == null ? null : SplitType.fromValue(value);
  }

  set splitType(SplitType? value) =>
      setFieldValue(splitTypeFieldNum, value?.value);

  static const int sportFieldNum = 1;

  /// sport.
  Sport? get sport {
    final value = intFieldValue(sportFieldNum);
    return value == null ? null : Sport.fromValue(value);
  }

  set sport(Sport? value) => setFieldValue(sportFieldNum, value?.value);

  static const int subSportFieldNum = 2;

  /// sub_sport.
  SubSport? get subSport {
    final value = intFieldValue(subSportFieldNum);
    return value == null ? null : SubSport.fromValue(value);
  }

  set subSport(SubSport? value) =>
      setFieldValue(subSportFieldNum, value?.value);

  static const int numSplitsFieldNum = 3;

  /// num_splits.
  int? get numSplits => intFieldValue(numSplitsFieldNum);

  set numSplits(int? value) => setFieldValue(numSplitsFieldNum, value);

  static const int totalTimerTimeFieldNum = 4;

  /// total_timer_time, in s.
  double? get totalTimerTime => doubleFieldValue(totalTimerTimeFieldNum);

  set totalTimerTime(double? value) =>
      setFieldValue(totalTimerTimeFieldNum, value);

  static const int totalDistanceFieldNum = 5;

  /// total_distance, in m.
  double? get totalDistance => doubleFieldValue(totalDistanceFieldNum);

  set totalDistance(double? value) =>
      setFieldValue(totalDistanceFieldNum, value);

  static const int avgSpeedFieldNum = 6;

  /// avg_speed, in m/s.
  double? get avgSpeed => doubleFieldValue(avgSpeedFieldNum);

  set avgSpeed(double? value) => setFieldValue(avgSpeedFieldNum, value);

  static const int maxSpeedFieldNum = 7;

  /// max_speed, in m/s.
  double? get maxSpeed => doubleFieldValue(maxSpeedFieldNum);

  set maxSpeed(double? value) => setFieldValue(maxSpeedFieldNum, value);

  static const int totalAscentFieldNum = 8;

  /// total_ascent, in m.
  int? get totalAscent => intFieldValue(totalAscentFieldNum);

  set totalAscent(int? value) => setFieldValue(totalAscentFieldNum, value);

  static const int totalDescentFieldNum = 9;

  /// total_descent, in m.
  int? get totalDescent => intFieldValue(totalDescentFieldNum);

  set totalDescent(int? value) => setFieldValue(totalDescentFieldNum, value);

  static const int avgHeartRateFieldNum = 10;

  /// avg_heart_rate, in bpm.
  int? get avgHeartRate => intFieldValue(avgHeartRateFieldNum);

  set avgHeartRate(int? value) => setFieldValue(avgHeartRateFieldNum, value);

  static const int maxHeartRateFieldNum = 11;

  /// max_heart_rate, in bpm.
  int? get maxHeartRate => intFieldValue(maxHeartRateFieldNum);

  set maxHeartRate(int? value) => setFieldValue(maxHeartRateFieldNum, value);

  static const int avgVertSpeedFieldNum = 12;

  /// avg_vert_speed, in m/s.
  double? get avgVertSpeed => doubleFieldValue(avgVertSpeedFieldNum);

  set avgVertSpeed(double? value) => setFieldValue(avgVertSpeedFieldNum, value);

  static const int totalCaloriesFieldNum = 13;

  /// total_calories, in kcal.
  int? get totalCalories => intFieldValue(totalCaloriesFieldNum);

  set totalCalories(int? value) => setFieldValue(totalCaloriesFieldNum, value);

  static const int avgCadenceFieldNum = 14;

  /// avg_cadence, in rpm.
  double? get avgCadence => doubleFieldValue(avgCadenceFieldNum);

  set avgCadence(double? value) => setFieldValue(avgCadenceFieldNum, value);

  /// avg_running_cadence: what avg_cadence means when this message selects it.
  double? get avgRunningCadence => doubleFieldValue(
      avgCadenceFieldNum, 0, const NamedSelector('avg_running_cadence'));

  void setAvgRunningCadence(double? value) => setFieldValue(
      avgCadenceFieldNum, value, 0, const NamedSelector('avg_running_cadence'));

  /// avg_swimming_cadence: what avg_cadence means when this message selects it.
  double? get avgSwimmingCadence => doubleFieldValue(
      avgCadenceFieldNum, 0, const NamedSelector('avg_swimming_cadence'));

  void setAvgSwimmingCadence(double? value) => setFieldValue(avgCadenceFieldNum,
      value, 0, const NamedSelector('avg_swimming_cadence'));

  /// avg_paddlesport_cadence: what avg_cadence means when this message selects it.
  double? get avgPaddlesportCadence => doubleFieldValue(
      avgCadenceFieldNum, 0, const NamedSelector('avg_paddlesport_cadence'));

  void setAvgPaddlesportCadence(double? value) => setFieldValue(
      avgCadenceFieldNum,
      value,
      0,
      const NamedSelector('avg_paddlesport_cadence'));

  /// avg_push_cadence: what avg_cadence means when this message selects it.
  ///
  /// average pushes per minute in all splits of the type
  int? get avgPushCadence => intFieldValue(
      avgCadenceFieldNum, 0, const NamedSelector('avg_push_cadence'));

  void setAvgPushCadence(int? value) => setFieldValue(
      avgCadenceFieldNum, value, 0, const NamedSelector('avg_push_cadence'));

  static const int maxCadenceFieldNum = 15;

  /// max_cadence, in rpm.
  double? get maxCadence => doubleFieldValue(maxCadenceFieldNum);

  set maxCadence(double? value) => setFieldValue(maxCadenceFieldNum, value);

  /// max_running_cadence: what max_cadence means when this message selects it.
  double? get maxRunningCadence => doubleFieldValue(
      maxCadenceFieldNum, 0, const NamedSelector('max_running_cadence'));

  void setMaxRunningCadence(double? value) => setFieldValue(
      maxCadenceFieldNum, value, 0, const NamedSelector('max_running_cadence'));

  /// max_swimming_cadence: what max_cadence means when this message selects it.
  double? get maxSwimmingCadence => doubleFieldValue(
      maxCadenceFieldNum, 0, const NamedSelector('max_swimming_cadence'));

  void setMaxSwimmingCadence(double? value) => setFieldValue(maxCadenceFieldNum,
      value, 0, const NamedSelector('max_swimming_cadence'));

  /// max_paddlesport_cadence: what max_cadence means when this message selects it.
  double? get maxPaddlesportCadence => doubleFieldValue(
      maxCadenceFieldNum, 0, const NamedSelector('max_paddlesport_cadence'));

  void setMaxPaddlesportCadence(double? value) => setFieldValue(
      maxCadenceFieldNum,
      value,
      0,
      const NamedSelector('max_paddlesport_cadence'));

  /// max_push_cadence: what max_cadence means when this message selects it.
  ///
  /// max pushes per minute in all splits of the type
  int? get maxPushCadence => intFieldValue(
      maxCadenceFieldNum, 0, const NamedSelector('max_push_cadence'));

  void setMaxPushCadence(int? value) => setFieldValue(
      maxCadenceFieldNum, value, 0, const NamedSelector('max_push_cadence'));

  static const int totalCyclesFieldNum = 16;

  /// total_cycles, in cycles.
  int? get totalCycles => intFieldValue(totalCyclesFieldNum);

  set totalCycles(int? value) => setFieldValue(totalCyclesFieldNum, value);

  /// total_strides: what total_cycles means when this message selects it.
  int? get totalStrides => intFieldValue(
      totalCyclesFieldNum, 0, const NamedSelector('total_strides'));

  void setTotalStrides(int? value) => setFieldValue(
      totalCyclesFieldNum, value, 0, const NamedSelector('total_strides'));

  /// total_strokes: what total_cycles means when this message selects it.
  int? get totalStrokes => intFieldValue(
      totalCyclesFieldNum, 0, const NamedSelector('total_strokes'));

  void setTotalStrokes(int? value) => setFieldValue(
      totalCyclesFieldNum, value, 0, const NamedSelector('total_strokes'));

  /// total_reps: what total_cycles means when this message selects it.
  ///
  /// total reps in all splits
  int? get totalReps =>
      intFieldValue(totalCyclesFieldNum, 0, const NamedSelector('total_reps'));

  void setTotalReps(int? value) => setFieldValue(
      totalCyclesFieldNum, value, 0, const NamedSelector('total_reps'));

  /// total_pushes: what total_cycles means when this message selects it.
  ///
  /// total number of pushes in all splits of the type
  int? get totalPushes => intFieldValue(
      totalCyclesFieldNum, 0, const NamedSelector('total_pushes'));

  void setTotalPushes(int? value) => setFieldValue(
      totalCyclesFieldNum, value, 0, const NamedSelector('total_pushes'));

  static const int avgTemperatureFieldNum = 17;

  /// avg_temperature, in C.
  int? get avgTemperature => intFieldValue(avgTemperatureFieldNum);

  set avgTemperature(int? value) =>
      setFieldValue(avgTemperatureFieldNum, value);

  static const int maxTemperatureFieldNum = 18;

  /// max_temperature, in C.
  int? get maxTemperature => intFieldValue(maxTemperatureFieldNum);

  set maxTemperature(int? value) =>
      setFieldValue(maxTemperatureFieldNum, value);

  static const int minTemperatureFieldNum = 19;

  /// min_temperature, in C.
  int? get minTemperature => intFieldValue(minTemperatureFieldNum);

  set minTemperature(int? value) =>
      setFieldValue(minTemperatureFieldNum, value);

  static const int avgVerticalOscillationFieldNum = 20;

  /// avg_vertical_oscillation, in mm.
  double? get avgVerticalOscillation =>
      doubleFieldValue(avgVerticalOscillationFieldNum);

  set avgVerticalOscillation(double? value) =>
      setFieldValue(avgVerticalOscillationFieldNum, value);

  static const int avgVerticalRatioFieldNum = 21;

  /// avg_vertical_ratio, in percent.
  double? get avgVerticalRatio => doubleFieldValue(avgVerticalRatioFieldNum);

  set avgVerticalRatio(double? value) =>
      setFieldValue(avgVerticalRatioFieldNum, value);

  static const int avgStanceTimeFieldNum = 22;

  /// avg_stance_time, in ms.
  double? get avgStanceTime => doubleFieldValue(avgStanceTimeFieldNum);

  set avgStanceTime(double? value) =>
      setFieldValue(avgStanceTimeFieldNum, value);

  static const int avgStanceTimeBalanceFieldNum = 23;

  /// avg_stance_time_balance, in percent.
  double? get avgStanceTimeBalance =>
      doubleFieldValue(avgStanceTimeBalanceFieldNum);

  set avgStanceTimeBalance(double? value) =>
      setFieldValue(avgStanceTimeBalanceFieldNum, value);

  static const int avgStepLengthFieldNum = 24;

  /// avg_step_length, in mm.
  double? get avgStepLength => doubleFieldValue(avgStepLengthFieldNum);

  set avgStepLength(double? value) =>
      setFieldValue(avgStepLengthFieldNum, value);

  static const int avgPowerFieldNum = 25;

  /// avg_power, in watts.
  int? get avgPower => intFieldValue(avgPowerFieldNum);

  set avgPower(int? value) => setFieldValue(avgPowerFieldNum, value);

  static const int maxPowerFieldNum = 26;

  /// max_power, in watts.
  int? get maxPower => intFieldValue(maxPowerFieldNum);

  set maxPower(int? value) => setFieldValue(maxPowerFieldNum, value);

  static const int normalizedPowerFieldNum = 27;

  /// normalized_power, in watts.
  int? get normalizedPower => intFieldValue(normalizedPowerFieldNum);

  set normalizedPower(int? value) =>
      setFieldValue(normalizedPowerFieldNum, value);

  static const int leftRightBalanceFieldNum = 28;

  /// left_right_balance. Total time spent in the standing position
  int? get leftRightBalance => intFieldValue(leftRightBalanceFieldNum);

  set leftRightBalance(int? value) =>
      setFieldValue(leftRightBalanceFieldNum, value);

  static const int timeStandingFieldNum = 29;

  /// time_standing, in s. Average left platform center offset
  double? get timeStanding => doubleFieldValue(timeStandingFieldNum);

  set timeStanding(double? value) => setFieldValue(timeStandingFieldNum, value);

  static const int avgLeftPcoFieldNum = 30;

  /// avg_left_pco, in mm. Average right platform center offset
  int? get avgLeftPco => intFieldValue(avgLeftPcoFieldNum);

  set avgLeftPco(int? value) => setFieldValue(avgLeftPcoFieldNum, value);

  static const int avgRightPcoFieldNum = 31;

  /// avg_right_pco, in mm. Average left power phase angles. Data value indexes defined by power_phase_type.
  int? get avgRightPco => intFieldValue(avgRightPcoFieldNum);

  set avgRightPco(int? value) => setFieldValue(avgRightPcoFieldNum, value);

  static const int avgLeftPowerPhaseFieldNum = 32;

  /// Number of values stored in avg_left_power_phase.
  int get numAvgLeftPowerPhase =>
      getField(avgLeftPowerPhaseFieldNum)?.numValues ?? 0;

  /// avg_left_power_phase, in degrees. Average left power phase peak angles. Data value indexes defined by power_phase_type.
  List<double?>? get avgLeftPowerPhase {
    final field = getField(avgLeftPowerPhaseFieldNum);
    if (field == null) return null;
    return List<double?>.generate(field.numValues, getAvgLeftPowerPhase);
  }

  set avgLeftPowerPhase(List<double?>? value) {
    removeField(avgLeftPowerPhaseFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setAvgLeftPowerPhase(index, value[index]);
    }
  }

  double? getAvgLeftPowerPhase(int index) =>
      doubleFieldValue(avgLeftPowerPhaseFieldNum, index);

  void setAvgLeftPowerPhase(int index, double? value) =>
      setFieldValue(avgLeftPowerPhaseFieldNum, value, index);

  static const int avgLeftPowerPhasePeakFieldNum = 33;

  /// Number of values stored in avg_left_power_phase_peak.
  int get numAvgLeftPowerPhasePeak =>
      getField(avgLeftPowerPhasePeakFieldNum)?.numValues ?? 0;

  /// avg_left_power_phase_peak, in degrees. Average right power phase angles. Data value indexes defined by power_phase_type.
  List<double?>? get avgLeftPowerPhasePeak {
    final field = getField(avgLeftPowerPhasePeakFieldNum);
    if (field == null) return null;
    return List<double?>.generate(field.numValues, getAvgLeftPowerPhasePeak);
  }

  set avgLeftPowerPhasePeak(List<double?>? value) {
    removeField(avgLeftPowerPhasePeakFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setAvgLeftPowerPhasePeak(index, value[index]);
    }
  }

  double? getAvgLeftPowerPhasePeak(int index) =>
      doubleFieldValue(avgLeftPowerPhasePeakFieldNum, index);

  void setAvgLeftPowerPhasePeak(int index, double? value) =>
      setFieldValue(avgLeftPowerPhasePeakFieldNum, value, index);

  static const int avgRightPowerPhaseFieldNum = 34;

  /// Number of values stored in avg_right_power_phase.
  int get numAvgRightPowerPhase =>
      getField(avgRightPowerPhaseFieldNum)?.numValues ?? 0;

  /// avg_right_power_phase, in degrees. Average right power phase peak angles. Data value indexes defined by power_phase_type.
  List<double?>? get avgRightPowerPhase {
    final field = getField(avgRightPowerPhaseFieldNum);
    if (field == null) return null;
    return List<double?>.generate(field.numValues, getAvgRightPowerPhase);
  }

  set avgRightPowerPhase(List<double?>? value) {
    removeField(avgRightPowerPhaseFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setAvgRightPowerPhase(index, value[index]);
    }
  }

  double? getAvgRightPowerPhase(int index) =>
      doubleFieldValue(avgRightPowerPhaseFieldNum, index);

  void setAvgRightPowerPhase(int index, double? value) =>
      setFieldValue(avgRightPowerPhaseFieldNum, value, index);

  static const int avgRightPowerPhasePeakFieldNum = 35;

  /// Number of values stored in avg_right_power_phase_peak.
  int get numAvgRightPowerPhasePeak =>
      getField(avgRightPowerPhasePeakFieldNum)?.numValues ?? 0;

  /// avg_right_power_phase_peak, in degrees. Average power by position. Data value indexes defined by rider_position_type.
  List<double?>? get avgRightPowerPhasePeak {
    final field = getField(avgRightPowerPhasePeakFieldNum);
    if (field == null) return null;
    return List<double?>.generate(field.numValues, getAvgRightPowerPhasePeak);
  }

  set avgRightPowerPhasePeak(List<double?>? value) {
    removeField(avgRightPowerPhasePeakFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setAvgRightPowerPhasePeak(index, value[index]);
    }
  }

  double? getAvgRightPowerPhasePeak(int index) =>
      doubleFieldValue(avgRightPowerPhasePeakFieldNum, index);

  void setAvgRightPowerPhasePeak(int index, double? value) =>
      setFieldValue(avgRightPowerPhasePeakFieldNum, value, index);

  static const int avgPowerPositionFieldNum = 36;

  /// Number of values stored in avg_power_position.
  int get numAvgPowerPosition =>
      getField(avgPowerPositionFieldNum)?.numValues ?? 0;

  /// avg_power_position, in watts. Maximum power by position. Data value indexes defined by rider_position_type.
  List<int?>? get avgPowerPosition {
    final field = getField(avgPowerPositionFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getAvgPowerPosition);
  }

  set avgPowerPosition(List<int?>? value) {
    removeField(avgPowerPositionFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setAvgPowerPosition(index, value[index]);
    }
  }

  int? getAvgPowerPosition(int index) =>
      intFieldValue(avgPowerPositionFieldNum, index);

  void setAvgPowerPosition(int index, int? value) =>
      setFieldValue(avgPowerPositionFieldNum, value, index);

  static const int maxPowerPositionFieldNum = 37;

  /// Number of values stored in max_power_position.
  int get numMaxPowerPosition =>
      getField(maxPowerPositionFieldNum)?.numValues ?? 0;

  /// max_power_position, in watts.
  List<int?>? get maxPowerPosition {
    final field = getField(maxPowerPositionFieldNum);
    if (field == null) return null;
    return List<int?>.generate(field.numValues, getMaxPowerPosition);
  }

  set maxPowerPosition(List<int?>? value) {
    removeField(maxPowerPositionFieldNum);
    if (value == null) return;
    for (var index = 0; index < value.length; index++) {
      setMaxPowerPosition(index, value[index]);
    }
  }

  int? getMaxPowerPosition(int index) =>
      intFieldValue(maxPowerPositionFieldNum, index);

  void setMaxPowerPosition(int index, int? value) =>
      setFieldValue(maxPowerPositionFieldNum, value, index);

  static const int avgLeftTorqueEffectivenessFieldNum = 38;

  /// avg_left_torque_effectiveness, in percent.
  double? get avgLeftTorqueEffectiveness =>
      doubleFieldValue(avgLeftTorqueEffectivenessFieldNum);

  set avgLeftTorqueEffectiveness(double? value) =>
      setFieldValue(avgLeftTorqueEffectivenessFieldNum, value);

  static const int avgRightTorqueEffectivenessFieldNum = 39;

  /// avg_right_torque_effectiveness, in percent.
  double? get avgRightTorqueEffectiveness =>
      doubleFieldValue(avgRightTorqueEffectivenessFieldNum);

  set avgRightTorqueEffectiveness(double? value) =>
      setFieldValue(avgRightTorqueEffectivenessFieldNum, value);

  static const int avgLeftPedalSmoothnessFieldNum = 40;

  /// avg_left_pedal_smoothness, in percent.
  double? get avgLeftPedalSmoothness =>
      doubleFieldValue(avgLeftPedalSmoothnessFieldNum);

  set avgLeftPedalSmoothness(double? value) =>
      setFieldValue(avgLeftPedalSmoothnessFieldNum, value);

  static const int avgRightPedalSmoothnessFieldNum = 41;

  /// avg_right_pedal_smoothness, in percent.
  double? get avgRightPedalSmoothness =>
      doubleFieldValue(avgRightPedalSmoothnessFieldNum);

  set avgRightPedalSmoothness(double? value) =>
      setFieldValue(avgRightPedalSmoothnessFieldNum, value);

  static const int avgCombinedPedalSmoothnessFieldNum = 42;

  /// avg_combined_pedal_smoothness, in percent. The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.
  double? get avgCombinedPedalSmoothness =>
      doubleFieldValue(avgCombinedPedalSmoothnessFieldNum);

  set avgCombinedPedalSmoothness(double? value) =>
      setFieldValue(avgCombinedPedalSmoothnessFieldNum, value);

  static const int avgFlowFieldNum = 43;

  /// avg_flow, in Flow. The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.
  double? get avgFlow => doubleFieldValue(avgFlowFieldNum);

  set avgFlow(double? value) => setFieldValue(avgFlowFieldNum, value);

  static const int totalGritFieldNum = 44;

  /// total_grit, in kGrit.
  double? get totalGrit => doubleFieldValue(totalGritFieldNum);

  set totalGrit(double? value) => setFieldValue(totalGritFieldNum, value);

  static const int swimStrokeFieldNum = 47;

  /// swim_stroke. # of active lengths of swim pool
  SwimStroke? get swimStroke {
    final value = intFieldValue(swimStrokeFieldNum);
    return value == null ? null : SwimStroke.fromValue(value);
  }

  set swimStroke(SwimStroke? value) =>
      setFieldValue(swimStrokeFieldNum, value?.value);

  static const int numActiveLengthsFieldNum = 48;

  /// num_active_lengths, in lengths.
  int? get numActiveLengths => intFieldValue(numActiveLengthsFieldNum);

  set numActiveLengths(int? value) =>
      setFieldValue(numActiveLengthsFieldNum, value);

  static const int avgSwolfFieldNum = 49;

  /// avg_swolf.
  int? get avgSwolf => intFieldValue(avgSwolfFieldNum);

  set avgSwolf(int? value) => setFieldValue(avgSwolfFieldNum, value);

  static const int avgStrokeDistanceFieldNum = 50;

  /// avg_stroke_distance, in m.
  double? get avgStrokeDistance => doubleFieldValue(avgStrokeDistanceFieldNum);

  set avgStrokeDistance(double? value) =>
      setFieldValue(avgStrokeDistanceFieldNum, value);

  static const int avgStrokesPerLengthFieldNum = 51;

  /// avg_strokes_per_length, in strokes / length.
  double? get avgStrokesPerLength =>
      doubleFieldValue(avgStrokesPerLengthFieldNum);

  set avgStrokesPerLength(double? value) =>
      setFieldValue(avgStrokesPerLengthFieldNum, value);

  static const int avgAscentFieldNum = 52;

  /// avg_ascent, in m.
  int? get avgAscent => intFieldValue(avgAscentFieldNum);

  set avgAscent(int? value) => setFieldValue(avgAscentFieldNum, value);

  static const int maxAscentFieldNum = 53;

  /// max_ascent, in m.
  int? get maxAscent => intFieldValue(maxAscentFieldNum);

  set maxAscent(int? value) => setFieldValue(maxAscentFieldNum, value);

  static const int climbGradingScaleFieldNum = 54;

  /// climb_grading_scale.
  ClimbGradingScale? get climbGradingScale {
    final value = intFieldValue(climbGradingScaleFieldNum);
    return value == null ? null : ClimbGradingScale.fromValue(value);
  }

  set climbGradingScale(ClimbGradingScale? value) =>
      setFieldValue(climbGradingScaleFieldNum, value?.value);

  static const int climbMaxGradeValueFieldNum = 55;

  /// climb_max_grade_value.
  int? get climbMaxGradeValue => intFieldValue(climbMaxGradeValueFieldNum);

  set climbMaxGradeValue(int? value) =>
      setFieldValue(climbMaxGradeValueFieldNum, value);

  /// climb_max_grade_yds: what climb_max_grade_value means when this message selects it.
  YdsGradingScale? get climbMaxGradeYds {
    final value = intFieldValue(climbMaxGradeValueFieldNum, 0,
        const NamedSelector('climb_max_grade_yds'));
    return value == null ? null : YdsGradingScale.fromValue(value);
  }

  void setClimbMaxGradeYds(YdsGradingScale? value) => setFieldValue(
      climbMaxGradeValueFieldNum,
      value?.value,
      0,
      const NamedSelector('climb_max_grade_yds'));

  /// climb_max_grade_uiaa: what climb_max_grade_value means when this message selects it.
  UiaaGradingScale? get climbMaxGradeUiaa {
    final value = intFieldValue(climbMaxGradeValueFieldNum, 0,
        const NamedSelector('climb_max_grade_uiaa'));
    return value == null ? null : UiaaGradingScale.fromValue(value);
  }

  void setClimbMaxGradeUiaa(UiaaGradingScale? value) => setFieldValue(
      climbMaxGradeValueFieldNum,
      value?.value,
      0,
      const NamedSelector('climb_max_grade_uiaa'));

  /// climb_max_grade_french: what climb_max_grade_value means when this message selects it.
  FrenchGradingScale? get climbMaxGradeFrench {
    final value = intFieldValue(climbMaxGradeValueFieldNum, 0,
        const NamedSelector('climb_max_grade_french'));
    return value == null ? null : FrenchGradingScale.fromValue(value);
  }

  void setClimbMaxGradeFrench(FrenchGradingScale? value) => setFieldValue(
      climbMaxGradeValueFieldNum,
      value?.value,
      0,
      const NamedSelector('climb_max_grade_french'));

  /// climb_max_grade_british_adjectival: what climb_max_grade_value means when this message selects it.
  BritishAdjectivalGradingScale? get climbMaxGradeBritishAdjectival {
    final value = intFieldValue(climbMaxGradeValueFieldNum, 0,
        const NamedSelector('climb_max_grade_british_adjectival'));
    return value == null
        ? null
        : BritishAdjectivalGradingScale.fromValue(value);
  }

  void setClimbMaxGradeBritishAdjectival(
          BritishAdjectivalGradingScale? value) =>
      setFieldValue(climbMaxGradeValueFieldNum, value?.value, 0,
          const NamedSelector('climb_max_grade_british_adjectival'));

  /// climb_max_grade_british_technical: what climb_max_grade_value means when this message selects it.
  BritishTechnicalGradingScale? get climbMaxGradeBritishTechnical {
    final value = intFieldValue(climbMaxGradeValueFieldNum, 0,
        const NamedSelector('climb_max_grade_british_technical'));
    return value == null ? null : BritishTechnicalGradingScale.fromValue(value);
  }

  void setClimbMaxGradeBritishTechnical(BritishTechnicalGradingScale? value) =>
      setFieldValue(climbMaxGradeValueFieldNum, value?.value, 0,
          const NamedSelector('climb_max_grade_british_technical'));

  /// climb_max_grade_ewbank: what climb_max_grade_value means when this message selects it.
  EwbankGradingScale? get climbMaxGradeEwbank {
    final value = intFieldValue(climbMaxGradeValueFieldNum, 0,
        const NamedSelector('climb_max_grade_ewbank'));
    return value == null ? null : EwbankGradingScale.fromValue(value);
  }

  void setClimbMaxGradeEwbank(EwbankGradingScale? value) => setFieldValue(
      climbMaxGradeValueFieldNum,
      value?.value,
      0,
      const NamedSelector('climb_max_grade_ewbank'));

  /// climb_max_grade_brazilian: what climb_max_grade_value means when this message selects it.
  BrazilianGradingScale? get climbMaxGradeBrazilian {
    final value = intFieldValue(climbMaxGradeValueFieldNum, 0,
        const NamedSelector('climb_max_grade_brazilian'));
    return value == null ? null : BrazilianGradingScale.fromValue(value);
  }

  void setClimbMaxGradeBrazilian(BrazilianGradingScale? value) => setFieldValue(
      climbMaxGradeValueFieldNum,
      value?.value,
      0,
      const NamedSelector('climb_max_grade_brazilian'));

  /// climb_max_grade_saxon: what climb_max_grade_value means when this message selects it.
  SaxonGradingScale? get climbMaxGradeSaxon {
    final value = intFieldValue(climbMaxGradeValueFieldNum, 0,
        const NamedSelector('climb_max_grade_saxon'));
    return value == null ? null : SaxonGradingScale.fromValue(value);
  }

  void setClimbMaxGradeSaxon(SaxonGradingScale? value) => setFieldValue(
      climbMaxGradeValueFieldNum,
      value?.value,
      0,
      const NamedSelector('climb_max_grade_saxon'));

  /// climb_max_grade_vermin: what climb_max_grade_value means when this message selects it.
  VerminGradingScale? get climbMaxGradeVermin {
    final value = intFieldValue(climbMaxGradeValueFieldNum, 0,
        const NamedSelector('climb_max_grade_vermin'));
    return value == null ? null : VerminGradingScale.fromValue(value);
  }

  void setClimbMaxGradeVermin(VerminGradingScale? value) => setFieldValue(
      climbMaxGradeValueFieldNum,
      value?.value,
      0,
      const NamedSelector('climb_max_grade_vermin'));

  /// climb_max_grade_font: what climb_max_grade_value means when this message selects it.
  FontGradingScale? get climbMaxGradeFont {
    final value = intFieldValue(climbMaxGradeValueFieldNum, 0,
        const NamedSelector('climb_max_grade_font'));
    return value == null ? null : FontGradingScale.fromValue(value);
  }

  void setClimbMaxGradeFont(FontGradingScale? value) => setFieldValue(
      climbMaxGradeValueFieldNum,
      value?.value,
      0,
      const NamedSelector('climb_max_grade_font'));

  /// climb_max_grade_dankyu: what climb_max_grade_value means when this message selects it.
  DankyuGradingScale? get climbMaxGradeDankyu {
    final value = intFieldValue(climbMaxGradeValueFieldNum, 0,
        const NamedSelector('climb_max_grade_dankyu'));
    return value == null ? null : DankyuGradingScale.fromValue(value);
  }

  void setClimbMaxGradeDankyu(DankyuGradingScale? value) => setFieldValue(
      climbMaxGradeValueFieldNum,
      value?.value,
      0,
      const NamedSelector('climb_max_grade_dankyu'));

  static const int numFallsFieldNum = 56;

  /// num_falls.
  int? get numFalls => intFieldValue(numFallsFieldNum);

  set numFalls(int? value) => setFieldValue(numFallsFieldNum, value);

  static const int numClimbsAttemptedFieldNum = 58;

  /// num_climbs_attempted.
  int? get numClimbsAttempted => intFieldValue(numClimbsAttemptedFieldNum);

  set numClimbsAttempted(int? value) =>
      setFieldValue(numClimbsAttemptedFieldNum, value);

  static const int numClimbsCompletedFieldNum = 59;

  /// num_climbs_completed.
  int? get numClimbsCompleted => intFieldValue(numClimbsCompletedFieldNum);

  set numClimbsCompleted(int? value) =>
      setFieldValue(numClimbsCompletedFieldNum, value);

  static const int maxDistanceFieldNum = 60;

  /// max_distance, in m. Distance of the longest split
  double? get maxDistance => doubleFieldValue(maxDistanceFieldNum);

  set maxDistance(double? value) => setFieldValue(maxDistanceFieldNum, value);

  static const int metabolicCaloriesFieldNum = 64;

  /// metabolic_calories, in kcal.
  int? get metabolicCalories => intFieldValue(metabolicCaloriesFieldNum);

  set metabolicCalories(int? value) =>
      setFieldValue(metabolicCaloriesFieldNum, value);

  static const int activeTimeFieldNum = 65;

  /// active_time, in s. total active time in all split rounds
  double? get activeTime => doubleFieldValue(activeTimeFieldNum);

  set activeTime(double? value) => setFieldValue(activeTimeFieldNum, value);

  static const int totalFractionalAscentFieldNum = 66;

  /// total_fractional_ascent, in m. fractional part of total_ascent
  double? get totalFractionalAscent =>
      doubleFieldValue(totalFractionalAscentFieldNum);

  set totalFractionalAscent(double? value) =>
      setFieldValue(totalFractionalAscentFieldNum, value);

  static const int totalFractionalDescentFieldNum = 67;

  /// total_fractional_descent, in m. fractional part of total_descent
  double? get totalFractionalDescent =>
      doubleFieldValue(totalFractionalDescentFieldNum);

  set totalFractionalDescent(double? value) =>
      setFieldValue(totalFractionalDescentFieldNum, value);

  static const int avgFractionalAscentFieldNum = 68;

  /// avg_fractional_ascent, in m. fractional part of avg_ascent
  double? get avgFractionalAscent =>
      doubleFieldValue(avgFractionalAscentFieldNum);

  set avgFractionalAscent(double? value) =>
      setFieldValue(avgFractionalAscentFieldNum, value);

  static const int maxFractionalAscentFieldNum = 69;

  /// max_fractional_ascent, in m. fractional part of max_descent
  double? get maxFractionalAscent =>
      doubleFieldValue(maxFractionalAscentFieldNum);

  set maxFractionalAscent(double? value) =>
      setFieldValue(maxFractionalAscentFieldNum, value);

  static const int avgGradeAdjustedSpeedFieldNum = 71;

  /// avg_grade_adjusted_speed, in m/s.
  double? get avgGradeAdjustedSpeed =>
      doubleFieldValue(avgGradeAdjustedSpeedFieldNum);

  set avgGradeAdjustedSpeed(double? value) =>
      setFieldValue(avgGradeAdjustedSpeedFieldNum, value);

  static const int avgStressFieldNum = 72;

  /// avg_stress.
  int? get avgStress => intFieldValue(avgStressFieldNum);

  set avgStress(int? value) => setFieldValue(avgStressFieldNum, value);

  static const int totalMovingTimeFieldNum = 77;

  /// total_moving_time, in s.
  double? get totalMovingTime => doubleFieldValue(totalMovingTimeFieldNum);

  set totalMovingTime(double? value) =>
      setFieldValue(totalMovingTimeFieldNum, value);

  static const int startTimeFieldNum = 79;

  /// start_time.
  DateTime? get startTime {
    final value = intFieldValue(startTimeFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set startTime(DateTime? value) => setFieldValue(
      startTimeFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int minHeartRateFieldNum = 87;

  /// min_heart_rate, in bpm.
  int? get minHeartRate => intFieldValue(minHeartRateFieldNum);

  set minHeartRate(int? value) => setFieldValue(minHeartRateFieldNum, value);

  static const int avgStanceTimePercentFieldNum = 91;

  /// avg_stance_time_percent, in percent.
  double? get avgStanceTimePercent =>
      doubleFieldValue(avgStanceTimePercentFieldNum);

  set avgStanceTimePercent(double? value) =>
      setFieldValue(avgStanceTimePercentFieldNum, value);

  static const int maxTotalTimerTimeFieldNum = 101;

  /// max_total_timer_time, in s.
  double? get maxTotalTimerTime => doubleFieldValue(maxTotalTimerTimeFieldNum);

  set maxTotalTimerTime(double? value) =>
      setFieldValue(maxTotalTimerTimeFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[254] =
        Field('message_index', 254, BaseType.uint16, 1.0, 0.0, '', false);
    fields[253] =
        Field('timestamp', 253, BaseType.uint32, 1.0, 0.0, 's', false);
    fields[0] = Field('split_type', 0, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[1] = Field('sport', 1, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[2] = Field('sub_sport', 2, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[3] = Field('num_splits', 3, BaseType.uint16, 1.0, 0.0, '', false);
    fields[4] =
        Field('total_timer_time', 4, BaseType.uint32, 1000.0, 0.0, 's', false);
    fields[5] =
        Field('total_distance', 5, BaseType.uint32, 100.0, 0.0, 'm', false);
    fields[6] =
        Field('avg_speed', 6, BaseType.uint32, 1000.0, 0.0, 'm/s', false);
    fields[7] =
        Field('max_speed', 7, BaseType.uint32, 1000.0, 0.0, 'm/s', false);
    fields[8] = Field('total_ascent', 8, BaseType.uint16, 1.0, 0.0, 'm', false);
    fields[9] =
        Field('total_descent', 9, BaseType.uint16, 1.0, 0.0, 'm', false);
    fields[10] =
        Field('avg_heart_rate', 10, BaseType.uint8, 1.0, 0.0, 'bpm', false);
    fields[11] =
        Field('max_heart_rate', 11, BaseType.uint8, 1.0, 0.0, 'bpm', false);
    fields[12] =
        Field('avg_vert_speed', 12, BaseType.sint32, 1000.0, 0.0, 'm/s', false);
    fields[13] =
        Field('total_calories', 13, BaseType.uint32, 1.0, 0.0, 'kcal', false);
    fields[14] = Field(
        'avg_cadence', 14, BaseType.uint16, 128.0, 0.0, 'rpm', false)
      ..addSubField(SubField(
          'avg_running_cadence', BaseType.uint16, 128.0, 0.0, 'strides/min')
        ..addMap(1, 1))
      ..addSubField(SubField(
          'avg_swimming_cadence', BaseType.uint16, 128.0, 0.0, 'strokes/min')
        ..addMap(1, 5))
      ..addSubField(SubField(
          'avg_paddlesport_cadence', BaseType.uint16, 128.0, 0.0, 'strokes/min')
        ..addMap(1, 15)
        ..addMap(1, 37))
      ..addSubField(
          SubField('avg_push_cadence', BaseType.uint16, 1.0, 0.0, 'pushes/min')
            ..addMap(1, 66)
            ..addMap(1, 65));
    fields[15] = Field(
        'max_cadence', 15, BaseType.uint16, 128.0, 0.0, 'rpm', false)
      ..addSubField(SubField(
          'max_running_cadence', BaseType.uint16, 128.0, 0.0, 'strides/min')
        ..addMap(1, 1))
      ..addSubField(SubField(
          'max_swimming_cadence', BaseType.uint16, 128.0, 0.0, 'strokes/min')
        ..addMap(1, 5))
      ..addSubField(SubField(
          'max_paddlesport_cadence', BaseType.uint16, 128.0, 0.0, 'strokes/min')
        ..addMap(1, 15)
        ..addMap(1, 37))
      ..addSubField(
          SubField('max_push_cadence', BaseType.uint16, 1.0, 0.0, 'pushes/min')
            ..addMap(1, 66)
            ..addMap(1, 65));
    fields[16] = Field(
        'total_cycles', 16, BaseType.uint32, 1.0, 0.0, 'cycles', false)
      ..addSubField(
          SubField('total_strides', BaseType.uint32, 1.0, 0.0, 'strides')
            ..addMap(1, 1)
            ..addMap(1, 11))
      ..addSubField(
          SubField('total_strokes', BaseType.uint32, 1.0, 0.0, 'strokes')
            ..addMap(1, 2)
            ..addMap(1, 5)
            ..addMap(1, 15)
            ..addMap(1, 37))
      ..addSubField(SubField('total_reps', BaseType.uint32, 1.0, 0.0, 'reps')
        ..addMap(1, 62))
      ..addSubField(
          SubField('total_pushes', BaseType.uint32, 1.0, 0.0, 'pushes')
            ..addMap(1, 66)
            ..addMap(1, 65));
    fields[17] =
        Field('avg_temperature', 17, BaseType.sint8, 1.0, 0.0, 'C', false);
    fields[18] =
        Field('max_temperature', 18, BaseType.sint8, 1.0, 0.0, 'C', false);
    fields[19] =
        Field('min_temperature', 19, BaseType.sint8, 1.0, 0.0, 'C', false);
    fields[20] = Field('avg_vertical_oscillation', 20, BaseType.uint16, 10.0,
        0.0, 'mm', false);
    fields[21] = Field('avg_vertical_ratio', 21, BaseType.uint16, 100.0, 0.0,
        'percent', false);
    fields[22] =
        Field('avg_stance_time', 22, BaseType.uint16, 10.0, 0.0, 'ms', false);
    fields[23] = Field('avg_stance_time_balance', 23, BaseType.uint16, 100.0,
        0.0, 'percent', false);
    fields[24] =
        Field('avg_step_length', 24, BaseType.uint16, 10.0, 0.0, 'mm', false);
    fields[25] =
        Field('avg_power', 25, BaseType.uint16, 1.0, 0.0, 'watts', false);
    fields[26] =
        Field('max_power', 26, BaseType.uint16, 1.0, 0.0, 'watts', false);
    fields[27] = Field(
        'normalized_power', 27, BaseType.uint16, 1.0, 0.0, 'watts', false);
    fields[28] =
        Field('left_right_balance', 28, BaseType.uint16, 1.0, 0.0, '', false);
    fields[29] =
        Field('time_standing', 29, BaseType.uint32, 1000.0, 0.0, 's', false);
    fields[30] =
        Field('avg_left_pco', 30, BaseType.sint8, 1.0, 0.0, 'mm', false);
    fields[31] =
        Field('avg_right_pco', 31, BaseType.sint8, 1.0, 0.0, 'mm', false);
    fields[32] = Field('avg_left_power_phase', 32, BaseType.uint8, 0.7111111,
        0.0, 'degrees', false);
    fields[33] = Field('avg_left_power_phase_peak', 33, BaseType.uint8,
        0.7111111, 0.0, 'degrees', false);
    fields[34] = Field('avg_right_power_phase', 34, BaseType.uint8, 0.7111111,
        0.0, 'degrees', false);
    fields[35] = Field('avg_right_power_phase_peak', 35, BaseType.uint8,
        0.7111111, 0.0, 'degrees', false);
    fields[36] = Field(
        'avg_power_position', 36, BaseType.uint16, 1.0, 0.0, 'watts', false);
    fields[37] = Field(
        'max_power_position', 37, BaseType.uint16, 1.0, 0.0, 'watts', false);
    fields[38] = Field('avg_left_torque_effectiveness', 38, BaseType.uint8, 2.0,
        0.0, 'percent', false);
    fields[39] = Field('avg_right_torque_effectiveness', 39, BaseType.uint8,
        2.0, 0.0, 'percent', false);
    fields[40] = Field('avg_left_pedal_smoothness', 40, BaseType.uint8, 2.0,
        0.0, 'percent', false);
    fields[41] = Field('avg_right_pedal_smoothness', 41, BaseType.uint8, 2.0,
        0.0, 'percent', false);
    fields[42] = Field('avg_combined_pedal_smoothness', 42, BaseType.uint8, 2.0,
        0.0, 'percent', false);
    fields[43] =
        Field('avg_flow', 43, BaseType.float32, 1.0, 0.0, 'Flow', false);
    fields[44] =
        Field('total_grit', 44, BaseType.float32, 1.0, 0.0, 'kGrit', false);
    fields[47] =
        Field('swim_stroke', 47, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[48] = Field(
        'num_active_lengths', 48, BaseType.uint16, 1.0, 0.0, 'lengths', false);
    fields[49] = Field('avg_swolf', 49, BaseType.uint16, 1.0, 0.0, '', false);
    fields[50] = Field(
        'avg_stroke_distance', 50, BaseType.uint16, 100.0, 0.0, 'm', false);
    fields[51] = Field('avg_strokes_per_length', 51, BaseType.uint16, 10.0, 0.0,
        'strokes / length', false);
    fields[52] = Field('avg_ascent', 52, BaseType.uint16, 1.0, 0.0, 'm', false);
    fields[53] = Field('max_ascent', 53, BaseType.uint16, 1.0, 0.0, 'm', false);
    fields[54] =
        Field('climb_grading_scale', 54, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[55] = Field(
        'climb_max_grade_value', 55, BaseType.uint32, 1.0, 0.0, '', false)
      ..addSubField(
          SubField('climb_max_grade_yds', BaseType.fitEnum, 1.0, 0.0, '')
            ..addMap(54, 0))
      ..addSubField(
          SubField('climb_max_grade_uiaa', BaseType.fitEnum, 1.0, 0.0, '')
            ..addMap(54, 1))
      ..addSubField(
          SubField('climb_max_grade_french', BaseType.fitEnum, 1.0, 0.0, '')
            ..addMap(54, 2))
      ..addSubField(SubField(
          'climb_max_grade_british_adjectival', BaseType.fitEnum, 1.0, 0.0, '')
        ..addMap(54, 3))
      ..addSubField(SubField(
          'climb_max_grade_british_technical', BaseType.fitEnum, 1.0, 0.0, '')
        ..addMap(54, 4))
      ..addSubField(
          SubField('climb_max_grade_ewbank', BaseType.fitEnum, 1.0, 0.0, '')
            ..addMap(54, 5))
      ..addSubField(
          SubField('climb_max_grade_brazilian', BaseType.fitEnum, 1.0, 0.0, '')
            ..addMap(54, 6))
      ..addSubField(
          SubField('climb_max_grade_saxon', BaseType.fitEnum, 1.0, 0.0, '')
            ..addMap(54, 7))
      ..addSubField(
          SubField('climb_max_grade_vermin', BaseType.fitEnum, 1.0, 0.0, '')
            ..addMap(54, 8))
      ..addSubField(
          SubField('climb_max_grade_font', BaseType.fitEnum, 1.0, 0.0, '')
            ..addMap(54, 9))
      ..addSubField(
          SubField('climb_max_grade_dankyu', BaseType.fitEnum, 1.0, 0.0, '')
            ..addMap(54, 10));
    fields[56] = Field('num_falls', 56, BaseType.uint16, 1.0, 0.0, '', false);
    fields[58] =
        Field('num_climbs_attempted', 58, BaseType.uint16, 1.0, 0.0, '', false);
    fields[59] =
        Field('num_climbs_completed', 59, BaseType.uint16, 1.0, 0.0, '', false);
    fields[60] =
        Field('max_distance', 60, BaseType.uint32, 100.0, 0.0, 'm', false);
    fields[64] = Field(
        'metabolic_calories', 64, BaseType.uint16, 1.0, 0.0, 'kcal', false);
    fields[65] =
        Field('active_time', 65, BaseType.uint32, 1000.0, 0.0, 's', false);
    fields[66] = Field(
        'total_fractional_ascent', 66, BaseType.uint8, 100.0, 0.0, 'm', false);
    fields[67] = Field(
        'total_fractional_descent', 67, BaseType.uint8, 100.0, 0.0, 'm', false);
    fields[68] = Field(
        'avg_fractional_ascent', 68, BaseType.uint8, 100.0, 0.0, 'm', false);
    fields[69] = Field(
        'max_fractional_ascent', 69, BaseType.uint8, 100.0, 0.0, 'm', false);
    fields[71] = Field('avg_grade_adjusted_speed', 71, BaseType.uint32, 1000.0,
        0.0, 'm/s', false);
    fields[72] = Field('avg_stress', 72, BaseType.uint16, 1.0, 0.0, '', false);
    fields[77] = Field(
        'total_moving_time', 77, BaseType.uint32, 1000.0, 0.0, 's', false);
    fields[79] = Field('start_time', 79, BaseType.uint32, 1.0, 0.0, '', false);
    fields[87] =
        Field('min_heart_rate', 87, BaseType.uint8, 1.0, 0.0, 'bpm', false);
    fields[91] = Field('avg_stance_time_percent', 91, BaseType.uint16, 100.0,
        0.0, 'percent', false);
    fields[101] = Field(
        'max_total_timer_time', 101, BaseType.uint32, 1000.0, 0.0, 's', false);
    return fields;
  }
}
