/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `sport` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class SportMesg extends Mesg {
  SportMesg() : super('sport', MesgNum.sport);

  /// A deep copy of [mesg] reinterpreted as a `sport`.
  SportMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  SportMesg.adopt(super.mesg) : super.adopt();

  static const int sportFieldNum = 0;

  /// sport.
  Sport? get sport {
    final value = intFieldValue(sportFieldNum);
    return value == null ? null : Sport.fromValue(value);
  }

  set sport(Sport? value) => setFieldValue(sportFieldNum, value?.value);

  static const int subSportFieldNum = 1;

  /// sub_sport.
  SubSport? get subSport {
    final value = intFieldValue(subSportFieldNum);
    return value == null ? null : SubSport.fromValue(value);
  }

  set subSport(SubSport? value) =>
      setFieldValue(subSportFieldNum, value?.value);

  static const int name_FieldNum = 3;

  /// name.
  String? get name_ => stringFieldValue(name_FieldNum);

  set name_(String? value) => setFieldValue(name_FieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[0] = Field('sport', 0, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[1] = Field('sub_sport', 1, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[3] = Field('name', 3, BaseType.string, 1.0, 0.0, '', false);
    return fields;
  }
}
