/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `video_title` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class VideoTitleMesg extends Mesg {
  VideoTitleMesg() : super('video_title', MesgNum.videoTitle);

  /// A deep copy of [mesg] reinterpreted as a `video_title`.
  VideoTitleMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  VideoTitleMesg.adopt(super.mesg) : super.adopt();

  static const int messageIndexFieldNum = 254;

  /// message_index. Long titles will be split into multiple parts
  int? get messageIndex => intFieldValue(messageIndexFieldNum);

  set messageIndex(int? value) => setFieldValue(messageIndexFieldNum, value);

  static const int messageCountFieldNum = 0;

  /// message_count. Total number of title parts
  int? get messageCount => intFieldValue(messageCountFieldNum);

  set messageCount(int? value) => setFieldValue(messageCountFieldNum, value);

  static const int textFieldNum = 1;

  /// text.
  String? get text => stringFieldValue(textFieldNum);

  set text(String? value) => setFieldValue(textFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[254] =
        Field('message_index', 254, BaseType.uint16, 1.0, 0.0, '', false);
    fields[0] = Field('message_count', 0, BaseType.uint16, 1.0, 0.0, '', false);
    fields[1] = Field('text', 1, BaseType.string, 1.0, 0.0, '', false);
    return fields;
  }
}
