/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `weather_conditions` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class WeatherConditionsMesg extends Mesg {
  WeatherConditionsMesg()
      : super('weather_conditions', MesgNum.weatherConditions);

  /// A deep copy of [mesg] reinterpreted as a `weather_conditions`.
  WeatherConditionsMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  WeatherConditionsMesg.adopt(super.mesg) : super.adopt();

  static const int timestampFieldNum = 253;

  /// timestamp. time of update for current conditions, else forecast time
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int weatherReportFieldNum = 0;

  /// weather_report. Current or forecast
  WeatherReport? get weatherReport {
    final value = intFieldValue(weatherReportFieldNum);
    return value == null ? null : WeatherReport.fromValue(value);
  }

  set weatherReport(WeatherReport? value) =>
      setFieldValue(weatherReportFieldNum, value?.value);

  static const int temperatureFieldNum = 1;

  /// temperature, in C.
  int? get temperature => intFieldValue(temperatureFieldNum);

  set temperature(int? value) => setFieldValue(temperatureFieldNum, value);

  static const int conditionFieldNum = 2;

  /// condition. Corresponds to GSC Response weatherIcon field
  WeatherStatus? get condition {
    final value = intFieldValue(conditionFieldNum);
    return value == null ? null : WeatherStatus.fromValue(value);
  }

  set condition(WeatherStatus? value) =>
      setFieldValue(conditionFieldNum, value?.value);

  static const int windDirectionFieldNum = 3;

  /// wind_direction, in degrees.
  int? get windDirection => intFieldValue(windDirectionFieldNum);

  set windDirection(int? value) => setFieldValue(windDirectionFieldNum, value);

  static const int windSpeedFieldNum = 4;

  /// wind_speed, in m/s.
  double? get windSpeed => doubleFieldValue(windSpeedFieldNum);

  set windSpeed(double? value) => setFieldValue(windSpeedFieldNum, value);

  static const int precipitationProbabilityFieldNum = 5;

  /// precipitation_probability. range 0-100
  int? get precipitationProbability =>
      intFieldValue(precipitationProbabilityFieldNum);

  set precipitationProbability(int? value) =>
      setFieldValue(precipitationProbabilityFieldNum, value);

  static const int temperatureFeelsLikeFieldNum = 6;

  /// temperature_feels_like, in C. Heat Index if GCS heatIdx above or equal to 90F or wind chill if GCS windChill below or equal to 32F
  int? get temperatureFeelsLike => intFieldValue(temperatureFeelsLikeFieldNum);

  set temperatureFeelsLike(int? value) =>
      setFieldValue(temperatureFeelsLikeFieldNum, value);

  static const int relativeHumidityFieldNum = 7;

  /// relative_humidity.
  int? get relativeHumidity => intFieldValue(relativeHumidityFieldNum);

  set relativeHumidity(int? value) =>
      setFieldValue(relativeHumidityFieldNum, value);

  static const int locationFieldNum = 8;

  /// location. string corresponding to GCS response location string
  String? get location => stringFieldValue(locationFieldNum);

  set location(String? value) => setFieldValue(locationFieldNum, value);

  static const int observedAtTimeFieldNum = 9;

  /// observed_at_time.
  DateTime? get observedAtTime {
    final value = intFieldValue(observedAtTimeFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set observedAtTime(DateTime? value) => setFieldValue(observedAtTimeFieldNum,
      value == null ? null : FitDateTime.toTimestamp(value));

  static const int observedLocationLatFieldNum = 10;

  /// observed_location_lat, in semicircles.
  int? get observedLocationLat => intFieldValue(observedLocationLatFieldNum);

  set observedLocationLat(int? value) =>
      setFieldValue(observedLocationLatFieldNum, value);

  static const int observedLocationLongFieldNum = 11;

  /// observed_location_long, in semicircles.
  int? get observedLocationLong => intFieldValue(observedLocationLongFieldNum);

  set observedLocationLong(int? value) =>
      setFieldValue(observedLocationLongFieldNum, value);

  static const int dayOfWeekFieldNum = 12;

  /// day_of_week.
  DayOfWeek? get dayOfWeek {
    final value = intFieldValue(dayOfWeekFieldNum);
    return value == null ? null : DayOfWeek.fromValue(value);
  }

  set dayOfWeek(DayOfWeek? value) =>
      setFieldValue(dayOfWeekFieldNum, value?.value);

  static const int highTemperatureFieldNum = 13;

  /// high_temperature, in C.
  int? get highTemperature => intFieldValue(highTemperatureFieldNum);

  set highTemperature(int? value) =>
      setFieldValue(highTemperatureFieldNum, value);

  static const int lowTemperatureFieldNum = 14;

  /// low_temperature, in C.
  int? get lowTemperature => intFieldValue(lowTemperatureFieldNum);

  set lowTemperature(int? value) =>
      setFieldValue(lowTemperatureFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[253] = Field('timestamp', 253, BaseType.uint32, 1.0, 0.0, '', false);
    fields[0] =
        Field('weather_report', 0, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[1] = Field('temperature', 1, BaseType.sint8, 1.0, 0.0, 'C', false);
    fields[2] = Field('condition', 2, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[3] =
        Field('wind_direction', 3, BaseType.uint16, 1.0, 0.0, 'degrees', false);
    fields[4] =
        Field('wind_speed', 4, BaseType.uint16, 1000.0, 0.0, 'm/s', false);
    fields[5] = Field(
        'precipitation_probability', 5, BaseType.uint8, 1.0, 0.0, '', false);
    fields[6] = Field(
        'temperature_feels_like', 6, BaseType.sint8, 1.0, 0.0, 'C', false);
    fields[7] =
        Field('relative_humidity', 7, BaseType.uint8, 1.0, 0.0, '', false);
    fields[8] = Field('location', 8, BaseType.string, 1.0, 0.0, '', false);
    fields[9] =
        Field('observed_at_time', 9, BaseType.uint32, 1.0, 0.0, '', false);
    fields[10] = Field('observed_location_lat', 10, BaseType.sint32, 1.0, 0.0,
        'semicircles', false);
    fields[11] = Field('observed_location_long', 11, BaseType.sint32, 1.0, 0.0,
        'semicircles', false);
    fields[12] =
        Field('day_of_week', 12, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[13] =
        Field('high_temperature', 13, BaseType.sint8, 1.0, 0.0, 'C', false);
    fields[14] =
        Field('low_temperature', 14, BaseType.sint8, 1.0, 0.0, 'C', false);
    return fields;
  }
}
