/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `weight_scale` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class WeightScaleMesg extends Mesg {
  WeightScaleMesg() : super('weight_scale', MesgNum.weightScale);

  /// A deep copy of [mesg] reinterpreted as a `weight_scale`.
  WeightScaleMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  WeightScaleMesg.adopt(super.mesg) : super.adopt();

  static const int timestampFieldNum = 253;

  /// timestamp, in s.
  DateTime? get timestamp {
    final value = intFieldValue(timestampFieldNum);
    return value == null ? null : FitDateTime.toDateTime(value);
  }

  set timestamp(DateTime? value) => setFieldValue(
      timestampFieldNum, value == null ? null : FitDateTime.toTimestamp(value));

  static const int weightFieldNum = 0;

  /// weight, in kg.
  double? get weight => doubleFieldValue(weightFieldNum);

  set weight(double? value) => setFieldValue(weightFieldNum, value);

  static const int percentFatFieldNum = 1;

  /// percent_fat, in %.
  double? get percentFat => doubleFieldValue(percentFatFieldNum);

  set percentFat(double? value) => setFieldValue(percentFatFieldNum, value);

  static const int percentHydrationFieldNum = 2;

  /// percent_hydration, in %.
  double? get percentHydration => doubleFieldValue(percentHydrationFieldNum);

  set percentHydration(double? value) =>
      setFieldValue(percentHydrationFieldNum, value);

  static const int visceralFatMassFieldNum = 3;

  /// visceral_fat_mass, in kg.
  double? get visceralFatMass => doubleFieldValue(visceralFatMassFieldNum);

  set visceralFatMass(double? value) =>
      setFieldValue(visceralFatMassFieldNum, value);

  static const int boneMassFieldNum = 4;

  /// bone_mass, in kg.
  double? get boneMass => doubleFieldValue(boneMassFieldNum);

  set boneMass(double? value) => setFieldValue(boneMassFieldNum, value);

  static const int muscleMassFieldNum = 5;

  /// muscle_mass, in kg.
  double? get muscleMass => doubleFieldValue(muscleMassFieldNum);

  set muscleMass(double? value) => setFieldValue(muscleMassFieldNum, value);

  static const int basalMetFieldNum = 7;

  /// basal_met, in kcal/day.
  double? get basalMet => doubleFieldValue(basalMetFieldNum);

  set basalMet(double? value) => setFieldValue(basalMetFieldNum, value);

  static const int physiqueRatingFieldNum = 8;

  /// physique_rating.
  int? get physiqueRating => intFieldValue(physiqueRatingFieldNum);

  set physiqueRating(int? value) =>
      setFieldValue(physiqueRatingFieldNum, value);

  static const int activeMetFieldNum = 9;

  /// active_met, in kcal/day. ~4kJ per kcal, 0.25 allows max 16384 kcal
  double? get activeMet => doubleFieldValue(activeMetFieldNum);

  set activeMet(double? value) => setFieldValue(activeMetFieldNum, value);

  static const int metabolicAgeFieldNum = 10;

  /// metabolic_age, in years.
  int? get metabolicAge => intFieldValue(metabolicAgeFieldNum);

  set metabolicAge(int? value) => setFieldValue(metabolicAgeFieldNum, value);

  static const int visceralFatRatingFieldNum = 11;

  /// visceral_fat_rating.
  int? get visceralFatRating => intFieldValue(visceralFatRatingFieldNum);

  set visceralFatRating(int? value) =>
      setFieldValue(visceralFatRatingFieldNum, value);

  static const int userProfileIndexFieldNum = 12;

  /// user_profile_index. Associates this weight scale message to a user. This corresponds to the index of the user profile message in the weight scale file.
  int? get userProfileIndex => intFieldValue(userProfileIndexFieldNum);

  set userProfileIndex(int? value) =>
      setFieldValue(userProfileIndexFieldNum, value);

  static const int bmiFieldNum = 13;

  /// bmi, in kg/m^2.
  double? get bmi => doubleFieldValue(bmiFieldNum);

  set bmi(double? value) => setFieldValue(bmiFieldNum, value);

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[253] =
        Field('timestamp', 253, BaseType.uint32, 1.0, 0.0, 's', false);
    fields[0] = Field('weight', 0, BaseType.uint16, 100.0, 0.0, 'kg', false);
    fields[1] =
        Field('percent_fat', 1, BaseType.uint16, 100.0, 0.0, '%', false);
    fields[2] =
        Field('percent_hydration', 2, BaseType.uint16, 100.0, 0.0, '%', false);
    fields[3] =
        Field('visceral_fat_mass', 3, BaseType.uint16, 100.0, 0.0, 'kg', false);
    fields[4] = Field('bone_mass', 4, BaseType.uint16, 100.0, 0.0, 'kg', false);
    fields[5] =
        Field('muscle_mass', 5, BaseType.uint16, 100.0, 0.0, 'kg', false);
    fields[7] =
        Field('basal_met', 7, BaseType.uint16, 4.0, 0.0, 'kcal/day', false);
    fields[8] =
        Field('physique_rating', 8, BaseType.uint8, 1.0, 0.0, '', false);
    fields[9] =
        Field('active_met', 9, BaseType.uint16, 4.0, 0.0, 'kcal/day', false);
    fields[10] =
        Field('metabolic_age', 10, BaseType.uint8, 1.0, 0.0, 'years', false);
    fields[11] =
        Field('visceral_fat_rating', 11, BaseType.uint8, 1.0, 0.0, '', false);
    fields[12] =
        Field('user_profile_index', 12, BaseType.uint16, 1.0, 0.0, '', false);
    fields[13] = Field('bmi', 13, BaseType.uint16, 10.0, 0.0, 'kg/m^2', false);
    return fields;
  }
}
