/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

// A generated message class imports the whole profile surface; which parts it
// actually names depends on the fields this particular message declares.
// ignore_for_file: unused_import

import '../base_type.dart';
import '../field.dart';
import '../field_component.dart';
import '../fit.dart';
import '../fit_date_time.dart';
import '../mesg.dart';
import '../profile.dart';
import '../sub_field.dart';
import '../types.dart';

/// The FIT `workout_step` message.
///
/// A thin typed view over [Mesg]: the accessors below read and write the same
/// numbered fields the untyped API exposes, so nothing is hidden by using them.
class WorkoutStepMesg extends Mesg {
  WorkoutStepMesg() : super('workout_step', MesgNum.workoutStep);

  /// A deep copy of [mesg] reinterpreted as a `workout_step`.
  WorkoutStepMesg.from(super.mesg) : super.from();

  /// Takes over [mesg]'s fields rather than copying them. Only for a caller that
  /// owns [mesg] outright and discards it — see [Mesg.adopt].
  WorkoutStepMesg.adopt(super.mesg) : super.adopt();

  static const int messageIndexFieldNum = 254;

  /// message_index.
  int? get messageIndex => intFieldValue(messageIndexFieldNum);

  set messageIndex(int? value) => setFieldValue(messageIndexFieldNum, value);

  static const int wktStepNameFieldNum = 0;

  /// wkt_step_name.
  String? get wktStepName => stringFieldValue(wktStepNameFieldNum);

  set wktStepName(String? value) => setFieldValue(wktStepNameFieldNum, value);

  static const int durationTypeFieldNum = 1;

  /// duration_type.
  WktStepDuration? get durationType {
    final value = intFieldValue(durationTypeFieldNum);
    return value == null ? null : WktStepDuration.fromValue(value);
  }

  set durationType(WktStepDuration? value) =>
      setFieldValue(durationTypeFieldNum, value?.value);

  static const int durationValueFieldNum = 2;

  /// duration_value.
  int? get durationValue => intFieldValue(durationValueFieldNum);

  set durationValue(int? value) => setFieldValue(durationValueFieldNum, value);

  /// duration_time: what duration_value means when this message selects it.
  double? get durationTime => doubleFieldValue(
      durationValueFieldNum, 0, const NamedSelector('duration_time'));

  void setDurationTime(double? value) => setFieldValue(
      durationValueFieldNum, value, 0, const NamedSelector('duration_time'));

  /// duration_distance: what duration_value means when this message selects it.
  double? get durationDistance => doubleFieldValue(
      durationValueFieldNum, 0, const NamedSelector('duration_distance'));

  void setDurationDistance(double? value) => setFieldValue(
      durationValueFieldNum,
      value,
      0,
      const NamedSelector('duration_distance'));

  /// duration_hr: what duration_value means when this message selects it.
  int? get durationHr => intFieldValue(
      durationValueFieldNum, 0, const NamedSelector('duration_hr'));

  void setDurationHr(int? value) => setFieldValue(
      durationValueFieldNum, value, 0, const NamedSelector('duration_hr'));

  /// duration_calories: what duration_value means when this message selects it.
  int? get durationCalories => intFieldValue(
      durationValueFieldNum, 0, const NamedSelector('duration_calories'));

  void setDurationCalories(int? value) => setFieldValue(durationValueFieldNum,
      value, 0, const NamedSelector('duration_calories'));

  /// duration_step: what duration_value means when this message selects it.
  ///
  /// message_index of step to loop back to. Steps are assumed to be in the order by message_index. custom_name and intensity members are undefined for this duration type.
  int? get durationStep => intFieldValue(
      durationValueFieldNum, 0, const NamedSelector('duration_step'));

  void setDurationStep(int? value) => setFieldValue(
      durationValueFieldNum, value, 0, const NamedSelector('duration_step'));

  /// duration_power: what duration_value means when this message selects it.
  int? get durationPower => intFieldValue(
      durationValueFieldNum, 0, const NamedSelector('duration_power'));

  void setDurationPower(int? value) => setFieldValue(
      durationValueFieldNum, value, 0, const NamedSelector('duration_power'));

  /// duration_reps: what duration_value means when this message selects it.
  int? get durationReps => intFieldValue(
      durationValueFieldNum, 0, const NamedSelector('duration_reps'));

  void setDurationReps(int? value) => setFieldValue(
      durationValueFieldNum, value, 0, const NamedSelector('duration_reps'));

  static const int targetTypeFieldNum = 3;

  /// target_type.
  WktStepTarget? get targetType {
    final value = intFieldValue(targetTypeFieldNum);
    return value == null ? null : WktStepTarget.fromValue(value);
  }

  set targetType(WktStepTarget? value) =>
      setFieldValue(targetTypeFieldNum, value?.value);

  static const int targetValueFieldNum = 4;

  /// target_value.
  int? get targetValue => intFieldValue(targetValueFieldNum);

  set targetValue(int? value) => setFieldValue(targetValueFieldNum, value);

  /// target_speed_zone: what target_value means when this message selects it.
  ///
  /// speed zone (1-10);Custom =0;
  int? get targetSpeedZone => intFieldValue(
      targetValueFieldNum, 0, const NamedSelector('target_speed_zone'));

  void setTargetSpeedZone(int? value) => setFieldValue(
      targetValueFieldNum, value, 0, const NamedSelector('target_speed_zone'));

  /// target_hr_zone: what target_value means when this message selects it.
  ///
  /// hr zone (1-5);Custom =0;
  int? get targetHrZone => intFieldValue(
      targetValueFieldNum, 0, const NamedSelector('target_hr_zone'));

  void setTargetHrZone(int? value) => setFieldValue(
      targetValueFieldNum, value, 0, const NamedSelector('target_hr_zone'));

  /// target_cadence_zone: what target_value means when this message selects it.
  ///
  /// Zone (1-?); Custom = 0;
  int? get targetCadenceZone => intFieldValue(
      targetValueFieldNum, 0, const NamedSelector('target_cadence_zone'));

  void setTargetCadenceZone(int? value) => setFieldValue(targetValueFieldNum,
      value, 0, const NamedSelector('target_cadence_zone'));

  /// target_power_zone: what target_value means when this message selects it.
  ///
  /// Power Zone ( 1-7); Custom = 0;
  int? get targetPowerZone => intFieldValue(
      targetValueFieldNum, 0, const NamedSelector('target_power_zone'));

  void setTargetPowerZone(int? value) => setFieldValue(
      targetValueFieldNum, value, 0, const NamedSelector('target_power_zone'));

  /// repeat_steps: what target_value means when this message selects it.
  ///
  /// # of repetitions
  int? get repeatSteps => intFieldValue(
      targetValueFieldNum, 0, const NamedSelector('repeat_steps'));

  void setRepeatSteps(int? value) => setFieldValue(
      targetValueFieldNum, value, 0, const NamedSelector('repeat_steps'));

  /// repeat_time: what target_value means when this message selects it.
  double? get repeatTime => doubleFieldValue(
      targetValueFieldNum, 0, const NamedSelector('repeat_time'));

  void setRepeatTime(double? value) => setFieldValue(
      targetValueFieldNum, value, 0, const NamedSelector('repeat_time'));

  /// repeat_distance: what target_value means when this message selects it.
  double? get repeatDistance => doubleFieldValue(
      targetValueFieldNum, 0, const NamedSelector('repeat_distance'));

  void setRepeatDistance(double? value) => setFieldValue(
      targetValueFieldNum, value, 0, const NamedSelector('repeat_distance'));

  /// repeat_calories: what target_value means when this message selects it.
  int? get repeatCalories => intFieldValue(
      targetValueFieldNum, 0, const NamedSelector('repeat_calories'));

  void setRepeatCalories(int? value) => setFieldValue(
      targetValueFieldNum, value, 0, const NamedSelector('repeat_calories'));

  /// repeat_hr: what target_value means when this message selects it.
  int? get repeatHr =>
      intFieldValue(targetValueFieldNum, 0, const NamedSelector('repeat_hr'));

  void setRepeatHr(int? value) => setFieldValue(
      targetValueFieldNum, value, 0, const NamedSelector('repeat_hr'));

  /// repeat_power: what target_value means when this message selects it.
  int? get repeatPower => intFieldValue(
      targetValueFieldNum, 0, const NamedSelector('repeat_power'));

  void setRepeatPower(int? value) => setFieldValue(
      targetValueFieldNum, value, 0, const NamedSelector('repeat_power'));

  /// target_stroke_type: what target_value means when this message selects it.
  SwimStroke? get targetStrokeType {
    final value = intFieldValue(
        targetValueFieldNum, 0, const NamedSelector('target_stroke_type'));
    return value == null ? null : SwimStroke.fromValue(value);
  }

  void setTargetStrokeType(SwimStroke? value) => setFieldValue(
      targetValueFieldNum,
      value?.value,
      0,
      const NamedSelector('target_stroke_type'));

  static const int customTargetValueLowFieldNum = 5;

  /// custom_target_value_low.
  int? get customTargetValueLow => intFieldValue(customTargetValueLowFieldNum);

  set customTargetValueLow(int? value) =>
      setFieldValue(customTargetValueLowFieldNum, value);

  /// custom_target_speed_low: what custom_target_value_low means when this message selects it.
  double? get customTargetSpeedLow => doubleFieldValue(
      customTargetValueLowFieldNum,
      0,
      const NamedSelector('custom_target_speed_low'));

  void setCustomTargetSpeedLow(double? value) => setFieldValue(
      customTargetValueLowFieldNum,
      value,
      0,
      const NamedSelector('custom_target_speed_low'));

  /// custom_target_heart_rate_low: what custom_target_value_low means when this message selects it.
  int? get customTargetHeartRateLow => intFieldValue(
      customTargetValueLowFieldNum,
      0,
      const NamedSelector('custom_target_heart_rate_low'));

  void setCustomTargetHeartRateLow(int? value) => setFieldValue(
      customTargetValueLowFieldNum,
      value,
      0,
      const NamedSelector('custom_target_heart_rate_low'));

  /// custom_target_cadence_low: what custom_target_value_low means when this message selects it.
  int? get customTargetCadenceLow => intFieldValue(customTargetValueLowFieldNum,
      0, const NamedSelector('custom_target_cadence_low'));

  void setCustomTargetCadenceLow(int? value) => setFieldValue(
      customTargetValueLowFieldNum,
      value,
      0,
      const NamedSelector('custom_target_cadence_low'));

  /// custom_target_power_low: what custom_target_value_low means when this message selects it.
  int? get customTargetPowerLow => intFieldValue(customTargetValueLowFieldNum,
      0, const NamedSelector('custom_target_power_low'));

  void setCustomTargetPowerLow(int? value) => setFieldValue(
      customTargetValueLowFieldNum,
      value,
      0,
      const NamedSelector('custom_target_power_low'));

  static const int customTargetValueHighFieldNum = 6;

  /// custom_target_value_high.
  int? get customTargetValueHigh =>
      intFieldValue(customTargetValueHighFieldNum);

  set customTargetValueHigh(int? value) =>
      setFieldValue(customTargetValueHighFieldNum, value);

  /// custom_target_speed_high: what custom_target_value_high means when this message selects it.
  double? get customTargetSpeedHigh => doubleFieldValue(
      customTargetValueHighFieldNum,
      0,
      const NamedSelector('custom_target_speed_high'));

  void setCustomTargetSpeedHigh(double? value) => setFieldValue(
      customTargetValueHighFieldNum,
      value,
      0,
      const NamedSelector('custom_target_speed_high'));

  /// custom_target_heart_rate_high: what custom_target_value_high means when this message selects it.
  int? get customTargetHeartRateHigh => intFieldValue(
      customTargetValueHighFieldNum,
      0,
      const NamedSelector('custom_target_heart_rate_high'));

  void setCustomTargetHeartRateHigh(int? value) => setFieldValue(
      customTargetValueHighFieldNum,
      value,
      0,
      const NamedSelector('custom_target_heart_rate_high'));

  /// custom_target_cadence_high: what custom_target_value_high means when this message selects it.
  int? get customTargetCadenceHigh => intFieldValue(
      customTargetValueHighFieldNum,
      0,
      const NamedSelector('custom_target_cadence_high'));

  void setCustomTargetCadenceHigh(int? value) => setFieldValue(
      customTargetValueHighFieldNum,
      value,
      0,
      const NamedSelector('custom_target_cadence_high'));

  /// custom_target_power_high: what custom_target_value_high means when this message selects it.
  int? get customTargetPowerHigh => intFieldValue(customTargetValueHighFieldNum,
      0, const NamedSelector('custom_target_power_high'));

  void setCustomTargetPowerHigh(int? value) => setFieldValue(
      customTargetValueHighFieldNum,
      value,
      0,
      const NamedSelector('custom_target_power_high'));

  static const int intensityFieldNum = 7;

  /// intensity.
  Intensity? get intensity {
    final value = intFieldValue(intensityFieldNum);
    return value == null ? null : Intensity.fromValue(value);
  }

  set intensity(Intensity? value) =>
      setFieldValue(intensityFieldNum, value?.value);

  static const int notesFieldNum = 8;

  /// notes.
  String? get notes => stringFieldValue(notesFieldNum);

  set notes(String? value) => setFieldValue(notesFieldNum, value);

  static const int equipmentFieldNum = 9;

  /// equipment.
  WorkoutEquipment? get equipment {
    final value = intFieldValue(equipmentFieldNum);
    return value == null ? null : WorkoutEquipment.fromValue(value);
  }

  set equipment(WorkoutEquipment? value) =>
      setFieldValue(equipmentFieldNum, value?.value);

  static const int exerciseCategoryFieldNum = 10;

  /// exercise_category.
  ExerciseCategory? get exerciseCategory {
    final value = intFieldValue(exerciseCategoryFieldNum);
    return value == null ? null : ExerciseCategory.fromValue(value);
  }

  set exerciseCategory(ExerciseCategory? value) =>
      setFieldValue(exerciseCategoryFieldNum, value?.value);

  static const int exerciseNameFieldNum = 11;

  /// exercise_name.
  int? get exerciseName => intFieldValue(exerciseNameFieldNum);

  set exerciseName(int? value) => setFieldValue(exerciseNameFieldNum, value);

  static const int exerciseWeightFieldNum = 12;

  /// exercise_weight, in kg.
  double? get exerciseWeight => doubleFieldValue(exerciseWeightFieldNum);

  set exerciseWeight(double? value) =>
      setFieldValue(exerciseWeightFieldNum, value);

  static const int weightDisplayUnitFieldNum = 13;

  /// weight_display_unit.
  FitBaseUnit? get weightDisplayUnit {
    final value = intFieldValue(weightDisplayUnitFieldNum);
    return value == null ? null : FitBaseUnit.fromValue(value);
  }

  set weightDisplayUnit(FitBaseUnit? value) =>
      setFieldValue(weightDisplayUnitFieldNum, value?.value);

  static const int secondaryTargetTypeFieldNum = 19;

  /// secondary_target_type.
  WktStepTarget? get secondaryTargetType {
    final value = intFieldValue(secondaryTargetTypeFieldNum);
    return value == null ? null : WktStepTarget.fromValue(value);
  }

  set secondaryTargetType(WktStepTarget? value) =>
      setFieldValue(secondaryTargetTypeFieldNum, value?.value);

  static const int secondaryTargetValueFieldNum = 20;

  /// secondary_target_value.
  int? get secondaryTargetValue => intFieldValue(secondaryTargetValueFieldNum);

  set secondaryTargetValue(int? value) =>
      setFieldValue(secondaryTargetValueFieldNum, value);

  /// secondary_target_speed_zone: what secondary_target_value means when this message selects it.
  ///
  /// speed zone (1-10);Custom =0;
  int? get secondaryTargetSpeedZone => intFieldValue(
      secondaryTargetValueFieldNum,
      0,
      const NamedSelector('secondary_target_speed_zone'));

  void setSecondaryTargetSpeedZone(int? value) => setFieldValue(
      secondaryTargetValueFieldNum,
      value,
      0,
      const NamedSelector('secondary_target_speed_zone'));

  /// secondary_target_hr_zone: what secondary_target_value means when this message selects it.
  ///
  /// hr zone (1-5);Custom =0;
  int? get secondaryTargetHrZone => intFieldValue(secondaryTargetValueFieldNum,
      0, const NamedSelector('secondary_target_hr_zone'));

  void setSecondaryTargetHrZone(int? value) => setFieldValue(
      secondaryTargetValueFieldNum,
      value,
      0,
      const NamedSelector('secondary_target_hr_zone'));

  /// secondary_target_cadence_zone: what secondary_target_value means when this message selects it.
  ///
  /// Zone (1-?); Custom = 0;
  int? get secondaryTargetCadenceZone => intFieldValue(
      secondaryTargetValueFieldNum,
      0,
      const NamedSelector('secondary_target_cadence_zone'));

  void setSecondaryTargetCadenceZone(int? value) => setFieldValue(
      secondaryTargetValueFieldNum,
      value,
      0,
      const NamedSelector('secondary_target_cadence_zone'));

  /// secondary_target_power_zone: what secondary_target_value means when this message selects it.
  ///
  /// Power Zone ( 1-7); Custom = 0;
  int? get secondaryTargetPowerZone => intFieldValue(
      secondaryTargetValueFieldNum,
      0,
      const NamedSelector('secondary_target_power_zone'));

  void setSecondaryTargetPowerZone(int? value) => setFieldValue(
      secondaryTargetValueFieldNum,
      value,
      0,
      const NamedSelector('secondary_target_power_zone'));

  /// secondary_target_stroke_type: what secondary_target_value means when this message selects it.
  SwimStroke? get secondaryTargetStrokeType {
    final value = intFieldValue(secondaryTargetValueFieldNum, 0,
        const NamedSelector('secondary_target_stroke_type'));
    return value == null ? null : SwimStroke.fromValue(value);
  }

  void setSecondaryTargetStrokeType(SwimStroke? value) => setFieldValue(
      secondaryTargetValueFieldNum,
      value?.value,
      0,
      const NamedSelector('secondary_target_stroke_type'));

  static const int secondaryCustomTargetValueLowFieldNum = 21;

  /// secondary_custom_target_value_low.
  int? get secondaryCustomTargetValueLow =>
      intFieldValue(secondaryCustomTargetValueLowFieldNum);

  set secondaryCustomTargetValueLow(int? value) =>
      setFieldValue(secondaryCustomTargetValueLowFieldNum, value);

  /// secondary_custom_target_speed_low: what secondary_custom_target_value_low means when this message selects it.
  double? get secondaryCustomTargetSpeedLow => doubleFieldValue(
      secondaryCustomTargetValueLowFieldNum,
      0,
      const NamedSelector('secondary_custom_target_speed_low'));

  void setSecondaryCustomTargetSpeedLow(double? value) => setFieldValue(
      secondaryCustomTargetValueLowFieldNum,
      value,
      0,
      const NamedSelector('secondary_custom_target_speed_low'));

  /// secondary_custom_target_heart_rate_low: what secondary_custom_target_value_low means when this message selects it.
  int? get secondaryCustomTargetHeartRateLow => intFieldValue(
      secondaryCustomTargetValueLowFieldNum,
      0,
      const NamedSelector('secondary_custom_target_heart_rate_low'));

  void setSecondaryCustomTargetHeartRateLow(int? value) => setFieldValue(
      secondaryCustomTargetValueLowFieldNum,
      value,
      0,
      const NamedSelector('secondary_custom_target_heart_rate_low'));

  /// secondary_custom_target_cadence_low: what secondary_custom_target_value_low means when this message selects it.
  int? get secondaryCustomTargetCadenceLow => intFieldValue(
      secondaryCustomTargetValueLowFieldNum,
      0,
      const NamedSelector('secondary_custom_target_cadence_low'));

  void setSecondaryCustomTargetCadenceLow(int? value) => setFieldValue(
      secondaryCustomTargetValueLowFieldNum,
      value,
      0,
      const NamedSelector('secondary_custom_target_cadence_low'));

  /// secondary_custom_target_power_low: what secondary_custom_target_value_low means when this message selects it.
  int? get secondaryCustomTargetPowerLow => intFieldValue(
      secondaryCustomTargetValueLowFieldNum,
      0,
      const NamedSelector('secondary_custom_target_power_low'));

  void setSecondaryCustomTargetPowerLow(int? value) => setFieldValue(
      secondaryCustomTargetValueLowFieldNum,
      value,
      0,
      const NamedSelector('secondary_custom_target_power_low'));

  static const int secondaryCustomTargetValueHighFieldNum = 22;

  /// secondary_custom_target_value_high.
  int? get secondaryCustomTargetValueHigh =>
      intFieldValue(secondaryCustomTargetValueHighFieldNum);

  set secondaryCustomTargetValueHigh(int? value) =>
      setFieldValue(secondaryCustomTargetValueHighFieldNum, value);

  /// secondary_custom_target_speed_high: what secondary_custom_target_value_high means when this message selects it.
  double? get secondaryCustomTargetSpeedHigh => doubleFieldValue(
      secondaryCustomTargetValueHighFieldNum,
      0,
      const NamedSelector('secondary_custom_target_speed_high'));

  void setSecondaryCustomTargetSpeedHigh(double? value) => setFieldValue(
      secondaryCustomTargetValueHighFieldNum,
      value,
      0,
      const NamedSelector('secondary_custom_target_speed_high'));

  /// secondary_custom_target_heart_rate_high: what secondary_custom_target_value_high means when this message selects it.
  int? get secondaryCustomTargetHeartRateHigh => intFieldValue(
      secondaryCustomTargetValueHighFieldNum,
      0,
      const NamedSelector('secondary_custom_target_heart_rate_high'));

  void setSecondaryCustomTargetHeartRateHigh(int? value) => setFieldValue(
      secondaryCustomTargetValueHighFieldNum,
      value,
      0,
      const NamedSelector('secondary_custom_target_heart_rate_high'));

  /// secondary_custom_target_cadence_high: what secondary_custom_target_value_high means when this message selects it.
  int? get secondaryCustomTargetCadenceHigh => intFieldValue(
      secondaryCustomTargetValueHighFieldNum,
      0,
      const NamedSelector('secondary_custom_target_cadence_high'));

  void setSecondaryCustomTargetCadenceHigh(int? value) => setFieldValue(
      secondaryCustomTargetValueHighFieldNum,
      value,
      0,
      const NamedSelector('secondary_custom_target_cadence_high'));

  /// secondary_custom_target_power_high: what secondary_custom_target_value_high means when this message selects it.
  int? get secondaryCustomTargetPowerHigh => intFieldValue(
      secondaryCustomTargetValueHighFieldNum,
      0,
      const NamedSelector('secondary_custom_target_power_high'));

  void setSecondaryCustomTargetPowerHigh(int? value) => setFieldValue(
      secondaryCustomTargetValueHighFieldNum,
      value,
      0,
      const NamedSelector('secondary_custom_target_power_high'));

  /// The profile definition of every field of this message, with no values.
  ///
  /// Dart initialises a `static final` the first time it is read, so the
  /// decoder pays for a message type it never meets nothing. Handed out only as
  /// copies, by [Factory].
  static final Map<int, Field> prototypeFields = _buildPrototypeFields();

  static Map<int, Field> _buildPrototypeFields() {
    final fields = <int, Field>{};
    fields[254] =
        Field('message_index', 254, BaseType.uint16, 1.0, 0.0, '', false);
    fields[0] = Field('wkt_step_name', 0, BaseType.string, 1.0, 0.0, '', false);
    fields[1] =
        Field('duration_type', 1, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[2] = Field('duration_value', 2, BaseType.uint32, 1.0, 0.0, '', false)
      ..addSubField(SubField('duration_time', BaseType.uint32, 1000.0, 0.0, 's')
        ..addMap(1, 0)
        ..addMap(1, 28))
      ..addSubField(
          SubField('duration_distance', BaseType.uint32, 100.0, 0.0, 'm')
            ..addMap(1, 1))
      ..addSubField(
          SubField('duration_hr', BaseType.uint32, 1.0, 0.0, '% or bpm')
            ..addMap(1, 2)
            ..addMap(1, 3))
      ..addSubField(
          SubField('duration_calories', BaseType.uint32, 1.0, 0.0, 'calories')
            ..addMap(1, 4))
      ..addSubField(SubField('duration_step', BaseType.uint32, 1.0, 0.0, '')
        ..addMap(1, 6)
        ..addMap(1, 7)
        ..addMap(1, 8)
        ..addMap(1, 9)
        ..addMap(1, 10)
        ..addMap(1, 11)
        ..addMap(1, 12)
        ..addMap(1, 13))
      ..addSubField(
          SubField('duration_power', BaseType.uint32, 1.0, 0.0, '% or watts')
            ..addMap(1, 14)
            ..addMap(1, 15))
      ..addSubField(SubField('duration_reps', BaseType.uint32, 1.0, 0.0, '')
        ..addMap(1, 29));
    fields[3] = Field('target_type', 3, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[4] = Field('target_value', 4, BaseType.uint32, 1.0, 0.0, '', false)
      ..addSubField(SubField('target_speed_zone', BaseType.uint32, 1.0, 0.0, '')
        ..addMap(3, 0))
      ..addSubField(SubField('target_hr_zone', BaseType.uint32, 1.0, 0.0, '')
        ..addMap(3, 1))
      ..addSubField(
          SubField('target_cadence_zone', BaseType.uint32, 1.0, 0.0, '')
            ..addMap(3, 3))
      ..addSubField(SubField('target_power_zone', BaseType.uint32, 1.0, 0.0, '')
        ..addMap(3, 4))
      ..addSubField(
          SubField('repeat_steps', BaseType.uint32, 1.0, 0.0, '')..addMap(1, 6))
      ..addSubField(SubField('repeat_time', BaseType.uint32, 1000.0, 0.0, 's')
        ..addMap(1, 7))
      ..addSubField(
          SubField('repeat_distance', BaseType.uint32, 100.0, 0.0, 'm')
            ..addMap(1, 8))
      ..addSubField(
          SubField('repeat_calories', BaseType.uint32, 1.0, 0.0, 'calories')
            ..addMap(1, 9))
      ..addSubField(SubField('repeat_hr', BaseType.uint32, 1.0, 0.0, '% or bpm')
        ..addMap(1, 10)
        ..addMap(1, 11))
      ..addSubField(
          SubField('repeat_power', BaseType.uint32, 1.0, 0.0, '% or watts')
            ..addMap(1, 12)
            ..addMap(1, 13))
      ..addSubField(
          SubField('target_stroke_type', BaseType.fitEnum, 1.0, 0.0, '')
            ..addMap(3, 11));
    fields[5] = Field(
        'custom_target_value_low', 5, BaseType.uint32, 1.0, 0.0, '', false)
      ..addSubField(SubField(
          'custom_target_speed_low', BaseType.uint32, 1000.0, 0.0, 'm/s')
        ..addMap(3, 0))
      ..addSubField(SubField(
          'custom_target_heart_rate_low', BaseType.uint32, 1.0, 0.0, '% or bpm')
        ..addMap(3, 1))
      ..addSubField(SubField(
          'custom_target_cadence_low', BaseType.uint32, 1.0, 0.0, 'rpm')
        ..addMap(3, 3))
      ..addSubField(SubField(
          'custom_target_power_low', BaseType.uint32, 1.0, 0.0, '% or watts')
        ..addMap(3, 4));
    fields[6] = Field(
        'custom_target_value_high', 6, BaseType.uint32, 1.0, 0.0, '', false)
      ..addSubField(SubField(
          'custom_target_speed_high', BaseType.uint32, 1000.0, 0.0, 'm/s')
        ..addMap(3, 0))
      ..addSubField(SubField('custom_target_heart_rate_high', BaseType.uint32,
          1.0, 0.0, '% or bpm')
        ..addMap(3, 1))
      ..addSubField(SubField(
          'custom_target_cadence_high', BaseType.uint32, 1.0, 0.0, 'rpm')
        ..addMap(3, 3))
      ..addSubField(SubField(
          'custom_target_power_high', BaseType.uint32, 1.0, 0.0, '% or watts')
        ..addMap(3, 4));
    fields[7] = Field('intensity', 7, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[8] = Field('notes', 8, BaseType.string, 1.0, 0.0, '', false);
    fields[9] = Field('equipment', 9, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[10] =
        Field('exercise_category', 10, BaseType.uint16, 1.0, 0.0, '', false);
    fields[11] =
        Field('exercise_name', 11, BaseType.uint16, 1.0, 0.0, '', false);
    fields[12] =
        Field('exercise_weight', 12, BaseType.uint16, 100.0, 0.0, 'kg', false);
    fields[13] =
        Field('weight_display_unit', 13, BaseType.uint16, 1.0, 0.0, '', false);
    fields[19] = Field(
        'secondary_target_type', 19, BaseType.fitEnum, 1.0, 0.0, '', false);
    fields[20] = Field(
        'secondary_target_value', 20, BaseType.uint32, 1.0, 0.0, '', false)
      ..addSubField(
          SubField('secondary_target_speed_zone', BaseType.uint32, 1.0, 0.0, '')
            ..addMap(19, 0))
      ..addSubField(
          SubField('secondary_target_hr_zone', BaseType.uint32, 1.0, 0.0, '')
            ..addMap(19, 1))
      ..addSubField(SubField(
          'secondary_target_cadence_zone', BaseType.uint32, 1.0, 0.0, '')
        ..addMap(19, 3))
      ..addSubField(
          SubField('secondary_target_power_zone', BaseType.uint32, 1.0, 0.0, '')
            ..addMap(19, 4))
      ..addSubField(SubField(
          'secondary_target_stroke_type', BaseType.fitEnum, 1.0, 0.0, '')
        ..addMap(19, 11));
    fields[21] = Field('secondary_custom_target_value_low', 21, BaseType.uint32,
        1.0, 0.0, '', false)
      ..addSubField(SubField('secondary_custom_target_speed_low',
          BaseType.uint32, 1000.0, 0.0, 'm/s')
        ..addMap(19, 0))
      ..addSubField(SubField('secondary_custom_target_heart_rate_low',
          BaseType.uint32, 1.0, 0.0, '% or bpm')
        ..addMap(19, 1))
      ..addSubField(SubField('secondary_custom_target_cadence_low',
          BaseType.uint32, 1.0, 0.0, 'rpm')
        ..addMap(19, 3))
      ..addSubField(SubField('secondary_custom_target_power_low',
          BaseType.uint32, 1.0, 0.0, '% or watts')
        ..addMap(19, 4));
    fields[22] = Field('secondary_custom_target_value_high', 22,
        BaseType.uint32, 1.0, 0.0, '', false)
      ..addSubField(SubField('secondary_custom_target_speed_high',
          BaseType.uint32, 1000.0, 0.0, 'm/s')
        ..addMap(19, 0))
      ..addSubField(SubField('secondary_custom_target_heart_rate_high',
          BaseType.uint32, 1.0, 0.0, '% or bpm')
        ..addMap(19, 1))
      ..addSubField(SubField('secondary_custom_target_cadence_high',
          BaseType.uint32, 1.0, 0.0, 'rpm')
        ..addMap(19, 3))
      ..addSubField(SubField('secondary_custom_target_power_high',
          BaseType.uint32, 1.0, 0.0, '% or watts')
        ..addMap(19, 4));
    return fields;
  }
}
