/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// Named values for the FIT profile type `auto_activity_detect`.
///
/// This type is not modelled as an enum: it is a bit mask or a scalar with named
/// thresholds, so values outside the list below are meaningful.
abstract final class AutoActivityDetectValues {
  static const int none = 0x00000000;
  static const int running = 0x00000001;
  static const int cycling = 0x00000002;
  static const int swimming = 0x00000004;
  static const int walking = 0x00000008;
  static const int elliptical = 0x00000020;
  static const int sedentary = 0x00000400;

  /// The FIT invalid sentinel for this type's base type.
  static const int invalid = 4294967295;
}
