/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `british_adjectival_grading_scale`.
enum BritishAdjectivalGradingScale {
  m(0), // M
  d(1), // D
  hD(2), // HD
  vD(3), // VD
  mS(4), // MS
  s(5), // S
  hS(6), // HS
  mVS(7), // MVS
  vS(8), // VS
  hVS(9), // HVS
  e1(10), // E1
  e2(11), // E2
  e3(12), // E3
  e4(13), // E4
  e5(14), // E5
  e6(15), // E6
  e7(16), // E7
  e8(17), // E8
  e9(18), // E9
  e10(19), // E10
  e11(20), // E11

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const BritishAdjectivalGradingScale(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, BritishAdjectivalGradingScale> _byValue = {
    for (final entry in BritishAdjectivalGradingScale.values)
      entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static BritishAdjectivalGradingScale fromValue(int value) =>
      _byValue[value] ?? BritishAdjectivalGradingScale.invalid;
}
