/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `carry_exercise_name`.
enum CarryExerciseName {
  barHolds(0),
  farmersWalk(1),
  farmersWalkOnToes(2),
  hexDumbbellHold(3),
  overheadCarry(4),
  dumbbellWaiterCarry(5),
  farmersCarryWalkLunge(6),
  farmersCarry(7),
  farmersCarryOnToes(8),

  /// Returned for any raw value not present in the profile.
  invalid(65535);

  const CarryExerciseName(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, CarryExerciseName> _byValue = {
    for (final entry in CarryExerciseName.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static CarryExerciseName fromValue(int value) =>
      _byValue[value] ?? CarryExerciseName.invalid;
}
