/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `ccr_setpoint_switch_mode`.
enum CcrSetpointSwitchMode {
  manual(0), // User switches setpoints manually
  automatic(1), // Switch automatically based on depth

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const CcrSetpointSwitchMode(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, CcrSetpointSwitchMode> _byValue = {
    for (final entry in CcrSetpointSwitchMode.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static CcrSetpointSwitchMode fromValue(int value) =>
      _byValue[value] ?? CcrSetpointSwitchMode.invalid;
}
