/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `crunch_exercise_name`.
enum CrunchExerciseName {
  bicycleCrunch(0),
  cableCrunch(1),
  circularArmCrunch(2),
  crossedArmsCrunch(3),
  weightedCrossedArmsCrunch(4),
  crossLegReverseCrunch(5),
  weightedCrossLegReverseCrunch(6),
  crunchChop(7),
  weightedCrunchChop(8),
  doubleCrunch(9),
  weightedDoubleCrunch(10),
  elbowToKneeCrunch(11),
  weightedElbowToKneeCrunch(12),
  flutterKicks(13),
  weightedFlutterKicks(14),
  foamRollerReverseCrunchOnBench(15),
  weightedFoamRollerReverseCrunchOnBench(16),
  foamRollerReverseCrunchWithDumbbell(17),
  foamRollerReverseCrunchWithMedicineBall(18),
  frogPress(19),
  hangingKneeRaiseObliqueCrunch(20),
  weightedHangingKneeRaiseObliqueCrunch(21),
  hipCrossover(22),
  weightedHipCrossover(23),
  hollowRock(24),
  weightedHollowRock(25),
  inclineReverseCrunch(26),
  weightedInclineReverseCrunch(27),
  kneelingCableCrunch(28),
  kneelingCrossCrunch(29),
  weightedKneelingCrossCrunch(30),
  kneelingObliqueCableCrunch(31),
  kneesToElbow(32),
  legExtensions(33),
  weightedLegExtensions(34),
  legLevers(35),
  mcgillCurlUp(36),
  weightedMcgillCurlUp(37),
  modifiedPilatesRollUpWithBall(38),
  weightedModifiedPilatesRollUpWithBall(39),
  pilatesCrunch(40),
  weightedPilatesCrunch(41),
  pilatesRollUpWithBall(42),
  weightedPilatesRollUpWithBall(43),
  raisedLegsCrunch(44),
  weightedRaisedLegsCrunch(45),
  reverseCrunch(46),
  weightedReverseCrunch(47),
  reverseCrunchOnABench(48),
  weightedReverseCrunchOnABench(49),
  reverseCurlAndLift(50),
  weightedReverseCurlAndLift(51),
  rotationalLift(52),
  weightedRotationalLift(53),
  seatedAlternatingReverseCrunch(54),
  weightedSeatedAlternatingReverseCrunch(55),
  seatedLegU(56),
  weightedSeatedLegU(57),
  sideToSideCrunchAndWeave(58),
  weightedSideToSideCrunchAndWeave(59),
  singleLegReverseCrunch(60),
  weightedSingleLegReverseCrunch(61),
  skaterCrunchCross(62),
  weightedSkaterCrunchCross(63),
  standingCableCrunch(64),
  standingSideCrunch(65),
  stepClimb(66),
  weightedStepClimb(67),
  swissBallCrunch(68),
  swissBallReverseCrunch(69),
  weightedSwissBallReverseCrunch(70),
  swissBallRussianTwist(71),
  weightedSwissBallRussianTwist(72),
  swissBallSideCrunch(73),
  weightedSwissBallSideCrunch(74),
  thoracicCrunchesOnFoamRoller(75),
  weightedThoracicCrunchesOnFoamRoller(76),
  tricepsCrunch(77),
  weightedBicycleCrunch(78),
  weightedCrunch(79),
  weightedSwissBallCrunch(80),
  toesToBar(81),
  weightedToesToBar(82),
  crunch(83),
  straightLegCrunchWithBall(84),
  legClimbCrunch(86),

  /// Returned for any raw value not present in the profile.
  invalid(65535);

  const CrunchExerciseName(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, CrunchExerciseName> _byValue = {
    for (final entry in CrunchExerciseName.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static CrunchExerciseName fromValue(int value) =>
      _byValue[value] ?? CrunchExerciseName.invalid;
}
