/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `display_measure`.
enum DisplayMeasure {
  metric(0),
  statute(1),
  nautical(2),

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const DisplayMeasure(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, DisplayMeasure> _byValue = {
    for (final entry in DisplayMeasure.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static DisplayMeasure fromValue(int value) =>
      _byValue[value] ?? DisplayMeasure.invalid;
}
