/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `ewbank_grading_scale`.
enum EwbankGradingScale {
  $4(0), // 4
  $5(1), // 5
  $6(2), // 6
  $7(3), // 7
  $8(4), // 8
  $9(5), // 9
  $10(6), // 10
  $11(7), // 11
  $12(8), // 12
  $13(9), // 13
  $14(10), // 14
  $15(11), // 15
  $16(12), // 16
  $17(13), // 17
  $18(14), // 18
  $19(15), // 19
  $20(16), // 20
  $21(17), // 21
  $22(18), // 22
  $23(19), // 23
  $24(20), // 24
  $25(21), // 25
  $26(22), // 26
  $27(23), // 27
  $28(24), // 28
  $29(25), // 29
  $30(26), // 30
  $31(27), // 31
  $32(28), // 32
  $33(29), // 33
  $34(30), // 34
  $35(31), // 35
  $36(32), // 36
  $37(33), // 37
  $38(34), // 38

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const EwbankGradingScale(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, EwbankGradingScale> _byValue = {
    for (final entry in EwbankGradingScale.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static EwbankGradingScale fromValue(int value) =>
      _byValue[value] ?? EwbankGradingScale.invalid;
}
