/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `exd_data_units`.
enum ExdDataUnits {
  noUnits(0),
  laps(1),
  milesPerHour(2),
  kilometersPerHour(3),
  feetPerHour(4),
  metersPerHour(5),
  degreesCelsius(6),
  degreesFarenheit(7),
  zone(8),
  gear(9),
  rpm(10),
  bpm(11),
  degrees(12),
  millimeters(13),
  meters(14),
  kilometers(15),
  feet(16),
  yards(17),
  kilofeet(18),
  miles(19),
  time(20),
  enumTurnType(21),
  percent(22),
  watts(23),
  wattsPerKilogram(24),
  enumBatteryStatus(25),
  enumBikeLightBeamAngleMode(26),
  enumBikeLightBatteryStatus(27),
  enumBikeLightNetworkConfigType(28),
  lights(29),
  seconds(30),
  minutes(31),
  hours(32),
  calories(33),
  kilojoules(34),
  milliseconds(35),
  secondPerMile(36),
  secondPerKilometer(37),
  centimeter(38),
  enumCoursePoint(39),
  bradians(40),
  enumSport(41),
  inchesHg(42),
  mmHg(43),
  mbars(44),
  hectoPascals(45),
  feetPerMin(46),
  metersPerMin(47),
  metersPerSec(48),
  eightCardinal(49),

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const ExdDataUnits(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, ExdDataUnits> _byValue = {
    for (final entry in ExdDataUnits.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static ExdDataUnits fromValue(int value) =>
      _byValue[value] ?? ExdDataUnits.invalid;
}
