/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `exd_display_type`.
enum ExdDisplayType {
  numerical(0),
  simple(1),
  graph(2),
  bar(3),
  circleGraph(4),
  virtualPartner(5),
  balance(6),
  stringList(7),
  string(8),
  simpleDynamicIcon(9),
  gauge(10),

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const ExdDisplayType(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, ExdDisplayType> _byValue = {
    for (final entry in ExdDisplayType.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static ExdDisplayType fromValue(int value) =>
      _byValue[value] ?? ExdDisplayType.invalid;
}
