/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `fit_base_type`.
enum FitBaseType {
  enum_(0),
  sint8(1),
  uint8(2),
  sint16(131),
  uint16(132),
  sint32(133),
  uint32(134),
  string(7),
  float32(136),
  float64(137),
  uint8z(10),
  uint16z(139),
  uint32z(140),
  byte(13),
  sint64(142),
  uint64(143),
  uint64z(144),

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const FitBaseType(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, FitBaseType> _byValue = {
    for (final entry in FitBaseType.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static FitBaseType fromValue(int value) =>
      _byValue[value] ?? FitBaseType.invalid;
}
