/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `font_grading_scale`.
enum FontGradingScale {
  $1(0), // 1
  $2(1), // 2
  $3(2), // 3
  $4(3), // 4
  $4Plus(4), // 4+
  $5(5), // 5
  $5Plus(6), // 5+
  $6a(7), // 6A
  $6aPlus(8), // 6A+
  $6b(9), // 6B
  $6bPlus(10), // 6B+
  $6c(11), // 6C
  $6cPlus(12), // 6C+
  $7a(13), // 7A
  $7aPlus(14), // 7A+
  $7b(15), // 7B
  $7bPlus(16), // 7B+
  $7c(17), // 7C
  $7cPlus(18), // 7C+
  $8a(19), // 8A
  $8aPlus(20), // 8A+
  $8b(21), // 8B
  $8bPlus(22), // 8B+
  $8c(23), // 8C
  $8cPlus(24), // 8C+
  $9a(25), // 9A

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const FontGradingScale(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, FontGradingScale> _byValue = {
    for (final entry in FontGradingScale.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static FontGradingScale fromValue(int value) =>
      _byValue[value] ?? FontGradingScale.invalid;
}
