/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `french_grading_scale`.
enum FrenchGradingScale {
  $1(0), // 1
  $2(1), // 2
  $3(2), // 3
  $4a(3), // 4a
  $4b(4), // 4b
  $4c(5), // 4c
  $5a(6), // 5a
  $5b(7), // 5b
  $5c(8), // 5c
  $6a(9), // 6a
  $6aPlus(10), // 6a+
  $6b(11), // 6b
  $6bPlus(12), // 6b+
  $6c(13), // 6c
  $6cPlus(14), // 6c+
  $7a(15), // 7a
  $7aPlus(16), // 7a+
  $7b(17), // 7b
  $7bPlus(18), // 7b+
  $7c(19), // 7c
  $7cPlus(20), // 7c+
  $8a(21), // 8a
  $8aPlus(22), // 8a+
  $8b(23), // 8b
  $8bPlus(24), // 8b+
  $8c(25), // 8c
  $8cPlus(26), // 8c+
  $9a(27), // 9a
  $9aPlus(28), // 9a+
  $9b(29), // 9b

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const FrenchGradingScale(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, FrenchGradingScale> _byValue = {
    for (final entry in FrenchGradingScale.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static FrenchGradingScale fromValue(int value) =>
      _byValue[value] ?? FrenchGradingScale.invalid;
}
