/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `hip_raise_exercise_name`.
enum HipRaiseExerciseName {
  barbellHipThrustOnFloor(0),
  barbellHipThrustWithBench(1),
  bentKneeSwissBallReverseHipRaise(2),
  weightedBentKneeSwissBallReverseHipRaise(3),
  bridgeWithLegExtension(4),
  weightedBridgeWithLegExtension(5),
  clamBridge(6),
  frontKickTabletop(7),
  weightedFrontKickTabletop(8),
  hipExtensionAndCross(9),
  weightedHipExtensionAndCross(10),
  hipRaise(11),
  weightedHipRaise(12),
  hipRaiseWithFeetOnSwissBall(13),
  weightedHipRaiseWithFeetOnSwissBall(14),
  hipRaiseWithHeadOnBosuBall(15),
  weightedHipRaiseWithHeadOnBosuBall(16),
  hipRaiseWithHeadOnSwissBall(17),
  weightedHipRaiseWithHeadOnSwissBall(18),
  hipRaiseWithKneeSqueeze(19),
  weightedHipRaiseWithKneeSqueeze(20),
  inclineRearLegExtension(21),
  weightedInclineRearLegExtension(22),
  kettlebellSwing(23),
  marchingHipRaise(24),
  weightedMarchingHipRaise(25),
  marchingHipRaiseWithFeetOnASwissBall(26),
  weightedMarchingHipRaiseWithFeetOnASwissBall(27),
  reverseHipRaise(28),
  weightedReverseHipRaise(29),
  singleLegHipRaise(30),
  weightedSingleLegHipRaise(31),
  singleLegHipRaiseWithFootOnBench(32),
  weightedSingleLegHipRaiseWithFootOnBench(33),
  singleLegHipRaiseWithFootOnBosuBall(34),
  weightedSingleLegHipRaiseWithFootOnBosuBall(35),
  singleLegHipRaiseWithFootOnFoamRoller(36),
  weightedSingleLegHipRaiseWithFootOnFoamRoller(37),
  singleLegHipRaiseWithFootOnMedicineBall(38),
  weightedSingleLegHipRaiseWithFootOnMedicineBall(39),
  singleLegHipRaiseWithHeadOnBosuBall(40),
  weightedSingleLegHipRaiseWithHeadOnBosuBall(41),
  weightedClamBridge(42),
  singleLegSwissBallHipRaiseAndLegCurl(43),
  clams(44),
  innerThighCircles(45), // Deprecated do not use
  innerThighSideLift(46), // Deprecated do not use
  legCircles(47),
  legLift(48),
  legLiftInExternalRotation(49),

  /// Returned for any raw value not present in the profile.
  invalid(65535);

  const HipRaiseExerciseName(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, HipRaiseExerciseName> _byValue = {
    for (final entry in HipRaiseExerciseName.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static HipRaiseExerciseName fromValue(int value) =>
      _byValue[value] ?? HipRaiseExerciseName.invalid;
}
