/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `hrv_status`.
enum HrvStatus {
  none(0),
  poor(1),
  low(2),
  unbalanced(3),
  balanced(4),

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const HrvStatus(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, HrvStatus> _byValue = {
    for (final entry in HrvStatus.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static HrvStatus fromValue(int value) => _byValue[value] ?? HrvStatus.invalid;
}
