/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `indoor_row_exercise_name`.
enum IndoorRowExerciseName {
  rowingMachine(0),

  /// Returned for any raw value not present in the profile.
  invalid(65535);

  const IndoorRowExerciseName(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, IndoorRowExerciseName> _byValue = {
    for (final entry in IndoorRowExerciseName.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static IndoorRowExerciseName fromValue(int value) =>
      _byValue[value] ?? IndoorRowExerciseName.invalid;
}
