/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `language_bits_4`.
enum LanguageBits4 {
  brazilianPortuguese(0x01),
  indonesian(0x02),
  malaysian(0x04),
  vietnamese(0x08),
  burmese(0x10),
  mongolian(0x20),

  /// Returned for any raw value not present in the profile.
  invalid(0);

  const LanguageBits4(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, LanguageBits4> _byValue = {
    for (final entry in LanguageBits4.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static LanguageBits4 fromValue(int value) =>
      _byValue[value] ?? LanguageBits4.invalid;
}
