/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `language`.
enum Language {
  english(0),
  french(1),
  italian(2),
  german(3),
  spanish(4),
  croatian(5),
  czech(6),
  danish(7),
  dutch(8),
  finnish(9),
  greek(10),
  hungarian(11),
  norwegian(12),
  polish(13),
  portuguese(14),
  slovakian(15),
  slovenian(16),
  swedish(17),
  russian(18),
  turkish(19),
  latvian(20),
  ukrainian(21),
  arabic(22),
  farsi(23),
  bulgarian(24),
  romanian(25),
  chinese(26),
  japanese(27),
  korean(28),
  taiwanese(29),
  thai(30),
  hebrew(31),
  brazilianPortuguese(32),
  indonesian(33),
  malaysian(34),
  vietnamese(35),
  burmese(36),
  mongolian(37),
  custom(254),

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const Language(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, Language> _byValue = {
    for (final entry in Language.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static Language fromValue(int value) => _byValue[value] ?? Language.invalid;
}
