/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `lap_trigger`.
enum LapTrigger {
  manual(0),
  time(1),
  distance(2),
  positionStart(3),
  positionLap(4),
  positionWaypoint(5),
  positionMarked(6),
  sessionEnd(7),
  fitnessEquipment(8),

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const LapTrigger(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, LapTrigger> _byValue = {
    for (final entry in LapTrigger.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static LapTrigger fromValue(int value) =>
      _byValue[value] ?? LapTrigger.invalid;
}
