/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// Named values for the FIT profile type `left_right_balance`.
///
/// This type is not modelled as an enum: it is a bit mask or a scalar with named
/// thresholds, so values outside the list below are meaningful.
abstract final class LeftRightBalanceValues {
  static const int mask = 0x7F; // % contribution
  static const int right =
      0x80; // data corresponds to right if set, otherwise unknown

  /// The FIT invalid sentinel for this type's base type.
  static const int invalid = 255;
}
