/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// Named values for the FIT profile type `local_date_time`.
///
/// seconds since 00:00 Dec 31 1989 in local time zone
///
/// This type is not modelled as an enum: it is a bit mask or a scalar with named
/// thresholds, so values outside the list below are meaningful.
abstract final class LocalDateTimeValues {
  static const int min =
      0x10000000; // if date_time is < 0x10000000 then it is system time (seconds from device power on)

  /// The FIT invalid sentinel for this type's base type.
  static const int invalid = 4294967295;
}
