/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// Named values for the FIT profile type `localtime_into_day`.
///
/// number of seconds into the day since local 00:00:00
///
/// This type is not modelled as an enum: it is a bit mask or a scalar with named
/// thresholds, so values outside the list below are meaningful.
abstract final class LocaltimeIntoDayValues {
  /// The FIT invalid sentinel for this type's base type.
  static const int invalid = 4294967295;
}
