/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `move_exercise_name`.
enum MoveExerciseName {
  archAndCurl(0),
  armCirclesWithBallBandAndWeight(1),
  armStretch(2),
  backMassage(3),
  bellyBreathing(4),
  bridgeWithBall(5),
  diamondLegCrunch(6),
  diamondLegLift(7),
  eightPointShoulderOpener(8),
  footRolling(9),
  footwork(10),
  footworkOnDisc(11),
  forwardFold(12),
  frogWithBand(13),
  halfRollUp(14),
  hamstringCurl(15),
  hamstringStretch(16),
  hipStretch(17),
  hugATreeWithBallBandAndWeight(18),
  kneeCircles(19),
  kneeFoldsOnDisc(20),
  lateralFlexion(21),
  legStretchWithBand(22),
  legStretchWithLegCircles(23),
  lowerLiftOnDisc(24),
  lungeSquat(25),
  lungesWithKneeLift(26),
  mermaidStretch(27),
  neutralPelvicPosition(28),
  pelvicClocksOnDisc(29),
  pilatesPlieSquatsParallelTurnedOutFlatAndHeelsWithChair(30),
  piriformisStretch(31),
  plankKneeCrosses(32),
  plankKneePulls(33),
  plankUpDowns(34),
  prayerMudra(35),
  psoasLungeStretch(36),
  ribcageBreathing(37),
  rollDown(38),
  rollUpWithWeightAndBand(39),
  saw(40),
  scapularStabilization(41),
  scissorsOnDisc(42),
  seatedHipStretchup(43),
  seatedTwist(44),
  shavingTheHeadWithBallBandAndWeight(45),
  spinalTwist(46),
  spinalTwistStretch(47),
  spineStretchForward(48),
  squatOpenArmTwistPose(49),
  squatsWithBall(50),
  standAndHang(51),
  standingSideStretch(52),
  standingSingleLegForwardBendWithItBandOpener(53),
  straightLegCrunchWithLegLift(54),
  straightLegCrunchWithLegLiftWithBall(55),
  straightLegCrunchWithLegsCrossed(56),
  straightLegCrunchWithLegsCrossedWithBall(57),
  straightLegDiagonalCrunch(58),
  straightLegDiagonalCrunchWithBall(59),
  tailboneCurl(60),
  throatLock(61),
  tickTockSideRoll(62),
  twist(63),
  vLegCrunches(64),
  vSit(65),
  forwardFoldWheelchair(66),
  forwardFoldPlusWheelchair(67),
  armCirclesLowForwardWheelchair(68),
  armCirclesMidForwardWheelchair(69),
  armCirclesHighForwardWheelchair(70),
  armCirclesLowBackwardWheelchair(71),
  armCirclesMidBackwardWheelchair(72),
  armCirclesHighBackwardWheelchair(73),
  coreTwistsWheelchair(74),
  armRaiseWheelchair(75),
  chestExpandWheelchair(76),
  armExtendWheelchair(77),
  forwardBendWheelchair(78),
  toeTouchWheelchair(79),
  extendedToeTouchWheelchair(80),
  seatedArmCircles(81),
  trunkRotations(82),
  seatedTrunkRotations(83),
  toeTouch(84),

  /// Returned for any raw value not present in the profile.
  invalid(65535);

  const MoveExerciseName(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, MoveExerciseName> _byValue = {
    for (final entry in MoveExerciseName.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static MoveExerciseName fromValue(int value) =>
      _byValue[value] ?? MoveExerciseName.invalid;
}
