/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `nap_period_feedback`.
enum NapPeriodFeedback {
  none(0),
  multipleNapsDuringDay(1),
  jetlagIdealTimingIdealDuration(2),
  jetlagIdealTimingLongDuration(3),
  jetlagLateTimingIdealDuration(4),
  jetlagLateTimingLongDuration(5),
  idealTimingIdealDurationLowNeed(6),
  idealTimingIdealDurationHighNeed(7),
  idealTimingLongDurationLowNeed(8),
  idealTimingLongDurationHighNeed(9),
  lateTimingIdealDurationLowNeed(10),
  lateTimingIdealDurationHighNeed(11),
  lateTimingLongDurationLowNeed(12),
  lateTimingLongDurationHighNeed(13),
  idealDurationLowNeed(14),
  idealDurationHighNeed(15),
  longDurationLowNeed(16),
  longDurationHighNeed(17),

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const NapPeriodFeedback(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, NapPeriodFeedback> _byValue = {
    for (final entry in NapPeriodFeedback.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static NapPeriodFeedback fromValue(int value) =>
      _byValue[value] ?? NapPeriodFeedback.invalid;
}
