/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `push_up_exercise_name`.
enum PushUpExerciseName {
  chestPressWithBand(0),
  alternatingStaggeredPushUp(1),
  weightedAlternatingStaggeredPushUp(2),
  alternatingHandsMedicineBallPushUp(3),
  weightedAlternatingHandsMedicineBallPushUp(4),
  bosuBallPushUp(5),
  weightedBosuBallPushUp(6),
  clappingPushUp(7),
  weightedClappingPushUp(8),
  closeGripMedicineBallPushUp(9),
  weightedCloseGripMedicineBallPushUp(10),
  closeHandsPushUp(11),
  weightedCloseHandsPushUp(12),
  declinePushUp(13),
  weightedDeclinePushUp(14),
  diamondPushUp(15),
  weightedDiamondPushUp(16),
  explosiveCrossoverPushUp(17),
  weightedExplosiveCrossoverPushUp(18),
  explosivePushUp(19),
  weightedExplosivePushUp(20),
  feetElevatedSideToSidePushUp(21),
  weightedFeetElevatedSideToSidePushUp(22),
  handReleasePushUp(23),
  weightedHandReleasePushUp(24),
  handstandPushUp(25),
  weightedHandstandPushUp(26),
  inclinePushUp(27),
  weightedInclinePushUp(28),
  isometricExplosivePushUp(29),
  weightedIsometricExplosivePushUp(30),
  judoPushUp(31),
  weightedJudoPushUp(32),
  kneelingPushUp(33),
  weightedKneelingPushUp(34),
  medicineBallChestPass(35),
  medicineBallPushUp(36),
  weightedMedicineBallPushUp(37),
  oneArmPushUp(38),
  weightedOneArmPushUp(39),
  weightedPushUp(40),
  pushUpAndRow(41),
  weightedPushUpAndRow(42),
  pushUpPlus(43),
  weightedPushUpPlus(44),
  pushUpWithFeetOnSwissBall(45),
  weightedPushUpWithFeetOnSwissBall(46),
  pushUpWithOneHandOnMedicineBall(47),
  weightedPushUpWithOneHandOnMedicineBall(48),
  shoulderPushUp(49),
  weightedShoulderPushUp(50),
  singleArmMedicineBallPushUp(51),
  weightedSingleArmMedicineBallPushUp(52),
  spidermanPushUp(53),
  weightedSpidermanPushUp(54),
  stackedFeetPushUp(55),
  weightedStackedFeetPushUp(56),
  staggeredHandsPushUp(57),
  weightedStaggeredHandsPushUp(58),
  suspendedPushUp(59),
  weightedSuspendedPushUp(60),
  swissBallPushUp(61),
  weightedSwissBallPushUp(62),
  swissBallPushUpPlus(63),
  weightedSwissBallPushUpPlus(64),
  tPushUp(65),
  weightedTPushUp(66),
  tripleStopPushUp(67),
  weightedTripleStopPushUp(68),
  wideHandsPushUp(69),
  weightedWideHandsPushUp(70),
  paralletteHandstandPushUp(71),
  weightedParalletteHandstandPushUp(72),
  ringHandstandPushUp(73),
  weightedRingHandstandPushUp(74),
  ringPushUp(75),
  weightedRingPushUp(76),
  pushUp(77),
  pilatesPushup(78),
  dynamicPushUp(79),
  kippingHandstandPushUp(80),
  shoulderTappingPushUp(81),
  bicepsPushUp(82),
  hinduPushUp(83),
  pikePushUp(84),
  wideGripPushUp(85),
  weightedBicepsPushUp(86),
  weightedHinduPushUp(87),
  weightedPikePushUp(88),
  kippingParalletteHandstandPushUp(89),
  wallPushUp(90),

  /// Returned for any raw value not present in the profile.
  invalid(65535);

  const PushUpExerciseName(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, PushUpExerciseName> _byValue = {
    for (final entry in PushUpExerciseName.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static PushUpExerciseName fromValue(int value) =>
      _byValue[value] ?? PushUpExerciseName.invalid;
}
