/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `radar_threat_level_type`.
enum RadarThreatLevelType {
  threatUnknown(0),
  threatNone(1),
  threatApproaching(2),
  threatApproachingFast(3),

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const RadarThreatLevelType(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, RadarThreatLevelType> _byValue = {
    for (final entry in RadarThreatLevelType.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static RadarThreatLevelType fromValue(int value) =>
      _byValue[value] ?? RadarThreatLevelType.invalid;
}
