/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `row_exercise_name`.
enum RowExerciseName {
  barbellStraightLegDeadliftToRow(0),
  cableRowStanding(1),
  dumbbellRow(2),
  elevatedFeetInvertedRow(3),
  weightedElevatedFeetInvertedRow(4),
  facePull(5),
  facePullWithExternalRotation(6),
  invertedRowWithFeetOnSwissBall(7),
  weightedInvertedRowWithFeetOnSwissBall(8),
  kettlebellRow(9),
  modifiedInvertedRow(10),
  weightedModifiedInvertedRow(11),
  neutralGripAlternatingDumbbellRow(12),
  oneArmBentOverRow(13),
  oneLeggedDumbbellRow(14),
  renegadeRow(15),
  reverseGripBarbellRow(16),
  ropeHandleCableRow(17),
  seatedCableRow(18),
  seatedDumbbellRow(19),
  singleArmCableRow(20),
  singleArmCableRowAndRotation(21),
  singleArmInvertedRow(22),
  weightedSingleArmInvertedRow(23),
  singleArmNeutralGripDumbbellRow(24),
  singleArmNeutralGripDumbbellRowAndRotation(25),
  suspendedInvertedRow(26),
  weightedSuspendedInvertedRow(27),
  tBarRow(28),
  towelGripInvertedRow(29),
  weightedTowelGripInvertedRow(30),
  underhandGripCableRow(31),
  vGripCableRow(32),
  wideGripSeatedCableRow(33),
  alternatingDumbbellRow(34),
  invertedRow(35),
  row(36),
  weightedRow(37),
  indoorRow(38),
  bandedFacePulls(39),
  chestSupportedDumbbellRow(40),
  declineRingRow(41),
  elevatedRingRow(42),
  rdlBentOverRowWithBarbellDumbbell(43),
  ringRow(44),
  barbellRow(45),
  bentOverRowWithBarbell(46),
  bentOverRowWithDumbell(47),
  seatedUnderhandGripCableRow(48),
  trxInvertedRow(49),
  weightedInvertedRow(50),
  weightedTrxInvertedRow(51),
  dumbbellRowWheelchair(52),

  /// Returned for any raw value not present in the profile.
  invalid(65535);

  const RowExerciseName(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, RowExerciseName> _byValue = {
    for (final entry in RowExerciseName.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static RowExerciseName fromValue(int value) =>
      _byValue[value] ?? RowExerciseName.invalid;
}
