/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `run_exercise_name`.
enum RunExerciseName {
  run(0),
  walk(1),
  jog(2),
  sprint(3),
  runOrWalk(4),
  speedWalk(5),
  warmUp(6),

  /// Returned for any raw value not present in the profile.
  invalid(65535);

  const RunExerciseName(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, RunExerciseName> _byValue = {
    for (final entry in RunExerciseName.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static RunExerciseName fromValue(int value) =>
      _byValue[value] ?? RunExerciseName.invalid;
}
