/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `shoulder_stability_exercise_name`.
enum ShoulderStabilityExerciseName {
  $90DegreeCableExternalRotation(0),
  bandExternalRotation(1),
  bandInternalRotation(2),
  bentArmLateralRaiseAndExternalRotation(3),
  cableExternalRotation(4),
  dumbbellFacePullWithExternalRotation(5),
  floorIRaise(6),
  weightedFloorIRaise(7),
  floorTRaise(8),
  weightedFloorTRaise(9),
  floorYRaise(10),
  weightedFloorYRaise(11),
  inclineIRaise(12),
  weightedInclineIRaise(13),
  inclineLRaise(14),
  weightedInclineLRaise(15),
  inclineTRaise(16),
  weightedInclineTRaise(17),
  inclineWRaise(18),
  weightedInclineWRaise(19),
  inclineYRaise(20),
  weightedInclineYRaise(21),
  lyingExternalRotation(22),
  seatedDumbbellExternalRotation(23),
  standingLRaise(24),
  swissBallIRaise(25),
  weightedSwissBallIRaise(26),
  swissBallTRaise(27),
  weightedSwissBallTRaise(28),
  swissBallWRaise(29),
  weightedSwissBallWRaise(30),
  swissBallYRaise(31),
  weightedSwissBallYRaise(32),
  cableInternalRotation(33),
  lyingInternalRotation(34),
  seatedDumbbellInternalRotation(35),

  /// Returned for any raw value not present in the profile.
  invalid(65535);

  const ShoulderStabilityExerciseName(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, ShoulderStabilityExerciseName> _byValue = {
    for (final entry in ShoulderStabilityExerciseName.values)
      entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static ShoulderStabilityExerciseName fromValue(int value) =>
      _byValue[value] ?? ShoulderStabilityExerciseName.invalid;
}
