/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `sit_up_exercise_name`.
enum SitUpExerciseName {
  alternatingSitUp(0),
  weightedAlternatingSitUp(1),
  bentKneeVUp(2),
  weightedBentKneeVUp(3),
  butterflySitUp(4),
  weightedButterflySitup(5),
  crossPunchRollUp(6),
  weightedCrossPunchRollUp(7),
  crossedArmsSitUp(8),
  weightedCrossedArmsSitUp(9),
  getUpSitUp(10),
  weightedGetUpSitUp(11),
  hoveringSitUp(12),
  weightedHoveringSitUp(13),
  kettlebellSitUp(14),
  medicineBallAlternatingVUp(15),
  medicineBallSitUp(16),
  medicineBallVUp(17),
  modifiedSitUp(18),
  negativeSitUp(19),
  oneArmFullSitUp(20),
  recliningCircle(21),
  weightedRecliningCircle(22),
  reverseCurlUp(23),
  weightedReverseCurlUp(24),
  singleLegSwissBallJackknife(25),
  weightedSingleLegSwissBallJackknife(26),
  theTeaser(27),
  theTeaserWeighted(28),
  threePartRollDown(29),
  weightedThreePartRollDown(30),
  vUp(31),
  weightedVUp(32),
  weightedRussianTwistOnSwissBall(33),
  weightedSitUp(34),
  xAbs(35),
  weightedXAbs(36),
  sitUp(37),
  ghdSitUps(38),
  sitUpTurkishGetUp(39),
  russianTwistOnSwissBall(40),

  /// Returned for any raw value not present in the profile.
  invalid(65535);

  const SitUpExerciseName(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, SitUpExerciseName> _byValue = {
    for (final entry in SitUpExerciseName.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static SitUpExerciseName fromValue(int value) =>
      _byValue[value] ?? SitUpExerciseName.invalid;
}
