/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `sport_bits_0`.
///
/// Bit field corresponding to sport enum type (1 << sport).
enum SportBits0 {
  generic(0x01),
  running(0x02),
  cycling(0x04),
  transition(0x08), // Mulitsport transition
  fitnessEquipment(0x10),
  swimming(0x20),
  basketball(0x40),
  soccer(0x80),

  /// Returned for any raw value not present in the profile.
  invalid(0);

  const SportBits0(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, SportBits0> _byValue = {
    for (final entry in SportBits0.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static SportBits0 fromValue(int value) =>
      _byValue[value] ?? SportBits0.invalid;
}
