/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `sport`.
enum Sport {
  generic(0),
  running(1),
  cycling(2),
  transition(3), // Mulitsport transition
  fitnessEquipment(4),
  swimming(5),
  basketball(6),
  soccer(7),
  tennis(8),
  americanFootball(9),
  training(10),
  walking(11),
  crossCountrySkiing(12),
  alpineSkiing(13),
  snowboarding(14),
  rowing(15),
  mountaineering(16),
  hiking(17),
  multisport(18),
  paddling(19),
  flying(20),
  eBiking(21),
  motorcycling(22),
  boating(23),
  driving(24),
  golf(25),
  hangGliding(26),
  horsebackRiding(27),
  hunting(28),
  fishing(29),
  inlineSkating(30),
  rockClimbing(31),
  sailing(32),
  iceSkating(33),
  skyDiving(34),
  snowshoeing(35),
  snowmobiling(36),
  standUpPaddleboarding(37),
  surfing(38),
  wakeboarding(39),
  waterSkiing(40),
  kayaking(41),
  rafting(42),
  windsurfing(43),
  kitesurfing(44),
  tactical(45),
  jumpmaster(46),
  boxing(47),
  floorClimbing(48),
  baseball(49),
  diving(53),
  shooting(56), // Sport Shooting bits, set here for sport_bits alignment
  winterSport(58),
  grinding(
      59), // Sailing position, operating manual winches to power boat controls
  hiit(62),
  videoGaming(63),
  racket(64),
  wheelchairPushWalk(65),
  wheelchairPushRun(66),
  meditation(67),
  paraSport(68),
  discGolf(69),
  teamSport(70),
  cricket(71),
  rugby(72),
  hockey(73),
  lacrosse(74),
  volleyball(75),
  waterTubing(76),
  wakesurfing(77),
  waterSport(78),
  archery(79),
  mixedMartialArts(80),
  motorSports(81),
  snorkeling(82),
  dance(83),
  jumpRope(84),
  poolApnea(85),
  mobility(86),
  geocaching(87),
  canoeing(88),
  all(254), // All is for goals only to include all sports.

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const Sport(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, Sport> _byValue = {
    for (final entry in Sport.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static Sport fromValue(int value) => _byValue[value] ?? Sport.invalid;
}
