/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `sport_bits_3`.
///
/// Bit field corresponding to sport enum type (1 << (sport-24)).
enum SportBits3 {
  driving(0x01),
  golf(0x02),
  hangGliding(0x04),
  horsebackRiding(0x08),
  hunting(0x10),
  fishing(0x20),
  inlineSkating(0x40),
  rockClimbing(0x80),

  /// Returned for any raw value not present in the profile.
  invalid(0);

  const SportBits3(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, SportBits3> _byValue = {
    for (final entry in SportBits3.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static SportBits3 fromValue(int value) =>
      _byValue[value] ?? SportBits3.invalid;
}
