/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `sub_sport`.
enum SubSport {
  generic(0),
  treadmill(1), // Run/Fitness Equipment
  street(2), // Run
  trail(3), // Run
  track(4), // Run
  spin(5), // Cycling
  indoorCycling(6), // Cycling/Fitness Equipment
  road(7), // Cycling
  mountain(8), // Cycling
  downhill(9), // Cycling
  recumbent(10), // Cycling
  cyclocross(11), // Cycling
  handCycling(12), // Cycling
  trackCycling(13), // Cycling
  indoorRowing(14), // Fitness Equipment
  elliptical(15), // Fitness Equipment
  stairClimbing(16), // Fitness Equipment
  lapSwimming(17), // Swimming
  openWater(18), // Swimming
  flexibilityTraining(19), // Training
  strengthTraining(20), // Training
  warmUp(21), // Tennis
  match(22), // Tennis
  exercise(23), // Tennis
  challenge(24),
  indoorSkiing(25), // Fitness Equipment
  cardioTraining(26), // Training
  indoorWalking(27), // Walking/Fitness Equipment
  eBikeFitness(28), // E-Biking
  bmx(29), // Cycling
  casualWalking(30), // Walking
  speedWalking(31), // Walking
  bikeToRunTransition(32), // Transition
  runToBikeTransition(33), // Transition
  swimToBikeTransition(34), // Transition
  atv(35), // Motorcycling
  motocross(36), // Motorcycling
  backcountry(37), // Alpine Skiing/Snowboarding
  resort(38), // Alpine Skiing/Snowboarding
  rcDrone(39), // Flying
  wingsuit(40), // Flying
  whitewater(41), // Kayaking/Rafting
  skateSkiing(42), // Cross Country Skiing
  yoga(43), // Training
  pilates(44), // Fitness Equipment
  indoorRunning(45), // Run
  gravelCycling(46), // Cycling
  eBikeMountain(47), // Cycling
  commuting(48), // Cycling
  mixedSurface(49), // Cycling
  navigate(50),
  trackMe(51),
  map(52),
  singleGasDiving(53), // Diving
  multiGasDiving(54), // Diving
  gaugeDiving(55), // Diving
  apneaDiving(56), // Diving
  apneaHunting(57), // Diving
  virtualActivity(58),
  obstacle(
      59), // Used for events where participants run, crawl through mud, climb over walls, etc.
  breathing(62),
  ccrDiving(63), // Diving w/ closed circuit rebreather
  sailRace(65), // Sailing
  expedition(66), // Generic
  ultra(67), // Ultramarathon
  indoorClimbing(68), // Climbing
  bouldering(69), // Climbing
  hiit(70), // High Intensity Interval Training
  indoorGrinding(
      71), // Sailing position, operating manual winches to power boat controls
  huntingWithDogs(72), // Hunting
  amrap(73), // HIIT
  emom(74), // HIIT
  tabata(75), // HIIT
  esport(77), // Video Gaming, Cycling, etc.
  triathlon(78), // Multisport
  duathlon(79), // Multisport
  brick(80), // Multisport
  swimRun(81), // Multisport
  adventureRace(82), // Multisport/Running
  truckerWorkout(83), // DEZL trucker workout training sport
  pickleball(84), // Racket
  padel(85), // Racket
  indoorWheelchairWalk(86),
  indoorWheelchairRun(87),
  indoorHandCycling(88),
  field(90), // Hockey
  ice(91), // Hockey
  ultimate(92), // Disc
  platform(93), // Racket
  squash(94), // Racket
  badminton(95), // Racket
  racquetball(96), // Racket
  tableTennis(97), // Racket
  overland(98),
  trollingMotor(99), // Generic
  flyCanopy(110), // Flying
  flyParaglide(111), // Flying
  flyParamotor(112), // Flying
  flyPressurized(113), // Flying
  flyNavigate(114), // Flying
  flyTimer(115), // Flying
  flyAltimeter(116), // Flying
  flyWx(117), // Flying
  flyVfr(118), // Flying
  flyIfr(119), // Flying
  dynamicApnea(121),
  enduro(123), // Cycling
  rucking(124), // Hiking
  rally(125), // Motor sports
  poolTriathlon(126), // Multisport
  eBikeEnduro(127), // Cycling
  all(254),

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const SubSport(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, SubSport> _byValue = {
    for (final entry in SubSport.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static SubSport fromValue(int value) => _byValue[value] ?? SubSport.invalid;
}
