/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `supported_exd_screen_layouts`.
enum SupportedExdScreenLayouts {
  fullScreen(0x00000001),
  halfVertical(0x00000002),
  halfHorizontal(0x00000004),
  halfVerticalRightSplit(0x00000008),
  halfHorizontalBottomSplit(0x00000010),
  fullQuarterSplit(0x00000020),
  halfVerticalLeftSplit(0x00000040),
  halfHorizontalTopSplit(0x00000080),

  /// Returned for any raw value not present in the profile.
  invalid(0);

  const SupportedExdScreenLayouts(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, SupportedExdScreenLayouts> _byValue = {
    for (final entry in SupportedExdScreenLayouts.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static SupportedExdScreenLayouts fromValue(int value) =>
      _byValue[value] ?? SupportedExdScreenLayouts.invalid;
}
