/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `suspension_exercise_name`.
enum SuspensionExerciseName {
  chestFly(0),
  chestPress(1),
  crunch(2),
  curl(3),
  dip(4),
  facePull(5),
  gluteBridge(6),
  hamstringCurl(7),
  hipDrop(8),
  invertedRow(9),
  kneeDriveJump(10),
  kneeToChest(11),
  latPullover(12),
  lunge(13),
  mountainClimber(14),
  pendulum(15),
  pike(16),
  plank(17),
  powerPull(18),
  pullUp(19),
  pushUp(20),
  reverseMountainClimber(21),
  reversePlank(22),
  rollout(23),
  row(24),
  sideLunge(25),
  sidePlank(26),
  singleLegDeadlift(27),
  singleLegSquat(28),
  sitUp(29),
  split(30),
  squat(31),
  squatJump(32),
  tricepPress(33),
  yFly(34),

  /// Returned for any raw value not present in the profile.
  invalid(65535);

  const SuspensionExerciseName(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, SuspensionExerciseName> _byValue = {
    for (final entry in SuspensionExerciseName.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static SuspensionExerciseName fromValue(int value) =>
      _byValue[value] ?? SuspensionExerciseName.invalid;
}
