/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `time_zone`.
enum TimeZone {
  almaty(0),
  bangkok(1),
  bombay(2),
  brasilia(3),
  cairo(4),
  capeVerdeIs(5),
  darwin(6),
  eniwetok(7),
  fiji(8),
  hongKong(9),
  islamabad(10),
  kabul(11),
  magadan(12),
  midAtlantic(13),
  moscow(14),
  muscat(15),
  newfoundland(16),
  samoa(17),
  sydney(18),
  tehran(19),
  tokyo(20),
  usAlaska(21),
  usAtlantic(22),
  usCentral(23),
  usEastern(24),
  usHawaii(25),
  usMountain(26),
  usPacific(27),
  other(28),
  auckland(29),
  kathmandu(30),
  europeWesternWet(31),
  europeCentralCet(32),
  europeEasternEet(33),
  jakarta(34),
  perth(35),
  adelaide(36),
  brisbane(37),
  tasmania(38),
  iceland(39),
  amsterdam(40),
  athens(41),
  barcelona(42),
  berlin(43),
  brussels(44),
  budapest(45),
  copenhagen(46),
  dublin(47),
  helsinki(48),
  lisbon(49),
  london(50),
  madrid(51),
  munich(52),
  oslo(53),
  paris(54),
  prague(55),
  reykjavik(56),
  rome(57),
  stockholm(58),
  vienna(59),
  warsaw(60),
  zurich(61),
  quebec(62),
  ontario(63),
  manitoba(64),
  saskatchewan(65),
  alberta(66),
  britishColumbia(67),
  boise(68),
  boston(69),
  chicago(70),
  dallas(71),
  denver(72),
  kansasCity(73),
  lasVegas(74),
  losAngeles(75),
  miami(76),
  minneapolis(77),
  newYork(78),
  newOrleans(79),
  phoenix(80),
  santaFe(81),
  seattle(82),
  washingtonDc(83),
  usArizona(84),
  chita(85),
  ekaterinburg(86),
  irkutsk(87),
  kaliningrad(88),
  krasnoyarsk(89),
  novosibirsk(90),
  petropavlovskKamchatskiy(91),
  samara(92),
  vladivostok(93),
  mexicoCentral(94),
  mexicoMountain(95),
  mexicoPacific(96),
  capeTown(97),
  winkhoek(98),
  lagos(99),
  riyahd(100),
  venezuela(101),
  australiaLh(102),
  santiago(103),
  manual(253),
  automatic(254),

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const TimeZone(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, TimeZone> _byValue = {
    for (final entry in TimeZone.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static TimeZone fromValue(int value) => _byValue[value] ?? TimeZone.invalid;
}
