/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `total_body_exercise_name`.
enum TotalBodyExerciseName {
  burpee(0),
  weightedBurpee(1),
  burpeeBoxJump(2),
  weightedBurpeeBoxJump(3),
  highPullBurpee(4),
  manMakers(5),
  oneArmBurpee(6),
  squatThrusts(7),
  weightedSquatThrusts(8),
  squatPlankPushUp(9),
  weightedSquatPlankPushUp(10),
  standingTRotationBalance(11),
  weightedStandingTRotationBalance(12),
  barbellBurpee(13),
  burpeeBoxJumpOverYesLiterallyJumpingOverTheBox(15),
  burpeeBoxJumpStepUpOver(16),
  lateralBarbellBurpee(17),
  totalBodyBurpeeOverBar(18),
  burpeeBoxJumpOver(19),
  burpeeWheelchair(20),

  /// Returned for any raw value not present in the profile.
  invalid(65535);

  const TotalBodyExerciseName(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, TotalBodyExerciseName> _byValue = {
    for (final entry in TotalBodyExerciseName.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static TotalBodyExerciseName fromValue(int value) =>
      _byValue[value] ?? TotalBodyExerciseName.invalid;
}
