/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `triceps_extension_exercise_name`.
enum TricepsExtensionExerciseName {
  benchDip(0),
  weightedBenchDip(1),
  bodyWeightDip(2),
  cableKickback(3),
  cableLyingTricepsExtension(4),
  cableOverheadTricepsExtension(5),
  dumbbellKickback(6),
  dumbbellLyingTricepsExtension(7),
  ezBarOverheadTricepsExtension(8),
  inclineDip(9),
  weightedInclineDip(10),
  inclineEzBarLyingTricepsExtension(11),
  lyingDumbbellPulloverToExtension(12),
  lyingEzBarTricepsExtension(13),
  lyingTricepsExtensionToCloseGripBenchPress(14),
  overheadDumbbellTricepsExtension(15),
  recliningTricepsPress(16),
  reverseGripPressdown(17),
  reverseGripTricepsPressdown(18),
  ropePressdown(19),
  seatedBarbellOverheadTricepsExtension(20),
  seatedDumbbellOverheadTricepsExtension(21),
  seatedEzBarOverheadTricepsExtension(22),
  seatedSingleArmOverheadDumbbellExtension(23),
  singleArmDumbbellOverheadTricepsExtension(24),
  singleDumbbellSeatedOverheadTricepsExtension(25),
  singleLegBenchDipAndKick(26),
  weightedSingleLegBenchDipAndKick(27),
  singleLegDip(28),
  weightedSingleLegDip(29),
  staticLyingTricepsExtension(30),
  suspendedDip(31),
  weightedSuspendedDip(32),
  swissBallDumbbellLyingTricepsExtension(33),
  swissBallEzBarLyingTricepsExtension(34),
  swissBallEzBarOverheadTricepsExtension(35),
  tabletopDip(36),
  weightedTabletopDip(37),
  tricepsExtensionOnFloor(38),
  tricepsPressdown(39),
  weightedDip(40),
  alternatingDumbbellLyingTricepsExtension(41),
  tricepsPress(42),
  dumbbellKickbackWheelchair(43),
  overheadDumbbellTricepsExtensionWheelchair(44),

  /// Returned for any raw value not present in the profile.
  invalid(65535);

  const TricepsExtensionExerciseName(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, TricepsExtensionExerciseName> _byValue = {
    for (final entry in TricepsExtensionExerciseName.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static TricepsExtensionExerciseName fromValue(int value) =>
      _byValue[value] ?? TricepsExtensionExerciseName.invalid;
}
