/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `uiaa_grading_scale`.
enum UiaaGradingScale {
  i(0), // I
  iI(1), // II
  iII(2), // III
  iVMinus(3), // IV-
  iV(4), // IV
  iVPlus(5), // IV+
  vMinus(6), // V-
  v(7), // V
  vPlus(8), // V+
  vIMinus(9), // VI-
  vI(10), // VI
  vIPlus(11), // VI+
  vIIMinus(12), // VII-
  vII(13), // VII
  vIIPlus(14), // VII+
  vIIIMinus(15), // VIII-
  vIII(16), // VIII
  vIIIPlus(17), // VIII+
  iXMinus(18), // IX-
  iX(19), // IX
  iXPlus(20), // IX+
  xMinus(21), // X-
  x(22), // X
  xPlus(23), // X+
  xIMinus(24), // XI-
  xI(25), // XI
  xIPlus(26), // XI+
  xIIMinus(27), // XII-

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const UiaaGradingScale(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, UiaaGradingScale> _byValue = {
    for (final entry in UiaaGradingScale.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static UiaaGradingScale fromValue(int value) =>
      _byValue[value] ?? UiaaGradingScale.invalid;
}
