/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

/// FIT profile type `weather_severe_type`.
enum WeatherSevereType {
  unspecified(0),
  tornado(1),
  tsunami(2),
  hurricane(3),
  extremeWind(4),
  typhoon(5),
  inlandHurricane(6),
  hurricaneForceWind(7),
  waterspout(8),
  severeThunderstorm(9),
  wreckhouseWinds(10),
  lesSuetesWind(11),
  avalanche(12),
  flashFlood(13),
  tropicalStorm(14),
  inlandTropicalStorm(15),
  blizzard(16),
  iceStorm(17),
  freezingRain(18),
  debrisFlow(19),
  flashFreeze(20),
  dustStorm(21),
  highWind(22),
  winterStorm(23),
  heavyFreezingSpray(24),
  extremeCold(25),
  windChill(26),
  coldWave(27),
  heavySnowAlert(28),
  lakeEffectBlowingSnow(29),
  snowSquall(30),
  lakeEffectSnow(31),
  winterWeather(32),
  sleet(33),
  snowfall(34),
  snowAndBlowingSnow(35),
  blowingSnow(36),
  snowAlert(37),
  arcticOutflow(38),
  freezingDrizzle(39),
  storm(40),
  stormSurge(41),
  rainfall(42),
  arealFlood(43),
  coastalFlood(44),
  lakeshoreFlood(45),
  excessiveHeat(46),
  heat(47),
  weather(48),
  highHeatAndHumidity(49),
  humidexAndHealth(50),
  humidex(51),
  gale(52),
  freezingSpray(53),
  specialMarine(54),
  squall(55),
  strongWind(56),
  lakeWind(57),
  marineWeather(58),
  wind(59),
  smallCraftHazardousSeas(60),
  hazardousSeas(61),
  smallCraft(62),
  smallCraftWinds(63),
  smallCraftRoughBar(64),
  highWaterLevel(65),
  ashfall(66),
  freezingFog(67),
  denseFog(68),
  denseSmoke(69),
  blowingDust(70),
  hardFreeze(71),
  freeze(72),
  frost(73),
  fireWeather(74),
  flood(75),
  ripTide(76),
  highSurf(77),
  smog(78),
  airQuality(79),
  briskWind(80),
  airStagnation(81),
  lowWater(82),
  hydrological(83),
  specialWeather(84),

  /// Returned for any raw value not present in the profile.
  invalid(255);

  const WeatherSevereType(this.value);

  /// The raw value as it appears in a FIT file.
  final int value;

  static final Map<int, WeatherSevereType> _byValue = {
    for (final entry in WeatherSevereType.values) entry.value: entry,
  };

  /// Maps a raw FIT value onto its enum entry, falling back to [invalid].
  static WeatherSevereType fromValue(int value) =>
      _byValue[value] ?? WeatherSevereType.invalid;
}
